/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class CManagerInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CManagerInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CManagerInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_CManagerInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int QueryInterface(SWIGTYPE_p_p_void riid, SWIGTYPE_p_p_void obj) {
    return mtmanapiJNI.CManagerInterface_QueryInterface(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(riid), SWIGTYPE_p_p_void.getCPtr(obj));
  }

  public int AddRef() {
    return mtmanapiJNI.CManagerInterface_AddRef(swigCPtr, this);
  }

  public int Release() {
    return mtmanapiJNI.CManagerInterface_Release(swigCPtr, this);
  }

  public void MemFree(SWIGTYPE_p_void ptr) {
    mtmanapiJNI.CManagerInterface_MemFree(swigCPtr, this, SWIGTYPE_p_void.getCPtr(ptr));
  }

  public String ErrorDescription(int code) {
    return mtmanapiJNI.CManagerInterface_ErrorDescription(swigCPtr, this, code);
  }

  public void WorkingDirectory(String path) {
    mtmanapiJNI.CManagerInterface_WorkingDirectory(swigCPtr, this, path);
  }

  public int Connect(String server) {
    return mtmanapiJNI.CManagerInterface_Connect(swigCPtr, this, server);
  }

  public int Disconnect() {
    return mtmanapiJNI.CManagerInterface_Disconnect(swigCPtr, this);
  }

  public int IsConnected() {
    return mtmanapiJNI.CManagerInterface_IsConnected(swigCPtr, this);
  }

  public int Login(int login, String password) {
    return mtmanapiJNI.CManagerInterface_Login(swigCPtr, this, login, password);
  }

  public int LoginSecured(String key_path) {
    return mtmanapiJNI.CManagerInterface_LoginSecured(swigCPtr, this, key_path);
  }

  public int KeysSend(String key_path) {
    return mtmanapiJNI.CManagerInterface_KeysSend(swigCPtr, this, key_path);
  }

  public int Ping() {
    return mtmanapiJNI.CManagerInterface_Ping(swigCPtr, this);
  }

  public int PasswordChange(String pass, int is_investor) {
    return mtmanapiJNI.CManagerInterface_PasswordChange(swigCPtr, this, pass, is_investor);
  }

  public int ManagerRights(ConManager man) {
    return mtmanapiJNI.CManagerInterface_ManagerRights(swigCPtr, this, ConManager.getCPtr(man), man);
  }

  public int SrvRestart() {
    return mtmanapiJNI.CManagerInterface_SrvRestart(swigCPtr, this);
  }

  public int SrvChartsSync() {
    return mtmanapiJNI.CManagerInterface_SrvChartsSync(swigCPtr, this);
  }

  public int SrvLiveUpdateStart() {
    return mtmanapiJNI.CManagerInterface_SrvLiveUpdateStart(swigCPtr, this);
  }

  public int SrvFeedsRestart() {
    return mtmanapiJNI.CManagerInterface_SrvFeedsRestart(swigCPtr, this);
  }

  public int CfgRequestCommon(ConCommon cfg) {
    return mtmanapiJNI.CManagerInterface_CfgRequestCommon(swigCPtr, this, ConCommon.getCPtr(cfg), cfg);
  }

  public int CfgRequestTime(ConTime cfg) {
    return mtmanapiJNI.CManagerInterface_CfgRequestTime(swigCPtr, this, ConTime.getCPtr(cfg), cfg);
  }

  public int CfgRequestBackup(ConBackup cfg) {
    return mtmanapiJNI.CManagerInterface_CfgRequestBackup(swigCPtr, this, ConBackup.getCPtr(cfg), cfg);
  }

  public int CfgRequestSymbolGroup(ConSymbolGroup cfg) {
    return mtmanapiJNI.CManagerInterface_CfgRequestSymbolGroup(swigCPtr, this, ConSymbolGroup.getCPtr(cfg), cfg);
  }

  public ConAccess CfgRequestAccess(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestAccess(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConAccess(cPtr, false);
  }

  public ConDataServer CfgRequestDataServer(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestDataServer(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConDataServer(cPtr, false);
  }

  public ConHoliday CfgRequestHoliday(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestHoliday(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConHoliday(cPtr, false);
  }

  public ConSymbol CfgRequestSymbol(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestSymbol(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConSymbol(cPtr, false);
  }

  public ConGroup CfgRequestGroup(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestGroup(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConGroup(cPtr, false);
  }

  public ConManager CfgRequestManager(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestManager(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConManager(cPtr, false);
  }

  public ConFeeder CfgRequestFeeder(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestFeeder(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConFeeder(cPtr, false);
  }

  public ConLiveUpdate CfgRequestLiveUpdate(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestLiveUpdate(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConLiveUpdate(cPtr, false);
  }

  public ConSync CfgRequestSync(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestSync(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConSync(cPtr, false);
  }

  public ConPluginParam CfgRequestPlugin(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestPlugin(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConPluginParam(cPtr, false);
  }

  public int CfgUpdateCommon(ConCommon cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateCommon(swigCPtr, this, ConCommon.getCPtr(cfg), cfg);
  }

  public int CfgUpdateAccess(ConAccess cfg, int pos) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateAccess(swigCPtr, this, ConAccess.getCPtr(cfg), cfg, pos);
  }

  public int CfgUpdateDataServer(ConDataServer cfg, int pos) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateDataServer(swigCPtr, this, ConDataServer.getCPtr(cfg), cfg, pos);
  }

  public int CfgUpdateTime(ConTime cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateTime(swigCPtr, this, ConTime.getCPtr(cfg), cfg);
  }

  public int CfgUpdateHoliday(ConHoliday cfg, int pos) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateHoliday(swigCPtr, this, ConHoliday.getCPtr(cfg), cfg, pos);
  }

  public int CfgUpdateSymbol(ConSymbol cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateSymbol(swigCPtr, this, ConSymbol.getCPtr(cfg), cfg);
  }

  public int CfgUpdateSymbolGroup(ConSymbolGroup cfg, int pos) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateSymbolGroup(swigCPtr, this, ConSymbolGroup.getCPtr(cfg), cfg, pos);
  }

  public int CfgUpdateGroup(ConGroup cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateGroup(swigCPtr, this, ConGroup.getCPtr(cfg), cfg);
  }

  public int CfgUpdateManager(ConManager cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateManager(swigCPtr, this, ConManager.getCPtr(cfg), cfg);
  }

  public int CfgUpdateFeeder(ConFeeder cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateFeeder(swigCPtr, this, ConFeeder.getCPtr(cfg), cfg);
  }

  public int CfgUpdateBackup(ConBackup cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateBackup(swigCPtr, this, ConBackup.getCPtr(cfg), cfg);
  }

  public int CfgUpdateLiveUpdate(ConLiveUpdate cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateLiveUpdate(swigCPtr, this, ConLiveUpdate.getCPtr(cfg), cfg);
  }

  public int CfgUpdateSync(ConSync cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateSync(swigCPtr, this, ConSync.getCPtr(cfg), cfg);
  }

  public int CfgUpdatePlugin(ConPlugin cfg, PluginCfg parupd, int total) {
    return mtmanapiJNI.CManagerInterface_CfgUpdatePlugin(swigCPtr, this, ConPlugin.getCPtr(cfg), cfg, PluginCfg.getCPtr(parupd), parupd, total);
  }

  public int CfgDeleteAccess(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteAccess(swigCPtr, this, pos);
  }

  public int CfgDeleteDataServer(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteDataServer(swigCPtr, this, pos);
  }

  public int CfgDeleteHoliday(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteHoliday(swigCPtr, this, pos);
  }

  public int CfgDeleteSymbol(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteSymbol(swigCPtr, this, pos);
  }

  public int CfgDeleteGroup(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteGroup(swigCPtr, this, pos);
  }

  public int CfgDeleteManager(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteManager(swigCPtr, this, pos);
  }

  public int CfgDeleteFeeder(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteFeeder(swigCPtr, this, pos);
  }

  public int CfgDeleteLiveUpdate(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteLiveUpdate(swigCPtr, this, pos);
  }

  public int CfgDeleteSync(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteSync(swigCPtr, this, pos);
  }

  public int CfgShiftAccess(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftAccess(swigCPtr, this, pos, shift);
  }

  public int CfgShiftDataServer(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftDataServer(swigCPtr, this, pos, shift);
  }

  public int CfgShiftHoliday(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftHoliday(swigCPtr, this, pos, shift);
  }

  public int CfgShiftSymbol(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftSymbol(swigCPtr, this, pos, shift);
  }

  public int CfgShiftGroup(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftGroup(swigCPtr, this, pos, shift);
  }

  public int CfgShiftManager(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftManager(swigCPtr, this, pos, shift);
  }

  public int CfgShiftFeeder(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftFeeder(swigCPtr, this, pos, shift);
  }

  public int CfgShiftLiveUpdate(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftLiveUpdate(swigCPtr, this, pos, shift);
  }

  public int CfgShiftSync(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftSync(swigCPtr, this, pos, shift);
  }

  public int CfgShiftPlugin(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftPlugin(swigCPtr, this, pos, shift);
  }

  public ServerFeed SrvFeeders(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_SrvFeeders(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ServerFeed(cPtr, false);
  }

  public String SrvFeederLog(String name, SWIGTYPE_p_int len) {
    return mtmanapiJNI.CManagerInterface_SrvFeederLog(swigCPtr, this, name, SWIGTYPE_p_int.getCPtr(len));
  }

  public RateInfoOld ChartRequestObsolete(ChartInfo chart, SWIGTYPE_p_int timesign, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_ChartRequestObsolete(swigCPtr, this, ChartInfo.getCPtr(chart), chart, SWIGTYPE_p_int.getCPtr(timesign), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new RateInfoOld(cPtr, false);
  }

  public int ChartAddObsolete(String symbol, int period, RateInfoOld rates, SWIGTYPE_p_int count) {
    return mtmanapiJNI.CManagerInterface_ChartAddObsolete(swigCPtr, this, symbol, period, RateInfoOld.getCPtr(rates), rates, SWIGTYPE_p_int.getCPtr(count));
  }

  public int ChartUpdateObsolete(String symbol, int period, RateInfoOld rates, SWIGTYPE_p_int count) {
    return mtmanapiJNI.CManagerInterface_ChartUpdateObsolete(swigCPtr, this, symbol, period, RateInfoOld.getCPtr(rates), rates, SWIGTYPE_p_int.getCPtr(count));
  }

  public int ChartDeleteObsolete(String symbol, int period, RateInfoOld rates, SWIGTYPE_p_int count) {
    return mtmanapiJNI.CManagerInterface_ChartDeleteObsolete(swigCPtr, this, symbol, period, RateInfoOld.getCPtr(rates), rates, SWIGTYPE_p_int.getCPtr(count));
  }

  public PerformanceInfo PerformanceRequest(int from, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_PerformanceRequest(swigCPtr, this, from, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new PerformanceInfo(cPtr, false);
  }

  public BackupInfo BackupInfoUsers(int mode, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_BackupInfoUsers(swigCPtr, this, mode, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new BackupInfo(cPtr, false);
  }

  public BackupInfo BackupInfoOrders(int mode, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_BackupInfoOrders(swigCPtr, this, mode, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new BackupInfo(cPtr, false);
  }

  public UserRecord BackupRequestUsers(String file, String request, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_BackupRequestUsers(swigCPtr, this, file, request, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public TradeRecord BackupRequestOrders(String file, String request, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_BackupRequestOrders(swigCPtr, this, file, request, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public int BackupRestoreUsers(UserRecord users, int total) {
    return mtmanapiJNI.CManagerInterface_BackupRestoreUsers(swigCPtr, this, UserRecord.getCPtr(users), users, total);
  }

  public TradeRestoreResult BackupRestoreOrders(TradeRecord trades, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_BackupRestoreOrders(swigCPtr, this, TradeRecord.getCPtr(trades), trades, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRestoreResult(cPtr, false);
  }

  public UserRecord AdmUsersRequest(String group, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_AdmUsersRequest(swigCPtr, this, group, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public TradeRecord AdmTradesRequest(String group, int open_only, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_AdmTradesRequest(swigCPtr, this, group, open_only, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public int AdmBalanceCheckObsolete(SWIGTYPE_p_int logins, SWIGTYPE_p_int total) {
    return mtmanapiJNI.CManagerInterface_AdmBalanceCheckObsolete(swigCPtr, this, SWIGTYPE_p_int.getCPtr(logins), SWIGTYPE_p_int.getCPtr(total));
  }

  public int AdmBalanceFix(SWIGTYPE_p_int logins, int total) {
    return mtmanapiJNI.CManagerInterface_AdmBalanceFix(swigCPtr, this, SWIGTYPE_p_int.getCPtr(logins), total);
  }

  public int AdmTradesDelete(SWIGTYPE_p_int orders, int total) {
    return mtmanapiJNI.CManagerInterface_AdmTradesDelete(swigCPtr, this, SWIGTYPE_p_int.getCPtr(orders), total);
  }

  public int AdmTradeRecordModify(TradeRecord trade) {
    return mtmanapiJNI.CManagerInterface_AdmTradeRecordModify(swigCPtr, this, TradeRecord.getCPtr(trade), trade);
  }

  public int SymbolsRefresh() {
    return mtmanapiJNI.CManagerInterface_SymbolsRefresh(swigCPtr, this);
  }

  public ConSymbol SymbolsGetAll(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_SymbolsGetAll(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConSymbol(cPtr, false);
  }

  public int SymbolGet(String symbol, ConSymbol cs) {
    return mtmanapiJNI.CManagerInterface_SymbolGet(swigCPtr, this, symbol, ConSymbol.getCPtr(cs), cs);
  }

  public int SymbolInfoGet(String symbol, SymbolInfo si) {
    return mtmanapiJNI.CManagerInterface_SymbolInfoGet(swigCPtr, this, symbol, SymbolInfo.getCPtr(si), si);
  }

  public int SymbolAdd(String symbol) {
    return mtmanapiJNI.CManagerInterface_SymbolAdd(swigCPtr, this, symbol);
  }

  public int SymbolHide(String symbol) {
    return mtmanapiJNI.CManagerInterface_SymbolHide(swigCPtr, this, symbol);
  }

  public int SymbolChangeObsolete(SymbolPropertiesOld prop) {
    return mtmanapiJNI.CManagerInterface_SymbolChangeObsolete(swigCPtr, this, SymbolPropertiesOld.getCPtr(prop), prop);
  }

  public int SymbolSendTick(String symbol, double bid, double ask) {
    return mtmanapiJNI.CManagerInterface_SymbolSendTick(swigCPtr, this, symbol, bid, ask);
  }

  public ConGroup GroupsRequest(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_GroupsRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConGroup(cPtr, false);
  }

  public int MailSend(MailBox mail, SWIGTYPE_p_int logins) {
    return mtmanapiJNI.CManagerInterface_MailSend(swigCPtr, this, MailBox.getCPtr(mail), mail, SWIGTYPE_p_int.getCPtr(logins));
  }

  public int NewsSend(NewsTopic news) {
    return mtmanapiJNI.CManagerInterface_NewsSend(swigCPtr, this, NewsTopic.getCPtr(news), news);
  }

  public ServerLog JournalRequest(int mode, int from, int to, String filter, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_JournalRequest(swigCPtr, this, mode, from, to, filter, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ServerLog(cPtr, false);
  }

  public UserRecord UsersRequest(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_UsersRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public UserRecord UserRecordsRequest(SWIGTYPE_p_int logins, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_UserRecordsRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(logins), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public int UserRecordNew(UserRecord user) {
    return mtmanapiJNI.CManagerInterface_UserRecordNew(swigCPtr, this, UserRecord.getCPtr(user), user);
  }

  public int UserRecordUpdate(UserRecord user) {
    return mtmanapiJNI.CManagerInterface_UserRecordUpdate(swigCPtr, this, UserRecord.getCPtr(user), user);
  }

  public int UsersGroupOp(GroupCommandInfo info, SWIGTYPE_p_int logins) {
    return mtmanapiJNI.CManagerInterface_UsersGroupOp(swigCPtr, this, GroupCommandInfo.getCPtr(info), info, SWIGTYPE_p_int.getCPtr(logins));
  }

  public int UserPasswordCheck(int login, String password) {
    return mtmanapiJNI.CManagerInterface_UserPasswordCheck(swigCPtr, this, login, password);
  }

  public int UserPasswordSet(int login, String password, int change_investor, int clean_pubkey) {
    return mtmanapiJNI.CManagerInterface_UserPasswordSet(swigCPtr, this, login, password, change_investor, clean_pubkey);
  }

  public OnlineRecord OnlineRequest(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_OnlineRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new OnlineRecord(cPtr, false);
  }

  public int TradeTransaction(TradeTransInfo info) {
    return mtmanapiJNI.CManagerInterface_TradeTransaction(swigCPtr, this, TradeTransInfo.getCPtr(info), info);
  }

  public TradeRecord TradesRequest(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public TradeRecord TradeRecordsRequest(SWIGTYPE_p_int orders, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradeRecordsRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(orders), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public TradeRecord TradesUserHistory(int login, int from, int to, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesUserHistory(swigCPtr, this, login, from, to, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public int TradeCheckStops(TradeTransInfo trade, double price) {
    return mtmanapiJNI.CManagerInterface_TradeCheckStops(swigCPtr, this, TradeTransInfo.getCPtr(trade), trade, price);
  }

  public TradeRecord ReportsRequest(ReportGroupRequest req, SWIGTYPE_p_int logins, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_ReportsRequest(swigCPtr, this, ReportGroupRequest.getCPtr(req), req, SWIGTYPE_p_int.getCPtr(logins), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public DailyReport DailyReportsRequest(DailyGroupRequest req, SWIGTYPE_p_int logins, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_DailyReportsRequest(swigCPtr, this, DailyGroupRequest.getCPtr(req), req, SWIGTYPE_p_int.getCPtr(logins), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new DailyReport(cPtr, false);
  }

  public int ExternalCommand(String data_in, int size_in, SWIGTYPE_p_p_char data_out, SWIGTYPE_p_int size_out) {
    return mtmanapiJNI.CManagerInterface_ExternalCommand(swigCPtr, this, data_in, size_in, SWIGTYPE_p_p_char.getCPtr(data_out), SWIGTYPE_p_int.getCPtr(size_out));
  }

  public int PluginUpdate(ConPluginParam plugin) {
    return mtmanapiJNI.CManagerInterface_PluginUpdate(swigCPtr, this, ConPluginParam.getCPtr(plugin), plugin);
  }

  public int PumpingSwitch(SWIGTYPE_p_f_int__void pfnFunc, SWIGTYPE_p_HWND destwnd, long eventmsg, int flags) {
    return mtmanapiJNI.CManagerInterface_PumpingSwitch(swigCPtr, this, SWIGTYPE_p_f_int__void.getCPtr(pfnFunc), SWIGTYPE_p_HWND.getCPtr(destwnd), eventmsg, flags);
  }

  public ConGroup GroupsGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_GroupsGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConGroup(cPtr, false);
  }

  public int GroupRecordGet(String name, ConGroup group) {
    return mtmanapiJNI.CManagerInterface_GroupRecordGet(swigCPtr, this, name, ConGroup.getCPtr(group), group);
  }

  public int SymbolInfoUpdated(SymbolInfo si, int max_info) {
    return mtmanapiJNI.CManagerInterface_SymbolInfoUpdated(swigCPtr, this, SymbolInfo.getCPtr(si), si, max_info);
  }

  public UserRecord UsersGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_UsersGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public int UserRecordGet(int login, UserRecord user) {
    return mtmanapiJNI.CManagerInterface_UserRecordGet(swigCPtr, this, login, UserRecord.getCPtr(user), user);
  }

  public OnlineRecord OnlineGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_OnlineGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new OnlineRecord(cPtr, false);
  }

  public int OnlineRecordGet(int login, OnlineRecord user) {
    return mtmanapiJNI.CManagerInterface_OnlineRecordGet(swigCPtr, this, login, OnlineRecord.getCPtr(user), user);
  }

  public TradeRecord TradesGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public TradeRecord TradesGetBySymbol(String symbol, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesGetBySymbol(swigCPtr, this, symbol, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public TradeRecord TradesGetByLogin(int login, String group, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesGetByLogin(swigCPtr, this, login, group, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public TradeRecord TradesGetByMarket(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesGetByMarket(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public int TradeRecordGet(int order, TradeRecord trade) {
    return mtmanapiJNI.CManagerInterface_TradeRecordGet(swigCPtr, this, order, TradeRecord.getCPtr(trade), trade);
  }

  public int TradeClearRollback(int order) {
    return mtmanapiJNI.CManagerInterface_TradeClearRollback(swigCPtr, this, order);
  }

  public MarginLevel MarginsGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_MarginsGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new MarginLevel(cPtr, false);
  }

  public int MarginLevelGet(int login, String group, MarginLevel margin) {
    return mtmanapiJNI.CManagerInterface_MarginLevelGet(swigCPtr, this, login, group, MarginLevel.getCPtr(margin), margin);
  }

  public RequestInfo RequestsGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_RequestsGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new RequestInfo(cPtr, false);
  }

  public int RequestInfoGet(int pos, RequestInfo info) {
    return mtmanapiJNI.CManagerInterface_RequestInfoGet(swigCPtr, this, pos, RequestInfo.getCPtr(info), info);
  }

  public ConPlugin PluginsGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_PluginsGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConPlugin(cPtr, false);
  }

  public int PluginParamGet(int pos, ConPluginParam plugin) {
    return mtmanapiJNI.CManagerInterface_PluginParamGet(swigCPtr, this, pos, ConPluginParam.getCPtr(plugin), plugin);
  }

  public int MailLast(String path, SWIGTYPE_p_int length) {
    return mtmanapiJNI.CManagerInterface_MailLast(swigCPtr, this, path, SWIGTYPE_p_int.getCPtr(length));
  }

  public NewsTopic NewsGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_NewsGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new NewsTopic(cPtr, false);
  }

  public int NewsTotal() {
    return mtmanapiJNI.CManagerInterface_NewsTotal(swigCPtr, this);
  }

  public int NewsTopicGet(int pos, NewsTopic news) {
    return mtmanapiJNI.CManagerInterface_NewsTopicGet(swigCPtr, this, pos, NewsTopic.getCPtr(news), news);
  }

  public void NewsBodyRequest(int key) {
    mtmanapiJNI.CManagerInterface_NewsBodyRequest(swigCPtr, this, key);
  }

  public String NewsBodyGet(int key) {
    return mtmanapiJNI.CManagerInterface_NewsBodyGet(swigCPtr, this, key);
  }

  public int DealerSwitch(SWIGTYPE_p_f_int__void pfnFunc, SWIGTYPE_p_HWND destwnd, long eventmsg) {
    return mtmanapiJNI.CManagerInterface_DealerSwitch(swigCPtr, this, SWIGTYPE_p_f_int__void.getCPtr(pfnFunc), SWIGTYPE_p_HWND.getCPtr(destwnd), eventmsg);
  }

  public int DealerRequestGet(RequestInfo info) {
    return mtmanapiJNI.CManagerInterface_DealerRequestGet(swigCPtr, this, RequestInfo.getCPtr(info), info);
  }

  public int DealerSend(RequestInfo info, int requote, int mode) {
    return mtmanapiJNI.CManagerInterface_DealerSend(swigCPtr, this, RequestInfo.getCPtr(info), info, requote, mode);
  }

  public int DealerReject(int id) {
    return mtmanapiJNI.CManagerInterface_DealerReject(swigCPtr, this, id);
  }

  public int DealerReset(int id) {
    return mtmanapiJNI.CManagerInterface_DealerReset(swigCPtr, this, id);
  }

  public TickInfo TickInfoLast(String symbol, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TickInfoLast(swigCPtr, this, symbol, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TickInfo(cPtr, false);
  }

  public int SymbolsGroupsGet(ConSymbolGroup grp) {
    return mtmanapiJNI.CManagerInterface_SymbolsGroupsGet(swigCPtr, this, ConSymbolGroup.getCPtr(grp), grp);
  }

  public int ServerTime() {
    return mtmanapiJNI.CManagerInterface_ServerTime(swigCPtr, this);
  }

  public MailBox MailsRequest(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_MailsRequest(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new MailBox(cPtr, false);
  }

  public SymbolSummary SummaryGetAll(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_SummaryGetAll(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new SymbolSummary(cPtr, false);
  }

  public int SummaryGet(String symbol, SymbolSummary info) {
    return mtmanapiJNI.CManagerInterface_SummaryGet(swigCPtr, this, symbol, SymbolSummary.getCPtr(info), info);
  }

  public int SummaryGetByCount(int symbol, SymbolSummary info) {
    return mtmanapiJNI.CManagerInterface_SummaryGetByCount(swigCPtr, this, symbol, SymbolSummary.getCPtr(info), info);
  }

  public int SummaryGetByType(int sectype, SymbolSummary info) {
    return mtmanapiJNI.CManagerInterface_SummaryGetByType(swigCPtr, this, sectype, SymbolSummary.getCPtr(info), info);
  }

  public int SummaryCurrency(String cur, int maxchars) {
    return mtmanapiJNI.CManagerInterface_SummaryCurrency(swigCPtr, this, cur, maxchars);
  }

  public ExposureValue ExposureGet(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_ExposureGet(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ExposureValue(cPtr, false);
  }

  public int ExposureValueGet(String cur, ExposureValue info) {
    return mtmanapiJNI.CManagerInterface_ExposureValueGet(swigCPtr, this, cur, ExposureValue.getCPtr(info), info);
  }

  public int MarginLevelRequest(int login, MarginLevel level) {
    return mtmanapiJNI.CManagerInterface_MarginLevelRequest(swigCPtr, this, login, MarginLevel.getCPtr(level), level);
  }

  public int HistoryCorrect(String symbol, SWIGTYPE_p_int updated) {
    return mtmanapiJNI.CManagerInterface_HistoryCorrect(swigCPtr, this, symbol, SWIGTYPE_p_int.getCPtr(updated));
  }

  public RateInfo ChartRequest(ChartInfo chart, SWIGTYPE_p_int timesign, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_ChartRequest(swigCPtr, this, ChartInfo.getCPtr(chart), chart, SWIGTYPE_p_int.getCPtr(timesign), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new RateInfo(cPtr, false);
  }

  public int ChartAdd(String symbol, int period, RateInfo rates, SWIGTYPE_p_int count) {
    return mtmanapiJNI.CManagerInterface_ChartAdd(swigCPtr, this, symbol, period, RateInfo.getCPtr(rates), rates, SWIGTYPE_p_int.getCPtr(count));
  }

  public int ChartUpdate(String symbol, int period, RateInfo rates, SWIGTYPE_p_int count) {
    return mtmanapiJNI.CManagerInterface_ChartUpdate(swigCPtr, this, symbol, period, RateInfo.getCPtr(rates), rates, SWIGTYPE_p_int.getCPtr(count));
  }

  public int ChartDelete(String symbol, int period, RateInfo rates, SWIGTYPE_p_int count) {
    return mtmanapiJNI.CManagerInterface_ChartDelete(swigCPtr, this, symbol, period, RateInfo.getCPtr(rates), rates, SWIGTYPE_p_int.getCPtr(count));
  }

  public TickRecord TicksRequest(TickRequest request, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TicksRequest(swigCPtr, this, TickRequest.getCPtr(request), request, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new TickRecord(cPtr, false);
  }

  public int PumpingSwitchEx(SWIGTYPE_p_f_int_int_p_void_p_void__void pfnFunc, int flags, SWIGTYPE_p_void param) {
    return mtmanapiJNI.CManagerInterface_PumpingSwitchEx(swigCPtr, this, SWIGTYPE_p_f_int_int_p_void_p_void__void.getCPtr(pfnFunc), flags, SWIGTYPE_p_void.getCPtr(param));
  }

  public int UsersSyncStart(int timestamp) {
    return mtmanapiJNI.CManagerInterface_UsersSyncStart(swigCPtr, this, timestamp);
  }

  public UserRecord UsersSyncRead(SWIGTYPE_p_int users_total) {
    long cPtr = mtmanapiJNI.CManagerInterface_UsersSyncRead(swigCPtr, this, SWIGTYPE_p_int.getCPtr(users_total));
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public SWIGTYPE_p_int UsersSnapshot(SWIGTYPE_p_int users_total) {
    long cPtr = mtmanapiJNI.CManagerInterface_UsersSnapshot(swigCPtr, this, SWIGTYPE_p_int.getCPtr(users_total));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public int TradesSyncStart(int timestamp) {
    return mtmanapiJNI.CManagerInterface_TradesSyncStart(swigCPtr, this, timestamp);
  }

  public TradeRecord TradesSyncRead(SWIGTYPE_p_int trades_total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesSyncRead(swigCPtr, this, SWIGTYPE_p_int.getCPtr(trades_total));
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public SWIGTYPE_p_int TradesSnapshot(SWIGTYPE_p_int trades_total) {
    long cPtr = mtmanapiJNI.CManagerInterface_TradesSnapshot(swigCPtr, this, SWIGTYPE_p_int.getCPtr(trades_total));
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public int DailySyncStart(int timestamp) {
    return mtmanapiJNI.CManagerInterface_DailySyncStart(swigCPtr, this, timestamp);
  }

  public DailyReport DailySyncRead(SWIGTYPE_p_int daily_total) {
    long cPtr = mtmanapiJNI.CManagerInterface_DailySyncRead(swigCPtr, this, SWIGTYPE_p_int.getCPtr(daily_total));
    return (cPtr == 0) ? null : new DailyReport(cPtr, false);
  }

  public int TradeCalcProfit(TradeRecord trade) {
    return mtmanapiJNI.CManagerInterface_TradeCalcProfit(swigCPtr, this, TradeRecord.getCPtr(trade), trade);
  }

  public int SymbolChange(SymbolProperties prop) {
    return mtmanapiJNI.CManagerInterface_SymbolChange(swigCPtr, this, SymbolProperties.getCPtr(prop), prop);
  }

  public int BytesSent() {
    return mtmanapiJNI.CManagerInterface_BytesSent(swigCPtr, this);
  }

  public int BytesReceived() {
    return mtmanapiJNI.CManagerInterface_BytesReceived(swigCPtr, this);
  }

  public int ManagerCommon(ConCommon common) {
    return mtmanapiJNI.CManagerInterface_ManagerCommon(swigCPtr, this, ConCommon.getCPtr(common), common);
  }

  public void LogsOut(int code, String source, String msg) {
    mtmanapiJNI.CManagerInterface_LogsOut(swigCPtr, this, code, source, msg);
  }

  public void LogsMode(int mode) {
    mtmanapiJNI.CManagerInterface_LogsMode(swigCPtr, this, mode);
  }

  public int LicenseCheck(String license_name) {
    return mtmanapiJNI.CManagerInterface_LicenseCheck(swigCPtr, this, license_name);
  }

  public ConGatewayAccount CfgRequestGatewayAccount(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestGatewayAccount(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConGatewayAccount(cPtr, false);
  }

  public ConGatewayMarkup CfgRequestGatewayMarkup(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestGatewayMarkup(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConGatewayMarkup(cPtr, false);
  }

  public ConGatewayRule CfgRequestGatewayRule(SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_CfgRequestGatewayRule(swigCPtr, this, SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new ConGatewayRule(cPtr, false);
  }

  public int CfgUpdateGatewayAccount(ConGatewayAccount cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateGatewayAccount(swigCPtr, this, ConGatewayAccount.getCPtr(cfg), cfg);
  }

  public int CfgUpdateGatewayMarkup(ConGatewayMarkup cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateGatewayMarkup(swigCPtr, this, ConGatewayMarkup.getCPtr(cfg), cfg);
  }

  public int CfgUpdateGatewayRule(ConGatewayRule cfg) {
    return mtmanapiJNI.CManagerInterface_CfgUpdateGatewayRule(swigCPtr, this, ConGatewayRule.getCPtr(cfg), cfg);
  }

  public int CfgDeleteGatewayAccount(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteGatewayAccount(swigCPtr, this, pos);
  }

  public int CfgDeleteGatewayMarkup(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteGatewayMarkup(swigCPtr, this, pos);
  }

  public int CfgDeleteGatewayRule(int pos) {
    return mtmanapiJNI.CManagerInterface_CfgDeleteGatewayRule(swigCPtr, this, pos);
  }

  public int CfgShiftGatewayAccount(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftGatewayAccount(swigCPtr, this, pos, shift);
  }

  public int CfgShiftGatewayMarkup(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftGatewayMarkup(swigCPtr, this, pos, shift);
  }

  public int CfgShiftGatewayRule(int pos, int shift) {
    return mtmanapiJNI.CManagerInterface_CfgShiftGatewayRule(swigCPtr, this, pos, shift);
  }

  public BalanceDiff AdmBalanceCheck(SWIGTYPE_p_int logins, SWIGTYPE_p_int total) {
    long cPtr = mtmanapiJNI.CManagerInterface_AdmBalanceCheck(swigCPtr, this, SWIGTYPE_p_int.getCPtr(logins), SWIGTYPE_p_int.getCPtr(total));
    return (cPtr == 0) ? null : new BalanceDiff(cPtr, false);
  }

  public int NotificationsSend(SWIGTYPE_p_LPWSTR metaquotes_ids, SWIGTYPE_p_LPCWSTR message) {
    return mtmanapiJNI.CManagerInterface_NotificationsSend__SWIG_0(swigCPtr, this, SWIGTYPE_p_LPWSTR.getCPtr(metaquotes_ids), SWIGTYPE_p_LPCWSTR.getCPtr(message));
  }

  public int NotificationsSend(SWIGTYPE_p_int logins, long logins_total, SWIGTYPE_p_LPCWSTR message) {
    return mtmanapiJNI.CManagerInterface_NotificationsSend__SWIG_1(swigCPtr, this, SWIGTYPE_p_int.getCPtr(logins), logins_total, SWIGTYPE_p_LPCWSTR.getCPtr(message));
  }

}
