/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConFeeder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConFeeder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConFeeder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConFeeder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    mtmanapiJNI.ConFeeder_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.ConFeeder_name_get(swigCPtr, this);
  }

  public void setFile(String value) {
    mtmanapiJNI.ConFeeder_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return mtmanapiJNI.ConFeeder_file_get(swigCPtr, this);
  }

  public void setServer(String value) {
    mtmanapiJNI.ConFeeder_server_set(swigCPtr, this, value);
  }

  public String getServer() {
    return mtmanapiJNI.ConFeeder_server_get(swigCPtr, this);
  }

  public void setLogin(String value) {
    mtmanapiJNI.ConFeeder_login_set(swigCPtr, this, value);
  }

  public String getLogin() {
    return mtmanapiJNI.ConFeeder_login_get(swigCPtr, this);
  }

  public void setPass(String value) {
    mtmanapiJNI.ConFeeder_pass_set(swigCPtr, this, value);
  }

  public String getPass() {
    return mtmanapiJNI.ConFeeder_pass_get(swigCPtr, this);
  }

  public void setKeywords(String value) {
    mtmanapiJNI.ConFeeder_keywords_set(swigCPtr, this, value);
  }

  public String getKeywords() {
    return mtmanapiJNI.ConFeeder_keywords_get(swigCPtr, this);
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConFeeder_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConFeeder_enable_get(swigCPtr, this);
  }

  public void setMode(int value) {
    mtmanapiJNI.ConFeeder_mode_set(swigCPtr, this, value);
  }

  public int getMode() {
    return mtmanapiJNI.ConFeeder_mode_get(swigCPtr, this);
  }

  public void setTimeout(int value) {
    mtmanapiJNI.ConFeeder_timeout_set(swigCPtr, this, value);
  }

  public int getTimeout() {
    return mtmanapiJNI.ConFeeder_timeout_get(swigCPtr, this);
  }

  public void setTimeout_reconnect(int value) {
    mtmanapiJNI.ConFeeder_timeout_reconnect_set(swigCPtr, this, value);
  }

  public int getTimeout_reconnect() {
    return mtmanapiJNI.ConFeeder_timeout_reconnect_get(swigCPtr, this);
  }

  public void setTimeout_sleep(int value) {
    mtmanapiJNI.ConFeeder_timeout_sleep_set(swigCPtr, this, value);
  }

  public int getTimeout_sleep() {
    return mtmanapiJNI.ConFeeder_timeout_sleep_get(swigCPtr, this);
  }

  public void setAttemps_sleep(int value) {
    mtmanapiJNI.ConFeeder_attemps_sleep_set(swigCPtr, this, value);
  }

  public int getAttemps_sleep() {
    return mtmanapiJNI.ConFeeder_attemps_sleep_get(swigCPtr, this);
  }

  public void setNews_langid(int value) {
    mtmanapiJNI.ConFeeder_news_langid_set(swigCPtr, this, value);
  }

  public int getNews_langid() {
    return mtmanapiJNI.ConFeeder_news_langid_get(swigCPtr, this);
  }

  public void setUnused(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConFeeder_unused_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getUnused() {
    long cPtr = mtmanapiJNI.ConFeeder_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConFeeder() {
    this(mtmanapiJNI.new_ConFeeder(), true);
  }

}
