/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConGroupSec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConGroupSec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConGroupSec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConGroupSec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setShow(int value) {
    mtmanapiJNI.ConGroupSec_show_set(swigCPtr, this, value);
  }

  public int getShow() {
    return mtmanapiJNI.ConGroupSec_show_get(swigCPtr, this);
  }

  public void setTrade(int value) {
    mtmanapiJNI.ConGroupSec_trade_set(swigCPtr, this, value);
  }

  public int getTrade() {
    return mtmanapiJNI.ConGroupSec_trade_get(swigCPtr, this);
  }

  public void setExecution(int value) {
    mtmanapiJNI.ConGroupSec_execution_set(swigCPtr, this, value);
  }

  public int getExecution() {
    return mtmanapiJNI.ConGroupSec_execution_get(swigCPtr, this);
  }

  public void setComm_base(double value) {
    mtmanapiJNI.ConGroupSec_comm_base_set(swigCPtr, this, value);
  }

  public double getComm_base() {
    return mtmanapiJNI.ConGroupSec_comm_base_get(swigCPtr, this);
  }

  public void setComm_type(int value) {
    mtmanapiJNI.ConGroupSec_comm_type_set(swigCPtr, this, value);
  }

  public int getComm_type() {
    return mtmanapiJNI.ConGroupSec_comm_type_get(swigCPtr, this);
  }

  public void setComm_lots(int value) {
    mtmanapiJNI.ConGroupSec_comm_lots_set(swigCPtr, this, value);
  }

  public int getComm_lots() {
    return mtmanapiJNI.ConGroupSec_comm_lots_get(swigCPtr, this);
  }

  public void setComm_agent(double value) {
    mtmanapiJNI.ConGroupSec_comm_agent_set(swigCPtr, this, value);
  }

  public double getComm_agent() {
    return mtmanapiJNI.ConGroupSec_comm_agent_get(swigCPtr, this);
  }

  public void setComm_agent_type(int value) {
    mtmanapiJNI.ConGroupSec_comm_agent_type_set(swigCPtr, this, value);
  }

  public int getComm_agent_type() {
    return mtmanapiJNI.ConGroupSec_comm_agent_type_get(swigCPtr, this);
  }

  public void setSpread_diff(int value) {
    mtmanapiJNI.ConGroupSec_spread_diff_set(swigCPtr, this, value);
  }

  public int getSpread_diff() {
    return mtmanapiJNI.ConGroupSec_spread_diff_get(swigCPtr, this);
  }

  public void setLot_min(int value) {
    mtmanapiJNI.ConGroupSec_lot_min_set(swigCPtr, this, value);
  }

  public int getLot_min() {
    return mtmanapiJNI.ConGroupSec_lot_min_get(swigCPtr, this);
  }

  public void setLot_max(int value) {
    mtmanapiJNI.ConGroupSec_lot_max_set(swigCPtr, this, value);
  }

  public int getLot_max() {
    return mtmanapiJNI.ConGroupSec_lot_max_get(swigCPtr, this);
  }

  public void setLot_step(int value) {
    mtmanapiJNI.ConGroupSec_lot_step_set(swigCPtr, this, value);
  }

  public int getLot_step() {
    return mtmanapiJNI.ConGroupSec_lot_step_get(swigCPtr, this);
  }

  public void setIe_deviation(int value) {
    mtmanapiJNI.ConGroupSec_ie_deviation_set(swigCPtr, this, value);
  }

  public int getIe_deviation() {
    return mtmanapiJNI.ConGroupSec_ie_deviation_get(swigCPtr, this);
  }

  public void setConfirmation(int value) {
    mtmanapiJNI.ConGroupSec_confirmation_set(swigCPtr, this, value);
  }

  public int getConfirmation() {
    return mtmanapiJNI.ConGroupSec_confirmation_get(swigCPtr, this);
  }

  public void setTrade_rights(int value) {
    mtmanapiJNI.ConGroupSec_trade_rights_set(swigCPtr, this, value);
  }

  public int getTrade_rights() {
    return mtmanapiJNI.ConGroupSec_trade_rights_get(swigCPtr, this);
  }

  public void setIe_quick_mode(int value) {
    mtmanapiJNI.ConGroupSec_ie_quick_mode_set(swigCPtr, this, value);
  }

  public int getIe_quick_mode() {
    return mtmanapiJNI.ConGroupSec_ie_quick_mode_get(swigCPtr, this);
  }

  public void setAutocloseout_mode(int value) {
    mtmanapiJNI.ConGroupSec_autocloseout_mode_set(swigCPtr, this, value);
  }

  public int getAutocloseout_mode() {
    return mtmanapiJNI.ConGroupSec_autocloseout_mode_get(swigCPtr, this);
  }

  public void setComm_tax(double value) {
    mtmanapiJNI.ConGroupSec_comm_tax_set(swigCPtr, this, value);
  }

  public double getComm_tax() {
    return mtmanapiJNI.ConGroupSec_comm_tax_get(swigCPtr, this);
  }

  public void setComm_agent_lots(int value) {
    mtmanapiJNI.ConGroupSec_comm_agent_lots_set(swigCPtr, this, value);
  }

  public int getComm_agent_lots() {
    return mtmanapiJNI.ConGroupSec_comm_agent_lots_get(swigCPtr, this);
  }

  public void setFreemargin_mode(int value) {
    mtmanapiJNI.ConGroupSec_freemargin_mode_set(swigCPtr, this, value);
  }

  public int getFreemargin_mode() {
    return mtmanapiJNI.ConGroupSec_freemargin_mode_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGroupSec_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConGroupSec_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConGroupSec() {
    this(mtmanapiJNI.new_ConGroupSec(), true);
  }

}
