/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGroup(String value) {
    mtmanapiJNI.ConGroup_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mtmanapiJNI.ConGroup_group_get(swigCPtr, this);
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConGroup_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConGroup_enable_get(swigCPtr, this);
  }

  public void setTimeout(int value) {
    mtmanapiJNI.ConGroup_timeout_set(swigCPtr, this, value);
  }

  public int getTimeout() {
    return mtmanapiJNI.ConGroup_timeout_get(swigCPtr, this);
  }

  public void setOtp_mode(int value) {
    mtmanapiJNI.ConGroup_otp_mode_set(swigCPtr, this, value);
  }

  public int getOtp_mode() {
    return mtmanapiJNI.ConGroup_otp_mode_get(swigCPtr, this);
  }

  public void setCompany(String value) {
    mtmanapiJNI.ConGroup_company_set(swigCPtr, this, value);
  }

  public String getCompany() {
    return mtmanapiJNI.ConGroup_company_get(swigCPtr, this);
  }

  public void setSignature(String value) {
    mtmanapiJNI.ConGroup_signature_set(swigCPtr, this, value);
  }

  public String getSignature() {
    return mtmanapiJNI.ConGroup_signature_get(swigCPtr, this);
  }

  public void setSupport_page(String value) {
    mtmanapiJNI.ConGroup_support_page_set(swigCPtr, this, value);
  }

  public String getSupport_page() {
    return mtmanapiJNI.ConGroup_support_page_get(swigCPtr, this);
  }

  public void setSmtp_server(String value) {
    mtmanapiJNI.ConGroup_smtp_server_set(swigCPtr, this, value);
  }

  public String getSmtp_server() {
    return mtmanapiJNI.ConGroup_smtp_server_get(swigCPtr, this);
  }

  public void setSmtp_login(String value) {
    mtmanapiJNI.ConGroup_smtp_login_set(swigCPtr, this, value);
  }

  public String getSmtp_login() {
    return mtmanapiJNI.ConGroup_smtp_login_get(swigCPtr, this);
  }

  public void setSmtp_password(String value) {
    mtmanapiJNI.ConGroup_smtp_password_set(swigCPtr, this, value);
  }

  public String getSmtp_password() {
    return mtmanapiJNI.ConGroup_smtp_password_get(swigCPtr, this);
  }

  public void setSupport_email(String value) {
    mtmanapiJNI.ConGroup_support_email_set(swigCPtr, this, value);
  }

  public String getSupport_email() {
    return mtmanapiJNI.ConGroup_support_email_get(swigCPtr, this);
  }

  public void setTemplates(String value) {
    mtmanapiJNI.ConGroup_templates_set(swigCPtr, this, value);
  }

  public String getTemplates() {
    return mtmanapiJNI.ConGroup_templates_get(swigCPtr, this);
  }

  public void setCopies(int value) {
    mtmanapiJNI.ConGroup_copies_set(swigCPtr, this, value);
  }

  public int getCopies() {
    return mtmanapiJNI.ConGroup_copies_get(swigCPtr, this);
  }

  public void setReports(int value) {
    mtmanapiJNI.ConGroup_reports_set(swigCPtr, this, value);
  }

  public int getReports() {
    return mtmanapiJNI.ConGroup_reports_get(swigCPtr, this);
  }

  public void setDefault_leverage(int value) {
    mtmanapiJNI.ConGroup_default_leverage_set(swigCPtr, this, value);
  }

  public int getDefault_leverage() {
    return mtmanapiJNI.ConGroup_default_leverage_get(swigCPtr, this);
  }

  public void setDefault_deposit(double value) {
    mtmanapiJNI.ConGroup_default_deposit_set(swigCPtr, this, value);
  }

  public double getDefault_deposit() {
    return mtmanapiJNI.ConGroup_default_deposit_get(swigCPtr, this);
  }

  public void setMaxsecurities(int value) {
    mtmanapiJNI.ConGroup_maxsecurities_set(swigCPtr, this, value);
  }

  public int getMaxsecurities() {
    return mtmanapiJNI.ConGroup_maxsecurities_get(swigCPtr, this);
  }

  public void setSecgroups(ConGroupSec value) {
    mtmanapiJNI.ConGroup_secgroups_set(swigCPtr, this, ConGroupSec.getCPtr(value), value);
  }

  public ConGroupSec getSecgroups() {
    long cPtr = mtmanapiJNI.ConGroup_secgroups_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConGroupSec(cPtr, false);
  }

  public void setSecmargins(ConGroupMargin value) {
    mtmanapiJNI.ConGroup_secmargins_set(swigCPtr, this, ConGroupMargin.getCPtr(value), value);
  }

  public ConGroupMargin getSecmargins() {
    long cPtr = mtmanapiJNI.ConGroup_secmargins_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConGroupMargin(cPtr, false);
  }

  public void setSecmargins_total(int value) {
    mtmanapiJNI.ConGroup_secmargins_total_set(swigCPtr, this, value);
  }

  public int getSecmargins_total() {
    return mtmanapiJNI.ConGroup_secmargins_total_get(swigCPtr, this);
  }

  public void setCurrency(String value) {
    mtmanapiJNI.ConGroup_currency_set(swigCPtr, this, value);
  }

  public String getCurrency() {
    return mtmanapiJNI.ConGroup_currency_get(swigCPtr, this);
  }

  public void setCredit(double value) {
    mtmanapiJNI.ConGroup_credit_set(swigCPtr, this, value);
  }

  public double getCredit() {
    return mtmanapiJNI.ConGroup_credit_get(swigCPtr, this);
  }

  public void setMargin_call(int value) {
    mtmanapiJNI.ConGroup_margin_call_set(swigCPtr, this, value);
  }

  public int getMargin_call() {
    return mtmanapiJNI.ConGroup_margin_call_get(swigCPtr, this);
  }

  public void setMargin_mode(int value) {
    mtmanapiJNI.ConGroup_margin_mode_set(swigCPtr, this, value);
  }

  public int getMargin_mode() {
    return mtmanapiJNI.ConGroup_margin_mode_get(swigCPtr, this);
  }

  public void setMargin_stopout(int value) {
    mtmanapiJNI.ConGroup_margin_stopout_set(swigCPtr, this, value);
  }

  public int getMargin_stopout() {
    return mtmanapiJNI.ConGroup_margin_stopout_get(swigCPtr, this);
  }

  public void setInterestrate(double value) {
    mtmanapiJNI.ConGroup_interestrate_set(swigCPtr, this, value);
  }

  public double getInterestrate() {
    return mtmanapiJNI.ConGroup_interestrate_get(swigCPtr, this);
  }

  public void setUse_swap(int value) {
    mtmanapiJNI.ConGroup_use_swap_set(swigCPtr, this, value);
  }

  public int getUse_swap() {
    return mtmanapiJNI.ConGroup_use_swap_get(swigCPtr, this);
  }

  public void setNews(int value) {
    mtmanapiJNI.ConGroup_news_set(swigCPtr, this, value);
  }

  public int getNews() {
    return mtmanapiJNI.ConGroup_news_get(swigCPtr, this);
  }

  public void setRights(int value) {
    mtmanapiJNI.ConGroup_rights_set(swigCPtr, this, value);
  }

  public int getRights() {
    return mtmanapiJNI.ConGroup_rights_get(swigCPtr, this);
  }

  public void setCheck_ie_prices(int value) {
    mtmanapiJNI.ConGroup_check_ie_prices_set(swigCPtr, this, value);
  }

  public int getCheck_ie_prices() {
    return mtmanapiJNI.ConGroup_check_ie_prices_get(swigCPtr, this);
  }

  public void setMaxpositions(int value) {
    mtmanapiJNI.ConGroup_maxpositions_set(swigCPtr, this, value);
  }

  public int getMaxpositions() {
    return mtmanapiJNI.ConGroup_maxpositions_get(swigCPtr, this);
  }

  public void setClose_reopen(int value) {
    mtmanapiJNI.ConGroup_close_reopen_set(swigCPtr, this, value);
  }

  public int getClose_reopen() {
    return mtmanapiJNI.ConGroup_close_reopen_get(swigCPtr, this);
  }

  public void setHedge_prohibited(int value) {
    mtmanapiJNI.ConGroup_hedge_prohibited_set(swigCPtr, this, value);
  }

  public int getHedge_prohibited() {
    return mtmanapiJNI.ConGroup_hedge_prohibited_get(swigCPtr, this);
  }

  public void setClose_fifo(int value) {
    mtmanapiJNI.ConGroup_close_fifo_set(swigCPtr, this, value);
  }

  public int getClose_fifo() {
    return mtmanapiJNI.ConGroup_close_fifo_get(swigCPtr, this);
  }

  public void setHedge_largeleg(int value) {
    mtmanapiJNI.ConGroup_hedge_largeleg_set(swigCPtr, this, value);
  }

  public int getHedge_largeleg() {
    return mtmanapiJNI.ConGroup_hedge_largeleg_get(swigCPtr, this);
  }

  public void setUnused_rights(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGroup_unused_rights_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getUnused_rights() {
    long cPtr = mtmanapiJNI.ConGroup_unused_rights_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setSecurities_hash(String value) {
    mtmanapiJNI.ConGroup_securities_hash_set(swigCPtr, this, value);
  }

  public String getSecurities_hash() {
    return mtmanapiJNI.ConGroup_securities_hash_get(swigCPtr, this);
  }

  public void setMargin_type(int value) {
    mtmanapiJNI.ConGroup_margin_type_set(swigCPtr, this, value);
  }

  public int getMargin_type() {
    return mtmanapiJNI.ConGroup_margin_type_get(swigCPtr, this);
  }

  public void setArchive_period(int value) {
    mtmanapiJNI.ConGroup_archive_period_set(swigCPtr, this, value);
  }

  public int getArchive_period() {
    return mtmanapiJNI.ConGroup_archive_period_get(swigCPtr, this);
  }

  public void setArchive_max_balance(int value) {
    mtmanapiJNI.ConGroup_archive_max_balance_set(swigCPtr, this, value);
  }

  public int getArchive_max_balance() {
    return mtmanapiJNI.ConGroup_archive_max_balance_get(swigCPtr, this);
  }

  public void setStopout_skip_hedged(int value) {
    mtmanapiJNI.ConGroup_stopout_skip_hedged_set(swigCPtr, this, value);
  }

  public int getStopout_skip_hedged() {
    return mtmanapiJNI.ConGroup_stopout_skip_hedged_get(swigCPtr, this);
  }

  public void setArchive_pending_period(int value) {
    mtmanapiJNI.ConGroup_archive_pending_period_set(swigCPtr, this, value);
  }

  public int getArchive_pending_period() {
    return mtmanapiJNI.ConGroup_archive_pending_period_get(swigCPtr, this);
  }

  public void setNews_languages(SWIGTYPE_p_unsigned_int value) {
    mtmanapiJNI.ConGroup_news_languages_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getNews_languages() {
    long cPtr = mtmanapiJNI.ConGroup_news_languages_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setNews_languages_total(long value) {
    mtmanapiJNI.ConGroup_news_languages_total_set(swigCPtr, this, value);
  }

  public long getNews_languages_total() {
    return mtmanapiJNI.ConGroup_news_languages_total_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGroup_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConGroup_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConGroup() {
    this(mtmanapiJNI.new_ConGroup(), true);
  }

}
