/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConGatewayMarkup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConGatewayMarkup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConGatewayMarkup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConGatewayMarkup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConGatewayMarkup_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConGatewayMarkup_enable_get(swigCPtr, this);
  }

  public void setSource(String value) {
    mtmanapiJNI.ConGatewayMarkup_source_set(swigCPtr, this, value);
  }

  public String getSource() {
    return mtmanapiJNI.ConGatewayMarkup_source_get(swigCPtr, this);
  }

  public void setSymbol(String value) {
    mtmanapiJNI.ConGatewayMarkup_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.ConGatewayMarkup_symbol_get(swigCPtr, this);
  }

  public void setAccount_name(String value) {
    mtmanapiJNI.ConGatewayMarkup_account_name_set(swigCPtr, this, value);
  }

  public String getAccount_name() {
    return mtmanapiJNI.ConGatewayMarkup_account_name_get(swigCPtr, this);
  }

  public void setAccount_id(int value) {
    mtmanapiJNI.ConGatewayMarkup_account_id_set(swigCPtr, this, value);
  }

  public int getAccount_id() {
    return mtmanapiJNI.ConGatewayMarkup_account_id_get(swigCPtr, this);
  }

  public void setBid_markup(int value) {
    mtmanapiJNI.ConGatewayMarkup_bid_markup_set(swigCPtr, this, value);
  }

  public int getBid_markup() {
    return mtmanapiJNI.ConGatewayMarkup_bid_markup_get(swigCPtr, this);
  }

  public void setAsk_markup(int value) {
    mtmanapiJNI.ConGatewayMarkup_ask_markup_set(swigCPtr, this, value);
  }

  public int getAsk_markup() {
    return mtmanapiJNI.ConGatewayMarkup_ask_markup_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGatewayMarkup_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConGatewayMarkup_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConGatewayMarkup() {
    this(mtmanapiJNI.new_ConGatewayMarkup(), true);
  }

}
