/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConGatewayAccount {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConGatewayAccount(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConGatewayAccount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConGatewayAccount(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConGatewayAccount_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConGatewayAccount_enable_get(swigCPtr, this);
  }

  public void setName(String value) {
    mtmanapiJNI.ConGatewayAccount_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.ConGatewayAccount_name_get(swigCPtr, this);
  }

  public void setId(int value) {
    mtmanapiJNI.ConGatewayAccount_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return mtmanapiJNI.ConGatewayAccount_id_get(swigCPtr, this);
  }

  public void setType(int value) {
    mtmanapiJNI.ConGatewayAccount_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mtmanapiJNI.ConGatewayAccount_type_get(swigCPtr, this);
  }

  public void setLogin(int value) {
    mtmanapiJNI.ConGatewayAccount_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.ConGatewayAccount_login_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    mtmanapiJNI.ConGatewayAccount_address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return mtmanapiJNI.ConGatewayAccount_address_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    mtmanapiJNI.ConGatewayAccount_password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return mtmanapiJNI.ConGatewayAccount_password_get(swigCPtr, this);
  }

  public void setNotify_logins(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGatewayAccount_notify_logins_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getNotify_logins() {
    long cPtr = mtmanapiJNI.ConGatewayAccount_notify_logins_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setFlags(int value) {
    mtmanapiJNI.ConGatewayAccount_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return mtmanapiJNI.ConGatewayAccount_flags_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGatewayAccount_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConGatewayAccount_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConGatewayAccount() {
    this(mtmanapiJNI.new_ConGatewayAccount(), true);
  }

}
