/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConGatewayRule {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConGatewayRule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConGatewayRule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConGatewayRule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConGatewayRule_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConGatewayRule_enable_get(swigCPtr, this);
  }

  public void setName(String value) {
    mtmanapiJNI.ConGatewayRule_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.ConGatewayRule_name_get(swigCPtr, this);
  }

  public void setRequest_symbol(String value) {
    mtmanapiJNI.ConGatewayRule_request_symbol_set(swigCPtr, this, value);
  }

  public String getRequest_symbol() {
    return mtmanapiJNI.ConGatewayRule_request_symbol_get(swigCPtr, this);
  }

  public void setRequest_group(String value) {
    mtmanapiJNI.ConGatewayRule_request_group_set(swigCPtr, this, value);
  }

  public String getRequest_group() {
    return mtmanapiJNI.ConGatewayRule_request_group_get(swigCPtr, this);
  }

  public void setRequest_reserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGatewayRule_request_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getRequest_reserved() {
    long cPtr = mtmanapiJNI.ConGatewayRule_request_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setExe_account_name(String value) {
    mtmanapiJNI.ConGatewayRule_exe_account_name_set(swigCPtr, this, value);
  }

  public String getExe_account_name() {
    return mtmanapiJNI.ConGatewayRule_exe_account_name_get(swigCPtr, this);
  }

  public void setExe_account_id(int value) {
    mtmanapiJNI.ConGatewayRule_exe_account_id_set(swigCPtr, this, value);
  }

  public int getExe_account_id() {
    return mtmanapiJNI.ConGatewayRule_exe_account_id_get(swigCPtr, this);
  }

  public void setExe_max_deviation(int value) {
    mtmanapiJNI.ConGatewayRule_exe_max_deviation_set(swigCPtr, this, value);
  }

  public int getExe_max_deviation() {
    return mtmanapiJNI.ConGatewayRule_exe_max_deviation_get(swigCPtr, this);
  }

  public void setExe_max_profit_slippage(int value) {
    mtmanapiJNI.ConGatewayRule_exe_max_profit_slippage_set(swigCPtr, this, value);
  }

  public int getExe_max_profit_slippage() {
    return mtmanapiJNI.ConGatewayRule_exe_max_profit_slippage_get(swigCPtr, this);
  }

  public void setExe_max_profit_slippage_lots(int value) {
    mtmanapiJNI.ConGatewayRule_exe_max_profit_slippage_lots_set(swigCPtr, this, value);
  }

  public int getExe_max_profit_slippage_lots() {
    return mtmanapiJNI.ConGatewayRule_exe_max_profit_slippage_lots_get(swigCPtr, this);
  }

  public void setExe_max_losing_slippage(int value) {
    mtmanapiJNI.ConGatewayRule_exe_max_losing_slippage_set(swigCPtr, this, value);
  }

  public int getExe_max_losing_slippage() {
    return mtmanapiJNI.ConGatewayRule_exe_max_losing_slippage_get(swigCPtr, this);
  }

  public void setExe_max_losing_slippage_lots(int value) {
    mtmanapiJNI.ConGatewayRule_exe_max_losing_slippage_lots_set(swigCPtr, this, value);
  }

  public int getExe_max_losing_slippage_lots() {
    return mtmanapiJNI.ConGatewayRule_exe_max_losing_slippage_lots_get(swigCPtr, this);
  }

  public void setExe_account_pos(int value) {
    mtmanapiJNI.ConGatewayRule_exe_account_pos_set(swigCPtr, this, value);
  }

  public int getExe_account_pos() {
    return mtmanapiJNI.ConGatewayRule_exe_account_pos_get(swigCPtr, this);
  }

  public void setExe_volume_percent(int value) {
    mtmanapiJNI.ConGatewayRule_exe_volume_percent_set(swigCPtr, this, value);
  }

  public int getExe_volume_percent() {
    return mtmanapiJNI.ConGatewayRule_exe_volume_percent_get(swigCPtr, this);
  }

  public void setExe_reserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGatewayRule_exe_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getExe_reserved() {
    long cPtr = mtmanapiJNI.ConGatewayRule_exe_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConGatewayRule() {
    this(mtmanapiJNI.new_ConGatewayRule(), true);
  }

}
