/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConHoliday {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConHoliday(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConHoliday obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConHoliday(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setYear(int value) {
    mtmanapiJNI.ConHoliday_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return mtmanapiJNI.ConHoliday_year_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    mtmanapiJNI.ConHoliday_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return mtmanapiJNI.ConHoliday_month_get(swigCPtr, this);
  }

  public void setDay(int value) {
    mtmanapiJNI.ConHoliday_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return mtmanapiJNI.ConHoliday_day_get(swigCPtr, this);
  }

  public void setFrom(int value) {
    mtmanapiJNI.ConHoliday_from_set(swigCPtr, this, value);
  }

  public int getFrom() {
    return mtmanapiJNI.ConHoliday_from_get(swigCPtr, this);
  }

  public void setTo(int value) {
    mtmanapiJNI.ConHoliday_to_set(swigCPtr, this, value);
  }

  public int getTo() {
    return mtmanapiJNI.ConHoliday_to_get(swigCPtr, this);
  }

  public void setSymbol(String value) {
    mtmanapiJNI.ConHoliday_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.ConHoliday_symbol_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    mtmanapiJNI.ConHoliday_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return mtmanapiJNI.ConHoliday_description_get(swigCPtr, this);
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConHoliday_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConHoliday_enable_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConHoliday_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConHoliday_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNext(ConHoliday value) {
    mtmanapiJNI.ConHoliday_next_set(swigCPtr, this, ConHoliday.getCPtr(value), value);
  }

  public ConHoliday getNext() {
    long cPtr = mtmanapiJNI.ConHoliday_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConHoliday(cPtr, false);
  }

  public ConHoliday() {
    this(mtmanapiJNI.new_ConHoliday(), true);
  }

}
