/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConLiveUpdate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConLiveUpdate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConLiveUpdate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConLiveUpdate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCompany(String value) {
    mtmanapiJNI.ConLiveUpdate_company_set(swigCPtr, this, value);
  }

  public String getCompany() {
    return mtmanapiJNI.ConLiveUpdate_company_get(swigCPtr, this);
  }

  public void setPath(String value) {
    mtmanapiJNI.ConLiveUpdate_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return mtmanapiJNI.ConLiveUpdate_path_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    mtmanapiJNI.ConLiveUpdate_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return mtmanapiJNI.ConLiveUpdate_version_get(swigCPtr, this);
  }

  public void setBuild(int value) {
    mtmanapiJNI.ConLiveUpdate_build_set(swigCPtr, this, value);
  }

  public int getBuild() {
    return mtmanapiJNI.ConLiveUpdate_build_get(swigCPtr, this);
  }

  public void setMaxconnect(int value) {
    mtmanapiJNI.ConLiveUpdate_maxconnect_set(swigCPtr, this, value);
  }

  public int getMaxconnect() {
    return mtmanapiJNI.ConLiveUpdate_maxconnect_get(swigCPtr, this);
  }

  public void setConnections(int value) {
    mtmanapiJNI.ConLiveUpdate_connections_set(swigCPtr, this, value);
  }

  public int getConnections() {
    return mtmanapiJNI.ConLiveUpdate_connections_get(swigCPtr, this);
  }

  public void setType(int value) {
    mtmanapiJNI.ConLiveUpdate_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mtmanapiJNI.ConLiveUpdate_type_get(swigCPtr, this);
  }

  public void setEnable(int value) {
    mtmanapiJNI.ConLiveUpdate_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.ConLiveUpdate_enable_get(swigCPtr, this);
  }

  public void setTotalfiles(int value) {
    mtmanapiJNI.ConLiveUpdate_totalfiles_set(swigCPtr, this, value);
  }

  public int getTotalfiles() {
    return mtmanapiJNI.ConLiveUpdate_totalfiles_get(swigCPtr, this);
  }

  public void setFiles(LiveInfoFile value) {
    mtmanapiJNI.ConLiveUpdate_files_set(swigCPtr, this, LiveInfoFile.getCPtr(value), value);
  }

  public LiveInfoFile getFiles() {
    long cPtr = mtmanapiJNI.ConLiveUpdate_files_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LiveInfoFile(cPtr, false);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConLiveUpdate_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConLiveUpdate_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNext(ConLiveUpdate value) {
    mtmanapiJNI.ConLiveUpdate_next_set(swigCPtr, this, ConLiveUpdate.getCPtr(value), value);
  }

  public ConLiveUpdate getNext() {
    long cPtr = mtmanapiJNI.ConLiveUpdate_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConLiveUpdate(cPtr, false);
  }

  public ConLiveUpdate() {
    this(mtmanapiJNI.new_ConLiveUpdate(), true);
  }

}
