/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogin(int value) {
    mtmanapiJNI.ConManager_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.ConManager_login_get(swigCPtr, this);
  }

  public void setManager(int value) {
    mtmanapiJNI.ConManager_manager_set(swigCPtr, this, value);
  }

  public int getManager() {
    return mtmanapiJNI.ConManager_manager_get(swigCPtr, this);
  }

  public void setMoney(int value) {
    mtmanapiJNI.ConManager_money_set(swigCPtr, this, value);
  }

  public int getMoney() {
    return mtmanapiJNI.ConManager_money_get(swigCPtr, this);
  }

  public void setOnline(int value) {
    mtmanapiJNI.ConManager_online_set(swigCPtr, this, value);
  }

  public int getOnline() {
    return mtmanapiJNI.ConManager_online_get(swigCPtr, this);
  }

  public void setRiskman(int value) {
    mtmanapiJNI.ConManager_riskman_set(swigCPtr, this, value);
  }

  public int getRiskman() {
    return mtmanapiJNI.ConManager_riskman_get(swigCPtr, this);
  }

  public void setBroker(int value) {
    mtmanapiJNI.ConManager_broker_set(swigCPtr, this, value);
  }

  public int getBroker() {
    return mtmanapiJNI.ConManager_broker_get(swigCPtr, this);
  }

  public void setAdmin(int value) {
    mtmanapiJNI.ConManager_admin_set(swigCPtr, this, value);
  }

  public int getAdmin() {
    return mtmanapiJNI.ConManager_admin_get(swigCPtr, this);
  }

  public void setLogs(int value) {
    mtmanapiJNI.ConManager_logs_set(swigCPtr, this, value);
  }

  public int getLogs() {
    return mtmanapiJNI.ConManager_logs_get(swigCPtr, this);
  }

  public void setReports(int value) {
    mtmanapiJNI.ConManager_reports_set(swigCPtr, this, value);
  }

  public int getReports() {
    return mtmanapiJNI.ConManager_reports_get(swigCPtr, this);
  }

  public void setTrades(int value) {
    mtmanapiJNI.ConManager_trades_set(swigCPtr, this, value);
  }

  public int getTrades() {
    return mtmanapiJNI.ConManager_trades_get(swigCPtr, this);
  }

  public void setMarket_watch(int value) {
    mtmanapiJNI.ConManager_market_watch_set(swigCPtr, this, value);
  }

  public int getMarket_watch() {
    return mtmanapiJNI.ConManager_market_watch_get(swigCPtr, this);
  }

  public void setEmail(int value) {
    mtmanapiJNI.ConManager_email_set(swigCPtr, this, value);
  }

  public int getEmail() {
    return mtmanapiJNI.ConManager_email_get(swigCPtr, this);
  }

  public void setUser_details(int value) {
    mtmanapiJNI.ConManager_user_details_set(swigCPtr, this, value);
  }

  public int getUser_details() {
    return mtmanapiJNI.ConManager_user_details_get(swigCPtr, this);
  }

  public void setSee_trades(int value) {
    mtmanapiJNI.ConManager_see_trades_set(swigCPtr, this, value);
  }

  public int getSee_trades() {
    return mtmanapiJNI.ConManager_see_trades_get(swigCPtr, this);
  }

  public void setNews(int value) {
    mtmanapiJNI.ConManager_news_set(swigCPtr, this, value);
  }

  public int getNews() {
    return mtmanapiJNI.ConManager_news_get(swigCPtr, this);
  }

  public void setPlugins(int value) {
    mtmanapiJNI.ConManager_plugins_set(swigCPtr, this, value);
  }

  public int getPlugins() {
    return mtmanapiJNI.ConManager_plugins_get(swigCPtr, this);
  }

  public void setServer_reports(int value) {
    mtmanapiJNI.ConManager_server_reports_set(swigCPtr, this, value);
  }

  public int getServer_reports() {
    return mtmanapiJNI.ConManager_server_reports_get(swigCPtr, this);
  }

  public void setTechsupport(int value) {
    mtmanapiJNI.ConManager_techsupport_set(swigCPtr, this, value);
  }

  public int getTechsupport() {
    return mtmanapiJNI.ConManager_techsupport_get(swigCPtr, this);
  }

  public void setMarket(int value) {
    mtmanapiJNI.ConManager_market_set(swigCPtr, this, value);
  }

  public int getMarket() {
    return mtmanapiJNI.ConManager_market_get(swigCPtr, this);
  }

  public void setNotifications(int value) {
    mtmanapiJNI.ConManager_notifications_set(swigCPtr, this, value);
  }

  public int getNotifications() {
    return mtmanapiJNI.ConManager_notifications_get(swigCPtr, this);
  }

  public void setUnused(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConManager_unused_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getUnused() {
    long cPtr = mtmanapiJNI.ConManager_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setIpfilter(int value) {
    mtmanapiJNI.ConManager_ipfilter_set(swigCPtr, this, value);
  }

  public int getIpfilter() {
    return mtmanapiJNI.ConManager_ipfilter_get(swigCPtr, this);
  }

  public void setIp_from(long value) {
    mtmanapiJNI.ConManager_ip_from_set(swigCPtr, this, value);
  }

  public long getIp_from() {
    return mtmanapiJNI.ConManager_ip_from_get(swigCPtr, this);
  }

  public void setIp_to(long value) {
    mtmanapiJNI.ConManager_ip_to_set(swigCPtr, this, value);
  }

  public long getIp_to() {
    return mtmanapiJNI.ConManager_ip_to_get(swigCPtr, this);
  }

  public void setMailbox(String value) {
    mtmanapiJNI.ConManager_mailbox_set(swigCPtr, this, value);
  }

  public String getMailbox() {
    return mtmanapiJNI.ConManager_mailbox_get(swigCPtr, this);
  }

  public void setGroups(String value) {
    mtmanapiJNI.ConManager_groups_set(swigCPtr, this, value);
  }

  public String getGroups() {
    return mtmanapiJNI.ConManager_groups_get(swigCPtr, this);
  }

  public void setSecgroups(ConManagerSec value) {
    mtmanapiJNI.ConManager_secgroups_set(swigCPtr, this, ConManagerSec.getCPtr(value), value);
  }

  public ConManagerSec getSecgroups() {
    long cPtr = mtmanapiJNI.ConManager_secgroups_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConManagerSec(cPtr, false);
  }

  public void setExp_time(long value) {
    mtmanapiJNI.ConManager_exp_time_set(swigCPtr, this, value);
  }

  public long getExp_time() {
    return mtmanapiJNI.ConManager_exp_time_get(swigCPtr, this);
  }

  public void setName(String value) {
    mtmanapiJNI.ConManager_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.ConManager_name_get(swigCPtr, this);
  }

  public void setInfo_depth(int value) {
    mtmanapiJNI.ConManager_info_depth_set(swigCPtr, this, value);
  }

  public int getInfo_depth() {
    return mtmanapiJNI.ConManager_info_depth_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConManager_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConManager_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConManager() {
    this(mtmanapiJNI.new_ConManager(), true);
  }

}
