/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConPlugin {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConPlugin(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConPlugin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConPlugin(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFile(String value) {
    mtmanapiJNI.ConPlugin_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return mtmanapiJNI.ConPlugin_file_get(swigCPtr, this);
  }

  public void setInfo(PluginInfo value) {
    mtmanapiJNI.ConPlugin_info_set(swigCPtr, this, PluginInfo.getCPtr(value), value);
  }

  public PluginInfo getInfo() {
    long cPtr = mtmanapiJNI.ConPlugin_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PluginInfo(cPtr, false);
  }

  public void setEnabled(int value) {
    mtmanapiJNI.ConPlugin_enabled_set(swigCPtr, this, value);
  }

  public int getEnabled() {
    return mtmanapiJNI.ConPlugin_enabled_get(swigCPtr, this);
  }

  public void setConfigurable(int value) {
    mtmanapiJNI.ConPlugin_configurable_set(swigCPtr, this, value);
  }

  public int getConfigurable() {
    return mtmanapiJNI.ConPlugin_configurable_get(swigCPtr, this);
  }

  public void setManager_access(int value) {
    mtmanapiJNI.ConPlugin_manager_access_set(swigCPtr, this, value);
  }

  public int getManager_access() {
    return mtmanapiJNI.ConPlugin_manager_access_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConPlugin_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConPlugin_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConPlugin() {
    this(mtmanapiJNI.new_ConPlugin(), true);
  }

}
