/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConPluginParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConPluginParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConPluginParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConPluginParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPlugin(ConPlugin value) {
    mtmanapiJNI.ConPluginParam_plugin_set(swigCPtr, this, ConPlugin.getCPtr(value), value);
  }

  public ConPlugin getPlugin() {
    long cPtr = mtmanapiJNI.ConPluginParam_plugin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConPlugin(cPtr, false);
  }

  public void setParams(PluginCfg value) {
    mtmanapiJNI.ConPluginParam_params_set(swigCPtr, this, PluginCfg.getCPtr(value), value);
  }

  public PluginCfg getParams() {
    long cPtr = mtmanapiJNI.ConPluginParam_params_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PluginCfg(cPtr, false);
  }

  public void setTotal(int value) {
    mtmanapiJNI.ConPluginParam_total_set(swigCPtr, this, value);
  }

  public int getTotal() {
    return mtmanapiJNI.ConPluginParam_total_get(swigCPtr, this);
  }

  public ConPluginParam() {
    this(mtmanapiJNI.new_ConPluginParam(), true);
  }

}
