/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class ConSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOpen_hour(short value) {
    mtmanapiJNI.ConSession_open_hour_set(swigCPtr, this, value);
  }

  public short getOpen_hour() {
    return mtmanapiJNI.ConSession_open_hour_get(swigCPtr, this);
  }

  public void setOpen_min(short value) {
    mtmanapiJNI.ConSession_open_min_set(swigCPtr, this, value);
  }

  public short getOpen_min() {
    return mtmanapiJNI.ConSession_open_min_get(swigCPtr, this);
  }

  public void setClose_hour(short value) {
    mtmanapiJNI.ConSession_close_hour_set(swigCPtr, this, value);
  }

  public short getClose_hour() {
    return mtmanapiJNI.ConSession_close_hour_get(swigCPtr, this);
  }

  public void setClose_min(short value) {
    mtmanapiJNI.ConSession_close_min_set(swigCPtr, this, value);
  }

  public short getClose_min() {
    return mtmanapiJNI.ConSession_close_min_get(swigCPtr, this);
  }

  public void setOpen(int value) {
    mtmanapiJNI.ConSession_open_set(swigCPtr, this, value);
  }

  public int getOpen() {
    return mtmanapiJNI.ConSession_open_get(swigCPtr, this);
  }

  public void setClose(int value) {
    mtmanapiJNI.ConSession_close_set(swigCPtr, this, value);
  }

  public int getClose() {
    return mtmanapiJNI.ConSession_close_get(swigCPtr, this);
  }

  public void setAlign(SWIGTYPE_p_short value) {
    mtmanapiJNI.ConSession_align_set(swigCPtr, this, SWIGTYPE_p_short.getCPtr(value));
  }

  public SWIGTYPE_p_short getAlign() {
    long cPtr = mtmanapiJNI.ConSession_align_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public ConSession() {
    this(mtmanapiJNI.new_ConSession(), true);
  }

}
