/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class DailyReport {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DailyReport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DailyReport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_DailyReport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogin(int value) {
    mtmanapiJNI.DailyReport_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.DailyReport_login_get(swigCPtr, this);
  }

  public void setCtm(int value) {
    mtmanapiJNI.DailyReport_ctm_set(swigCPtr, this, value);
  }

  public int getCtm() {
    return mtmanapiJNI.DailyReport_ctm_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    mtmanapiJNI.DailyReport_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mtmanapiJNI.DailyReport_group_get(swigCPtr, this);
  }

  public void setBank(String value) {
    mtmanapiJNI.DailyReport_bank_set(swigCPtr, this, value);
  }

  public String getBank() {
    return mtmanapiJNI.DailyReport_bank_get(swigCPtr, this);
  }

  public void setBalance_prev(double value) {
    mtmanapiJNI.DailyReport_balance_prev_set(swigCPtr, this, value);
  }

  public double getBalance_prev() {
    return mtmanapiJNI.DailyReport_balance_prev_get(swigCPtr, this);
  }

  public void setBalance(double value) {
    mtmanapiJNI.DailyReport_balance_set(swigCPtr, this, value);
  }

  public double getBalance() {
    return mtmanapiJNI.DailyReport_balance_get(swigCPtr, this);
  }

  public void setDeposit(double value) {
    mtmanapiJNI.DailyReport_deposit_set(swigCPtr, this, value);
  }

  public double getDeposit() {
    return mtmanapiJNI.DailyReport_deposit_get(swigCPtr, this);
  }

  public void setCredit(double value) {
    mtmanapiJNI.DailyReport_credit_set(swigCPtr, this, value);
  }

  public double getCredit() {
    return mtmanapiJNI.DailyReport_credit_get(swigCPtr, this);
  }

  public void setProfit_closed(double value) {
    mtmanapiJNI.DailyReport_profit_closed_set(swigCPtr, this, value);
  }

  public double getProfit_closed() {
    return mtmanapiJNI.DailyReport_profit_closed_get(swigCPtr, this);
  }

  public void setProfit(double value) {
    mtmanapiJNI.DailyReport_profit_set(swigCPtr, this, value);
  }

  public double getProfit() {
    return mtmanapiJNI.DailyReport_profit_get(swigCPtr, this);
  }

  public void setEquity(double value) {
    mtmanapiJNI.DailyReport_equity_set(swigCPtr, this, value);
  }

  public double getEquity() {
    return mtmanapiJNI.DailyReport_equity_get(swigCPtr, this);
  }

  public void setMargin(double value) {
    mtmanapiJNI.DailyReport_margin_set(swigCPtr, this, value);
  }

  public double getMargin() {
    return mtmanapiJNI.DailyReport_margin_get(swigCPtr, this);
  }

  public void setMargin_free(double value) {
    mtmanapiJNI.DailyReport_margin_free_set(swigCPtr, this, value);
  }

  public double getMargin_free() {
    return mtmanapiJNI.DailyReport_margin_free_get(swigCPtr, this);
  }

  public void setNext(int value) {
    mtmanapiJNI.DailyReport_next_set(swigCPtr, this, value);
  }

  public int getNext() {
    return mtmanapiJNI.DailyReport_next_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.DailyReport_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.DailyReport_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public DailyReport() {
    this(mtmanapiJNI.new_DailyReport(), true);
  }

}
