/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public final class EnGatewayAccountFlags {
  public final static EnGatewayAccountFlags GATEWAY_FLAG_NONE = new EnGatewayAccountFlags("GATEWAY_FLAG_NONE", mtmanapiJNI.GATEWAY_FLAG_NONE_get());
  public final static EnGatewayAccountFlags GATEWAY_FLAG_QUOTES = new EnGatewayAccountFlags("GATEWAY_FLAG_QUOTES", mtmanapiJNI.GATEWAY_FLAG_QUOTES_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EnGatewayAccountFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EnGatewayAccountFlags.class + " with value " + swigValue);
  }

  private EnGatewayAccountFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EnGatewayAccountFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EnGatewayAccountFlags(String swigName, EnGatewayAccountFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EnGatewayAccountFlags[] swigValues = { GATEWAY_FLAG_NONE, GATEWAY_FLAG_QUOTES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

