/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class FeedDescription {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FeedDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FeedDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_FeedDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(int value) {
    mtmanapiJNI.FeedDescription_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return mtmanapiJNI.FeedDescription_version_get(swigCPtr, this);
  }

  public void setName(String value) {
    mtmanapiJNI.FeedDescription_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.FeedDescription_name_get(swigCPtr, this);
  }

  public void setCopyright(String value) {
    mtmanapiJNI.FeedDescription_copyright_set(swigCPtr, this, value);
  }

  public String getCopyright() {
    return mtmanapiJNI.FeedDescription_copyright_get(swigCPtr, this);
  }

  public void setWeb(String value) {
    mtmanapiJNI.FeedDescription_web_set(swigCPtr, this, value);
  }

  public String getWeb() {
    return mtmanapiJNI.FeedDescription_web_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    mtmanapiJNI.FeedDescription_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return mtmanapiJNI.FeedDescription_email_get(swigCPtr, this);
  }

  public void setServer(String value) {
    mtmanapiJNI.FeedDescription_server_set(swigCPtr, this, value);
  }

  public String getServer() {
    return mtmanapiJNI.FeedDescription_server_get(swigCPtr, this);
  }

  public void setUsername(String value) {
    mtmanapiJNI.FeedDescription_username_set(swigCPtr, this, value);
  }

  public String getUsername() {
    return mtmanapiJNI.FeedDescription_username_get(swigCPtr, this);
  }

  public void setUserpass(String value) {
    mtmanapiJNI.FeedDescription_userpass_set(swigCPtr, this, value);
  }

  public String getUserpass() {
    return mtmanapiJNI.FeedDescription_userpass_get(swigCPtr, this);
  }

  public void setModes(int value) {
    mtmanapiJNI.FeedDescription_modes_set(swigCPtr, this, value);
  }

  public int getModes() {
    return mtmanapiJNI.FeedDescription_modes_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    mtmanapiJNI.FeedDescription_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return mtmanapiJNI.FeedDescription_description_get(swigCPtr, this);
  }

  public void setModule(String value) {
    mtmanapiJNI.FeedDescription_module_set(swigCPtr, this, value);
  }

  public String getModule() {
    return mtmanapiJNI.FeedDescription_module_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.FeedDescription_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.FeedDescription_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public FeedDescription() {
    this(mtmanapiJNI.new_FeedDescription(), true);
  }

}
