/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class MailBox {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MailBox(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MailBox obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_MailBox(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTime(int value) {
    mtmanapiJNI.MailBox_time_set(swigCPtr, this, value);
  }

  public int getTime() {
    return mtmanapiJNI.MailBox_time_get(swigCPtr, this);
  }

  public void setSender(int value) {
    mtmanapiJNI.MailBox_sender_set(swigCPtr, this, value);
  }

  public int getSender() {
    return mtmanapiJNI.MailBox_sender_get(swigCPtr, this);
  }

  public void setFrom(String value) {
    mtmanapiJNI.MailBox_from_set(swigCPtr, this, value);
  }

  public String getFrom() {
    return mtmanapiJNI.MailBox_from_get(swigCPtr, this);
  }

  public void setTo(int value) {
    mtmanapiJNI.MailBox_to_set(swigCPtr, this, value);
  }

  public int getTo() {
    return mtmanapiJNI.MailBox_to_get(swigCPtr, this);
  }

  public void setSubject(String value) {
    mtmanapiJNI.MailBox_subject_set(swigCPtr, this, value);
  }

  public String getSubject() {
    return mtmanapiJNI.MailBox_subject_get(swigCPtr, this);
  }

  public void setReaded(int value) {
    mtmanapiJNI.MailBox_readed_set(swigCPtr, this, value);
  }

  public int getReaded() {
    return mtmanapiJNI.MailBox_readed_get(swigCPtr, this);
  }

  public void setBody(String value) {
    mtmanapiJNI.MailBox_body_set(swigCPtr, this, value);
  }

  public String getBody() {
    return mtmanapiJNI.MailBox_body_get(swigCPtr, this);
  }

  public void setBodylen(int value) {
    mtmanapiJNI.MailBox_bodylen_set(swigCPtr, this, value);
  }

  public int getBodylen() {
    return mtmanapiJNI.MailBox_bodylen_get(swigCPtr, this);
  }

  public void setBuild_min(short value) {
    mtmanapiJNI.MailBox_build_min_set(swigCPtr, this, value);
  }

  public short getBuild_min() {
    return mtmanapiJNI.MailBox_build_min_get(swigCPtr, this);
  }

  public void setBuild_max(short value) {
    mtmanapiJNI.MailBox_build_max_set(swigCPtr, this, value);
  }

  public short getBuild_max() {
    return mtmanapiJNI.MailBox_build_max_get(swigCPtr, this);
  }

  public void setReserved(int value) {
    mtmanapiJNI.MailBox_reserved_set(swigCPtr, this, value);
  }

  public int getReserved() {
    return mtmanapiJNI.MailBox_reserved_get(swigCPtr, this);
  }

  public MailBox() {
    this(mtmanapiJNI.new_MailBox(), true);
  }

}
