/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class mtmanapi implements mtmanapiConstants {
  public static ConGroup new_ConGroupArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConGroupArray(nelements);
    return (cPtr == 0) ? null : new ConGroup(cPtr, false);
  }

  public static void delete_ConGroupArray(ConGroup ary) {
    mtmanapiJNI.delete_ConGroupArray(ConGroup.getCPtr(ary), ary);
  }

  public static ConGroup ConGroupArray_getitem(ConGroup ary, int index) {
    return new ConGroup(mtmanapiJNI.ConGroupArray_getitem(ConGroup.getCPtr(ary), ary, index), true);
  }

  public static void ConGroupArray_setitem(ConGroup ary, int index, ConGroup value) {
    mtmanapiJNI.ConGroupArray_setitem(ConGroup.getCPtr(ary), ary, index, ConGroup.getCPtr(value), value);
  }

  public static ConGroupSec new_ConGroupSecArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConGroupSecArray(nelements);
    return (cPtr == 0) ? null : new ConGroupSec(cPtr, false);
  }

  public static void delete_ConGroupSecArray(ConGroupSec ary) {
    mtmanapiJNI.delete_ConGroupSecArray(ConGroupSec.getCPtr(ary), ary);
  }

  public static ConGroupSec ConGroupSecArray_getitem(ConGroupSec ary, int index) {
    return new ConGroupSec(mtmanapiJNI.ConGroupSecArray_getitem(ConGroupSec.getCPtr(ary), ary, index), true);
  }

  public static void ConGroupSecArray_setitem(ConGroupSec ary, int index, ConGroupSec value) {
    mtmanapiJNI.ConGroupSecArray_setitem(ConGroupSec.getCPtr(ary), ary, index, ConGroupSec.getCPtr(value), value);
  }

  public static UserRecord new_UserRecordArray(int nelements) {
    long cPtr = mtmanapiJNI.new_UserRecordArray(nelements);
    return (cPtr == 0) ? null : new UserRecord(cPtr, false);
  }

  public static void delete_UserRecordArray(UserRecord ary) {
    mtmanapiJNI.delete_UserRecordArray(UserRecord.getCPtr(ary), ary);
  }

  public static UserRecord UserRecordArray_getitem(UserRecord ary, int index) {
    return new UserRecord(mtmanapiJNI.UserRecordArray_getitem(UserRecord.getCPtr(ary), ary, index), true);
  }

  public static void UserRecordArray_setitem(UserRecord ary, int index, UserRecord value) {
    mtmanapiJNI.UserRecordArray_setitem(UserRecord.getCPtr(ary), ary, index, UserRecord.getCPtr(value), value);
  }

  public static TradeRecord new_TradeRecordArray(int nelements) {
    long cPtr = mtmanapiJNI.new_TradeRecordArray(nelements);
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public static void delete_TradeRecordArray(TradeRecord ary) {
    mtmanapiJNI.delete_TradeRecordArray(TradeRecord.getCPtr(ary), ary);
  }

  public static TradeRecord TradeRecordArray_getitem(TradeRecord ary, int index) {
    return new TradeRecord(mtmanapiJNI.TradeRecordArray_getitem(TradeRecord.getCPtr(ary), ary, index), true);
  }

  public static void TradeRecordArray_setitem(TradeRecord ary, int index, TradeRecord value) {
    mtmanapiJNI.TradeRecordArray_setitem(TradeRecord.getCPtr(ary), ary, index, TradeRecord.getCPtr(value), value);
  }

  public static ConSymbol new_ConSymbolArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConSymbolArray(nelements);
    return (cPtr == 0) ? null : new ConSymbol(cPtr, false);
  }

  public static void delete_ConSymbolArray(ConSymbol ary) {
    mtmanapiJNI.delete_ConSymbolArray(ConSymbol.getCPtr(ary), ary);
  }

  public static ConSymbol ConSymbolArray_getitem(ConSymbol ary, int index) {
    return new ConSymbol(mtmanapiJNI.ConSymbolArray_getitem(ConSymbol.getCPtr(ary), ary, index), true);
  }

  public static void ConSymbolArray_setitem(ConSymbol ary, int index, ConSymbol value) {
    mtmanapiJNI.ConSymbolArray_setitem(ConSymbol.getCPtr(ary), ary, index, ConSymbol.getCPtr(value), value);
  }

  public static SymbolInfo new_SymbolInfoArray(int nelements) {
    long cPtr = mtmanapiJNI.new_SymbolInfoArray(nelements);
    return (cPtr == 0) ? null : new SymbolInfo(cPtr, false);
  }

  public static void delete_SymbolInfoArray(SymbolInfo ary) {
    mtmanapiJNI.delete_SymbolInfoArray(SymbolInfo.getCPtr(ary), ary);
  }

  public static SymbolInfo SymbolInfoArray_getitem(SymbolInfo ary, int index) {
    return new SymbolInfo(mtmanapiJNI.SymbolInfoArray_getitem(SymbolInfo.getCPtr(ary), ary, index), true);
  }

  public static void SymbolInfoArray_setitem(SymbolInfo ary, int index, SymbolInfo value) {
    mtmanapiJNI.SymbolInfoArray_setitem(SymbolInfo.getCPtr(ary), ary, index, SymbolInfo.getCPtr(value), value);
  }

  public static RateInfo new_RateInfoArray(int nelements) {
    long cPtr = mtmanapiJNI.new_RateInfoArray(nelements);
    return (cPtr == 0) ? null : new RateInfo(cPtr, false);
  }

  public static void delete_RateInfoArray(RateInfo ary) {
    mtmanapiJNI.delete_RateInfoArray(RateInfo.getCPtr(ary), ary);
  }

  public static RateInfo RateInfoArray_getitem(RateInfo ary, int index) {
    return new RateInfo(mtmanapiJNI.RateInfoArray_getitem(RateInfo.getCPtr(ary), ary, index), true);
  }

  public static void RateInfoArray_setitem(RateInfo ary, int index, RateInfo value) {
    mtmanapiJNI.RateInfoArray_setitem(RateInfo.getCPtr(ary), ary, index, RateInfo.getCPtr(value), value);
  }

  public static TickInfo new_TickInfoArray(int nelements) {
    long cPtr = mtmanapiJNI.new_TickInfoArray(nelements);
    return (cPtr == 0) ? null : new TickInfo(cPtr, false);
  }

  public static void delete_TickInfoArray(TickInfo ary) {
    mtmanapiJNI.delete_TickInfoArray(TickInfo.getCPtr(ary), ary);
  }

  public static TickInfo TickInfoArray_getitem(TickInfo ary, int index) {
    return new TickInfo(mtmanapiJNI.TickInfoArray_getitem(TickInfo.getCPtr(ary), ary, index), true);
  }

  public static void TickInfoArray_setitem(TickInfo ary, int index, TickInfo value) {
    mtmanapiJNI.TickInfoArray_setitem(TickInfo.getCPtr(ary), ary, index, TickInfo.getCPtr(value), value);
  }

  public static ConSessions new_ConSessionsArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConSessionsArray(nelements);
    return (cPtr == 0) ? null : new ConSessions(cPtr, false);
  }

  public static void delete_ConSessionsArray(ConSessions ary) {
    mtmanapiJNI.delete_ConSessionsArray(ConSessions.getCPtr(ary), ary);
  }

  public static ConSessions ConSessionsArray_getitem(ConSessions ary, int index) {
    return new ConSessions(mtmanapiJNI.ConSessionsArray_getitem(ConSessions.getCPtr(ary), ary, index), true);
  }

  public static void ConSessionsArray_setitem(ConSessions ary, int index, ConSessions value) {
    mtmanapiJNI.ConSessionsArray_setitem(ConSessions.getCPtr(ary), ary, index, ConSessions.getCPtr(value), value);
  }

  public static ConSession new_ConSessionArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConSessionArray(nelements);
    return (cPtr == 0) ? null : new ConSession(cPtr, false);
  }

  public static void delete_ConSessionArray(ConSession ary) {
    mtmanapiJNI.delete_ConSessionArray(ConSession.getCPtr(ary), ary);
  }

  public static ConSession ConSessionArray_getitem(ConSession ary, int index) {
    return new ConSession(mtmanapiJNI.ConSessionArray_getitem(ConSession.getCPtr(ary), ary, index), true);
  }

  public static void ConSessionArray_setitem(ConSession ary, int index, ConSession value) {
    mtmanapiJNI.ConSessionArray_setitem(ConSession.getCPtr(ary), ary, index, ConSession.getCPtr(value), value);
  }

  public static void setGlobalPumper(PumpReceiver value) {
    mtmanapiJNI.globalPumper_set(PumpReceiver.getCPtr(value), value);
  }

  public static PumpReceiver getGlobalPumper() {
    long cPtr = mtmanapiJNI.globalPumper_get();
    return (cPtr == 0) ? null : new PumpReceiver(cPtr, false);
  }

  public static void pumpingCallback(int code, int typ, SWIGTYPE_p_void data, SWIGTYPE_p_void param) {
    mtmanapiJNI.pumpingCallback(code, typ, SWIGTYPE_p_void.getCPtr(data), SWIGTYPE_p_void.getCPtr(param));
  }

  public static void pumpingSwitchEx(CManagerInterface c, int flags, SWIGTYPE_p_void param) {
    mtmanapiJNI.pumpingSwitchEx(CManagerInterface.getCPtr(c), c, flags, SWIGTYPE_p_void.getCPtr(param));
  }

}
