/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public interface mtmanapiConstants {
  public final static int ManAPIProgramVersion = mtmanapiJNI.ManAPIProgramVersion_get();
  public final static int ManAPIProgramBuild = mtmanapiJNI.ManAPIProgramBuild_get();
  public final static int CONFIG_ALL = mtmanapiJNI.CONFIG_ALL_get();
  public final static int CONFIG_COMMON = mtmanapiJNI.CONFIG_COMMON_get();
  public final static int CONFIG_ACCESS = mtmanapiJNI.CONFIG_ACCESS_get();
  public final static int CONFIG_SERVERS = mtmanapiJNI.CONFIG_SERVERS_get();
  public final static int CONFIG_TIME = mtmanapiJNI.CONFIG_TIME_get();
  public final static int CONFIG_HOLIDAYS = mtmanapiJNI.CONFIG_HOLIDAYS_get();
  public final static int CONFIG_SYMBOLS = mtmanapiJNI.CONFIG_SYMBOLS_get();
  public final static int CONFIG_SYMB_GROUPS = mtmanapiJNI.CONFIG_SYMB_GROUPS_get();
  public final static int CONFIG_GROUPS = mtmanapiJNI.CONFIG_GROUPS_get();
  public final static int CONFIG_MANAGERS = mtmanapiJNI.CONFIG_MANAGERS_get();
  public final static int CONFIG_DATAFEEDS = mtmanapiJNI.CONFIG_DATAFEEDS_get();
  public final static int CONFIG_BACKUP = mtmanapiJNI.CONFIG_BACKUP_get();
  public final static int CONFIG_LIVEUPDATE = mtmanapiJNI.CONFIG_LIVEUPDATE_get();
  public final static int CONFIG_SYNC = mtmanapiJNI.CONFIG_SYNC_get();
  public final static int CONFIG_PLUGINS = mtmanapiJNI.CONFIG_PLUGINS_get();
  public final static int CONFIG_GATEWAY_ACCOUNTS = mtmanapiJNI.CONFIG_GATEWAY_ACCOUNTS_get();
  public final static int CONFIG_GATEWAY_MARKUPS = mtmanapiJNI.CONFIG_GATEWAY_MARKUPS_get();
  public final static int CONFIG_GATEWAY_RULES = mtmanapiJNI.CONFIG_GATEWAY_RULES_get();
  public final static int CONFIG_END = mtmanapiJNI.CONFIG_END_get();

  public final static int DEMO_DISABLED = mtmanapiJNI.DEMO_DISABLED_get();
  public final static int DEMO_PROLONG = mtmanapiJNI.DEMO_PROLONG_get();
  public final static int DEMO_FIXED = mtmanapiJNI.DEMO_FIXED_get();

  public final static int ROLLOVER_NORMAL = mtmanapiJNI.ROLLOVER_NORMAL_get();
  public final static int ROLLOVER_REOPEN_BY_CLOSE_PRICE = mtmanapiJNI.ROLLOVER_REOPEN_BY_CLOSE_PRICE_get();
  public final static int ROLLOVER_REOPEN_BY_BID = mtmanapiJNI.ROLLOVER_REOPEN_BY_BID_get();

  public final static int LIVE_UPDATE_NO = mtmanapiJNI.LIVE_UPDATE_NO_get();
  public final static int LIVE_UPDATE_RELEASE = mtmanapiJNI.LIVE_UPDATE_RELEASE_get();
  public final static int LIVE_UPDATE_NO_SERVER = mtmanapiJNI.LIVE_UPDATE_NO_SERVER_get();
  public final static int LIVE_UPDATE_BETA = mtmanapiJNI.LIVE_UPDATE_BETA_get();

  public final static int STATEMENT_END_DAY = mtmanapiJNI.STATEMENT_END_DAY_get();
  public final static int STATEMENT_START_DAY = mtmanapiJNI.STATEMENT_START_DAY_get();

  public final static int MONTHLY_STATEMENT_END_MONTH = mtmanapiJNI.MONTHLY_STATEMENT_END_MONTH_get();
  public final static int MONTHLY_STATEMENT_START_MONTH = mtmanapiJNI.MONTHLY_STATEMENT_START_MONTH_get();

  public final static int STOP_REASON_NONE = mtmanapiJNI.STOP_REASON_NONE_get();
  public final static int STOP_REASON_RESTART = mtmanapiJNI.STOP_REASON_RESTART_get();
  public final static int STOP_REASON_SHUTDOWN = mtmanapiJNI.STOP_REASON_SHUTDOWN_get();
  public final static int STOP_REASON_LIVEUPDATE = mtmanapiJNI.STOP_REASON_LIVEUPDATE_get();

  public final static int FW_BLOCK = mtmanapiJNI.FW_BLOCK_get();
  public final static int FW_PERMIT = mtmanapiJNI.FW_PERMIT_get();

  public final static int WATCH_STAND_ALONE = mtmanapiJNI.WATCH_STAND_ALONE_get();
  public final static int WATCH_MASTER = mtmanapiJNI.WATCH_MASTER_get();
  public final static int WATCH_SLAVE = mtmanapiJNI.WATCH_SLAVE_get();

  public final static int BACKUP_1HOUR = mtmanapiJNI.BACKUP_1HOUR_get();
  public final static int BACKUP_4HOURS = mtmanapiJNI.BACKUP_4HOURS_get();
  public final static int BACKUP_1DAY = mtmanapiJNI.BACKUP_1DAY_get();

  public final static int BU_STORE_1MONTH = mtmanapiJNI.BU_STORE_1MONTH_get();
  public final static int BU_STORE_3MONTHS = mtmanapiJNI.BU_STORE_3MONTHS_get();
  public final static int BU_STORE_6MONTHS = mtmanapiJNI.BU_STORE_6MONTHS_get();
  public final static int BU_STORE_1YEAR = mtmanapiJNI.BU_STORE_1YEAR_get();

  public final static int ARC_BACKUP_DISABLED = mtmanapiJNI.ARC_BACKUP_DISABLED_get();
  public final static int ARC_BACKUP_5MIN = mtmanapiJNI.ARC_BACKUP_5MIN_get();
  public final static int ARC_BACKUP_15MIN = mtmanapiJNI.ARC_BACKUP_15MIN_get();
  public final static int ARC_BACKUP_30MIN = mtmanapiJNI.ARC_BACKUP_30MIN_get();
  public final static int ARC_BACKUP_1HOUR = mtmanapiJNI.ARC_BACKUP_1HOUR_get();

  public final static int ARC_STORE_1DAY = mtmanapiJNI.ARC_STORE_1DAY_get();
  public final static int ARC_STORE_3DAYS = mtmanapiJNI.ARC_STORE_3DAYS_get();
  public final static int ARC_STORE_1WEEK = mtmanapiJNI.ARC_STORE_1WEEK_get();
  public final static int ARC_STORE_2WEEKS = mtmanapiJNI.ARC_STORE_2WEEKS_get();
  public final static int ARC_STORE_1MONTH = mtmanapiJNI.ARC_STORE_1MONTH_get();
  public final static int ARC_STORE_3MONTH = mtmanapiJNI.ARC_STORE_3MONTH_get();
  public final static int ARC_STORE_6MONTH = mtmanapiJNI.ARC_STORE_6MONTH_get();

  public final static int EXPORT_1MIN = mtmanapiJNI.EXPORT_1MIN_get();
  public final static int EXPORT_5MIN = mtmanapiJNI.EXPORT_5MIN_get();
  public final static int EXPORT_15MIN = mtmanapiJNI.EXPORT_15MIN_get();
  public final static int EXPORT_30MIN = mtmanapiJNI.EXPORT_30MIN_get();
  public final static int EXPORT_1HOUR = mtmanapiJNI.EXPORT_1HOUR_get();

  public final static int WS_DISCONNECTED = mtmanapiJNI.WS_DISCONNECTED_get();
  public final static int WS_SYNCHRONIZING = mtmanapiJNI.WS_SYNCHRONIZING_get();
  public final static int WS_SYNCHRONIZED = mtmanapiJNI.WS_SYNCHRONIZED_get();

  public final static int FAILOVER_OFF = mtmanapiJNI.FAILOVER_OFF_get();
  public final static int FAILOVER_MOST = mtmanapiJNI.FAILOVER_MOST_get();
  public final static int FAILOVER_FULL = mtmanapiJNI.FAILOVER_FULL_get();

  public final static int FEED_QUOTES = mtmanapiJNI.FEED_QUOTES_get();
  public final static int FEED_NEWS = mtmanapiJNI.FEED_NEWS_get();
  public final static int FEED_QUOTESNEWS = mtmanapiJNI.FEED_QUOTESNEWS_get();

  public final static int MAX_SEC_GROUPS = mtmanapiJNI.MAX_SEC_GROUPS_get();
  public final static int MAX_SEC_GROPS_MARGIN = mtmanapiJNI.MAX_SEC_GROPS_MARGIN_get();
  public final static int EXECUTION_MANUAL = mtmanapiJNI.EXECUTION_MANUAL_get();
  public final static int EXECUTION_AUTO = mtmanapiJNI.EXECUTION_AUTO_get();
  public final static int EXECUTION_ACTIVITY = mtmanapiJNI.EXECUTION_ACTIVITY_get();

  public final static int COMM_TYPE_MONEY = mtmanapiJNI.COMM_TYPE_MONEY_get();
  public final static int COMM_TYPE_PIPS = mtmanapiJNI.COMM_TYPE_PIPS_get();
  public final static int COMM_TYPE_PERCENT = mtmanapiJNI.COMM_TYPE_PERCENT_get();

  public final static int COMMISSION_PER_LOT = mtmanapiJNI.COMMISSION_PER_LOT_get();
  public final static int COMMISSION_PER_DEAL = mtmanapiJNI.COMMISSION_PER_DEAL_get();

  public final static int TRADE_DENY_NONE = mtmanapiJNI.TRADE_DENY_NONE_get();
  public final static int TRADE_DENY_CLOSEBY = mtmanapiJNI.TRADE_DENY_CLOSEBY_get();
  public final static int TRADE_DENY_MUCLOSEBY = mtmanapiJNI.TRADE_DENY_MUCLOSEBY_get();

  public final static int CLOSE_OUT_NONE = mtmanapiJNI.CLOSE_OUT_NONE_get();
  public final static int CLOSE_OUT_HIHI = mtmanapiJNI.CLOSE_OUT_HIHI_get();
  public final static int CLOSE_OUT_LOLO = mtmanapiJNI.CLOSE_OUT_LOLO_get();
  public final static int CLOSE_OUT_HILO = mtmanapiJNI.CLOSE_OUT_HILO_get();
  public final static int CLOSE_OUT_LOHI = mtmanapiJNI.CLOSE_OUT_LOHI_get();
  public final static int CLOSE_OUT_FIFO = mtmanapiJNI.CLOSE_OUT_FIFO_get();
  public final static int CLOSE_OUT_LIFO = mtmanapiJNI.CLOSE_OUT_LIFO_get();
  public final static int CLOSE_OUT_INTRDAY_FIFO = mtmanapiJNI.CLOSE_OUT_INTRDAY_FIFO_get();

  public final static int MARGIN_MODE_DONT_USE = mtmanapiJNI.MARGIN_MODE_DONT_USE_get();
  public final static int MARGIN_MODE_USE_ALL = mtmanapiJNI.MARGIN_MODE_USE_ALL_get();
  public final static int MARGIN_MODE_USE_PROFIT = mtmanapiJNI.MARGIN_MODE_USE_PROFIT_get();
  public final static int MARGIN_MODE_USE_LOSS = mtmanapiJNI.MARGIN_MODE_USE_LOSS_get();

  public final static int MARGIN_TYPE_PERCENT = mtmanapiJNI.MARGIN_TYPE_PERCENT_get();
  public final static int MARGIN_TYPE_CURRENCY = mtmanapiJNI.MARGIN_TYPE_CURRENCY_get();

  public final static int NEWS_NO = mtmanapiJNI.NEWS_NO_get();
  public final static int NEWS_TOPICS = mtmanapiJNI.NEWS_TOPICS_get();
  public final static int NEWS_FULL = mtmanapiJNI.NEWS_FULL_get();

  public final static int ALLOW_FLAG_EMAIL = mtmanapiJNI.ALLOW_FLAG_EMAIL_get();
  public final static int ALLOW_FLAG_TRAILING = mtmanapiJNI.ALLOW_FLAG_TRAILING_get();
  public final static int ALLOW_FLAG_ADVISOR = mtmanapiJNI.ALLOW_FLAG_ADVISOR_get();
  public final static int ALLOW_FLAG_EXPIRATION = mtmanapiJNI.ALLOW_FLAG_EXPIRATION_get();
  public final static int ALLOW_FLAG_SIGNALS_ALL = mtmanapiJNI.ALLOW_FLAG_SIGNALS_ALL_get();
  public final static int ALLOW_FLAG_SIGNALS_OWN = mtmanapiJNI.ALLOW_FLAG_SIGNALS_OWN_get();
  public final static int ALLOW_FLAG_RISK_WARNING = mtmanapiJNI.ALLOW_FLAG_RISK_WARNING_get();
  public final static int ALLOW_FLAG_FORCED_OTP_USAGE = mtmanapiJNI.ALLOW_FLAG_FORCED_OTP_USAGE_get();

  public final static int OTP_MODE_DISABLED = mtmanapiJNI.OTP_MODE_DISABLED_get();
  public final static int OTP_MODE_TOTP_SHA256 = mtmanapiJNI.OTP_MODE_TOTP_SHA256_get();

  public final static int LIVE_FILES_MAX = mtmanapiJNI.LIVE_FILES_MAX_get();
  public final static int LIVE_UPDATE_CLIENT = mtmanapiJNI.LIVE_UPDATE_CLIENT_get();
  public final static int LIVE_UPDATE_MANAGER = mtmanapiJNI.LIVE_UPDATE_MANAGER_get();
  public final static int LIVE_UPDATE_ADMIN = mtmanapiJNI.LIVE_UPDATE_ADMIN_get();
  public final static int LIVE_UPDATE_DATACENTER = mtmanapiJNI.LIVE_UPDATE_DATACENTER_get();
  public final static int LIVE_UPDATE_CLIENT_PPC2002 = mtmanapiJNI.LIVE_UPDATE_CLIENT_PPC2002_get();
  public final static int LIVE_UPDATE_CLIENT_PPC2003 = mtmanapiJNI.LIVE_UPDATE_CLIENT_PPC2003_get();
  public final static int LIVE_UPDATE_MULTI = mtmanapiJNI.LIVE_UPDATE_MULTI_get();
  public final static int LIVE_UPDATE_WD = mtmanapiJNI.LIVE_UPDATE_WD_get();
  public final static int LIVE_UPDATE_CLIENT_PHONE = mtmanapiJNI.LIVE_UPDATE_CLIENT_PHONE_get();
  public final static int LIVE_UPDATE_LAST = mtmanapiJNI.LIVE_UPDATE_LAST_get();

  public final static int MAX_SYMBOLS = mtmanapiJNI.MAX_SYMBOLS_get();
  public final static int EXE_REQUEST = mtmanapiJNI.EXE_REQUEST_get();
  public final static int EXE_INSTANT = mtmanapiJNI.EXE_INSTANT_get();
  public final static int EXE_MARKET = mtmanapiJNI.EXE_MARKET_get();

  public final static int TRADE_NO = mtmanapiJNI.TRADE_NO_get();
  public final static int TRADE_CLOSE = mtmanapiJNI.TRADE_CLOSE_get();
  public final static int TRADE_FULL = mtmanapiJNI.TRADE_FULL_get();

  public final static int SWAP_BY_POINTS = mtmanapiJNI.SWAP_BY_POINTS_get();
  public final static int SWAP_BY_DOLLARS = mtmanapiJNI.SWAP_BY_DOLLARS_get();
  public final static int SWAP_BY_INTEREST = mtmanapiJNI.SWAP_BY_INTEREST_get();
  public final static int SWAP_BY_MARGIN_CURRENCY = mtmanapiJNI.SWAP_BY_MARGIN_CURRENCY_get();

  public final static int PROFIT_CALC_FOREX = mtmanapiJNI.PROFIT_CALC_FOREX_get();
  public final static int PROFIT_CALC_CFD = mtmanapiJNI.PROFIT_CALC_CFD_get();
  public final static int PROFIT_CALC_FUTURES = mtmanapiJNI.PROFIT_CALC_FUTURES_get();

  public final static int MARGIN_CALC_FOREX = mtmanapiJNI.MARGIN_CALC_FOREX_get();
  public final static int MARGIN_CALC_CFD = mtmanapiJNI.MARGIN_CALC_CFD_get();
  public final static int MARGIN_CALC_FUTURES = mtmanapiJNI.MARGIN_CALC_FUTURES_get();
  public final static int MARGIN_CALC_CFDINDEX = mtmanapiJNI.MARGIN_CALC_CFDINDEX_get();
  public final static int MARGIN_CALC_CFDLEVERAGE = mtmanapiJNI.MARGIN_CALC_CFDLEVERAGE_get();

  public final static int ORDERS_DAILY = mtmanapiJNI.ORDERS_DAILY_get();
  public final static int ORDERS_GTC = mtmanapiJNI.ORDERS_GTC_get();
  public final static int ORDERS_DAILY_NO_STOPS = mtmanapiJNI.ORDERS_DAILY_NO_STOPS_get();

  public final static int MAX_SEC_GROUP = mtmanapiJNI.MAX_SEC_GROUP_get();
  public final static int HB_ADD = mtmanapiJNI.HB_ADD_get();
  public final static int HB_UPDATE = mtmanapiJNI.HB_UPDATE_get();
  public final static int HB_INSERT = mtmanapiJNI.HB_INSERT_get();
  public final static int HB_DELETE = mtmanapiJNI.HB_DELETE_get();
  public final static int HB_LAST = mtmanapiJNI.HB_LAST_get();

  public final static int RET_OK = mtmanapiJNI.RET_OK_get();
  public final static int RET_OK_NONE = mtmanapiJNI.RET_OK_NONE_get();
  public final static int RET_ERROR = mtmanapiJNI.RET_ERROR_get();
  public final static int RET_INVALID_DATA = mtmanapiJNI.RET_INVALID_DATA_get();
  public final static int RET_TECH_PROBLEM = mtmanapiJNI.RET_TECH_PROBLEM_get();
  public final static int RET_OLD_VERSION = mtmanapiJNI.RET_OLD_VERSION_get();
  public final static int RET_NO_CONNECT = mtmanapiJNI.RET_NO_CONNECT_get();
  public final static int RET_NOT_ENOUGH_RIGHTS = mtmanapiJNI.RET_NOT_ENOUGH_RIGHTS_get();
  public final static int RET_TOO_FREQUENT = mtmanapiJNI.RET_TOO_FREQUENT_get();
  public final static int RET_MALFUNCTION = mtmanapiJNI.RET_MALFUNCTION_get();
  public final static int RET_GENERATE_KEY = mtmanapiJNI.RET_GENERATE_KEY_get();
  public final static int RET_SECURITY_SESSION = mtmanapiJNI.RET_SECURITY_SESSION_get();
  public final static int RET_ACCOUNT_DISABLED = mtmanapiJNI.RET_ACCOUNT_DISABLED_get();
  public final static int RET_BAD_ACCOUNT_INFO = mtmanapiJNI.RET_BAD_ACCOUNT_INFO_get();
  public final static int RET_PUBLIC_KEY_MISSING = mtmanapiJNI.RET_PUBLIC_KEY_MISSING_get();
  public final static int RET_TRADE_TIMEOUT = mtmanapiJNI.RET_TRADE_TIMEOUT_get();
  public final static int RET_TRADE_BAD_PRICES = mtmanapiJNI.RET_TRADE_BAD_PRICES_get();
  public final static int RET_TRADE_BAD_STOPS = mtmanapiJNI.RET_TRADE_BAD_STOPS_get();
  public final static int RET_TRADE_BAD_VOLUME = mtmanapiJNI.RET_TRADE_BAD_VOLUME_get();
  public final static int RET_TRADE_MARKET_CLOSED = mtmanapiJNI.RET_TRADE_MARKET_CLOSED_get();
  public final static int RET_TRADE_DISABLE = mtmanapiJNI.RET_TRADE_DISABLE_get();
  public final static int RET_TRADE_NO_MONEY = mtmanapiJNI.RET_TRADE_NO_MONEY_get();
  public final static int RET_TRADE_PRICE_CHANGED = mtmanapiJNI.RET_TRADE_PRICE_CHANGED_get();
  public final static int RET_TRADE_OFFQUOTES = mtmanapiJNI.RET_TRADE_OFFQUOTES_get();
  public final static int RET_TRADE_BROKER_BUSY = mtmanapiJNI.RET_TRADE_BROKER_BUSY_get();
  public final static int RET_TRADE_REQUOTE = mtmanapiJNI.RET_TRADE_REQUOTE_get();
  public final static int RET_TRADE_ORDER_LOCKED = mtmanapiJNI.RET_TRADE_ORDER_LOCKED_get();
  public final static int RET_TRADE_LONG_ONLY = mtmanapiJNI.RET_TRADE_LONG_ONLY_get();
  public final static int RET_TRADE_TOO_MANY_REQ = mtmanapiJNI.RET_TRADE_TOO_MANY_REQ_get();
  public final static int RET_TRADE_ACCEPTED = mtmanapiJNI.RET_TRADE_ACCEPTED_get();
  public final static int RET_TRADE_PROCESS = mtmanapiJNI.RET_TRADE_PROCESS_get();
  public final static int RET_TRADE_USER_CANCEL = mtmanapiJNI.RET_TRADE_USER_CANCEL_get();
  public final static int RET_TRADE_MODIFY_DENIED = mtmanapiJNI.RET_TRADE_MODIFY_DENIED_get();
  public final static int RET_TRADE_CONTEXT_BUSY = mtmanapiJNI.RET_TRADE_CONTEXT_BUSY_get();
  public final static int RET_TRADE_EXPIRATION_DENIED = mtmanapiJNI.RET_TRADE_EXPIRATION_DENIED_get();
  public final static int RET_TRADE_TOO_MANY_ORDERS = mtmanapiJNI.RET_TRADE_TOO_MANY_ORDERS_get();
  public final static int RET_TRADE_HEDGE_PROHIBITED = mtmanapiJNI.RET_TRADE_HEDGE_PROHIBITED_get();
  public final static int RET_TRADE_PROHIBITED_BY_FIFO = mtmanapiJNI.RET_TRADE_PROHIBITED_BY_FIFO_get();

  public final static int CLIENT_FLAGS_HIDETICKS = mtmanapiJNI.CLIENT_FLAGS_HIDETICKS_get();
  public final static int CLIENT_FLAGS_HIDENEWS = mtmanapiJNI.CLIENT_FLAGS_HIDENEWS_get();
  public final static int CLIENT_FLAGS_HIDEMAIL = mtmanapiJNI.CLIENT_FLAGS_HIDEMAIL_get();
  public final static int CLIENT_FLAGS_SENDFULLNEWS = mtmanapiJNI.CLIENT_FLAGS_SENDFULLNEWS_get();
  public final static int CLIENT_FLAGS_RESERVED = mtmanapiJNI.CLIENT_FLAGS_RESERVED_get();
  public final static int CLIENT_FLAGS_HIDEONLINE = mtmanapiJNI.CLIENT_FLAGS_HIDEONLINE_get();
  public final static int CLIENT_FLAGS_HIDEUSERS = mtmanapiJNI.CLIENT_FLAGS_HIDEUSERS_get();

  public final static int PERIOD_M1 = mtmanapiJNI.PERIOD_M1_get();
  public final static int PERIOD_M5 = mtmanapiJNI.PERIOD_M5_get();
  public final static int PERIOD_M15 = mtmanapiJNI.PERIOD_M15_get();
  public final static int PERIOD_M30 = mtmanapiJNI.PERIOD_M30_get();
  public final static int PERIOD_H1 = mtmanapiJNI.PERIOD_H1_get();
  public final static int PERIOD_H4 = mtmanapiJNI.PERIOD_H4_get();
  public final static int PERIOD_D1 = mtmanapiJNI.PERIOD_D1_get();
  public final static int PERIOD_W1 = mtmanapiJNI.PERIOD_W1_get();
  public final static int PERIOD_MN1 = mtmanapiJNI.PERIOD_MN1_get();

  public final static int CHART_RANGE_IN = mtmanapiJNI.CHART_RANGE_IN_get();
  public final static int CHART_RANGE_OUT = mtmanapiJNI.CHART_RANGE_OUT_get();
  public final static int CHART_RANGE_LAST = mtmanapiJNI.CHART_RANGE_LAST_get();

  public final static int TICK_FLAG_RAW = mtmanapiJNI.TICK_FLAG_RAW_get();
  public final static int TICK_FLAG_NORMAL = mtmanapiJNI.TICK_FLAG_NORMAL_get();
  public final static int TICK_FLAG_ALL = mtmanapiJNI.TICK_FLAG_ALL_get();

  public final static int BACKUPS_ALL = mtmanapiJNI.BACKUPS_ALL_get();
  public final static int BACKUPS_PERIODICAL = mtmanapiJNI.BACKUPS_PERIODICAL_get();
  public final static int BACKUPS_STARTUP = mtmanapiJNI.BACKUPS_STARTUP_get();
  public final static int BACKUPS_DELETE = mtmanapiJNI.BACKUPS_DELETE_get();

  public final static int TRANS_ADD = mtmanapiJNI.TRANS_ADD_get();
  public final static int TRANS_DELETE = mtmanapiJNI.TRANS_DELETE_get();
  public final static int TRANS_UPDATE = mtmanapiJNI.TRANS_UPDATE_get();
  public final static int TRANS_CHANGE_GRP = mtmanapiJNI.TRANS_CHANGE_GRP_get();

  public final static int PUBLIC_KEY_SIZE = mtmanapiJNI.PUBLIC_KEY_SIZE_get();
  public final static int USER_COLOR_NONE = mtmanapiJNI.USER_COLOR_NONE_get();
  public final static int GROUP_DELETE = mtmanapiJNI.GROUP_DELETE_get();
  public final static int GROUP_ENABLE = mtmanapiJNI.GROUP_ENABLE_get();
  public final static int GROUP_DISABLE = mtmanapiJNI.GROUP_DISABLE_get();
  public final static int GROUP_LEVERAGE = mtmanapiJNI.GROUP_LEVERAGE_get();
  public final static int GROUP_SETGROUP = mtmanapiJNI.GROUP_SETGROUP_get();

  public final static int OP_BUY = mtmanapiJNI.OP_BUY_get();
  public final static int OP_SELL = mtmanapiJNI.OP_SELL_get();
  public final static int OP_BUY_LIMIT = mtmanapiJNI.OP_BUY_LIMIT_get();
  public final static int OP_SELL_LIMIT = mtmanapiJNI.OP_SELL_LIMIT_get();
  public final static int OP_BUY_STOP = mtmanapiJNI.OP_BUY_STOP_get();
  public final static int OP_SELL_STOP = mtmanapiJNI.OP_SELL_STOP_get();
  public final static int OP_BALANCE = mtmanapiJNI.OP_BALANCE_get();
  public final static int OP_CREDIT = mtmanapiJNI.OP_CREDIT_get();

  public final static int TS_OPEN_NORMAL = mtmanapiJNI.TS_OPEN_NORMAL_get();
  public final static int TS_OPEN_REMAND = mtmanapiJNI.TS_OPEN_REMAND_get();
  public final static int TS_OPEN_RESTORED = mtmanapiJNI.TS_OPEN_RESTORED_get();
  public final static int TS_CLOSED_NORMAL = mtmanapiJNI.TS_CLOSED_NORMAL_get();
  public final static int TS_CLOSED_PART = mtmanapiJNI.TS_CLOSED_PART_get();
  public final static int TS_CLOSED_BY = mtmanapiJNI.TS_CLOSED_BY_get();
  public final static int TS_DELETED = mtmanapiJNI.TS_DELETED_get();

  public final static int TR_REASON_CLIENT = mtmanapiJNI.TR_REASON_CLIENT_get();
  public final static int TR_REASON_EXPERT = mtmanapiJNI.TR_REASON_EXPERT_get();
  public final static int TR_REASON_DEALER = mtmanapiJNI.TR_REASON_DEALER_get();
  public final static int TR_REASON_SIGNAL = mtmanapiJNI.TR_REASON_SIGNAL_get();
  public final static int TR_REASON_GATEWAY = mtmanapiJNI.TR_REASON_GATEWAY_get();
  public final static int TR_REASON_MOBILE = mtmanapiJNI.TR_REASON_MOBILE_get();
  public final static int TR_REASON_WEB = mtmanapiJNI.TR_REASON_WEB_get();
  public final static int TR_REASON_API = mtmanapiJNI.TR_REASON_API_get();

  public final static int ACTIVATION_NONE = mtmanapiJNI.ACTIVATION_NONE_get();
  public final static int ACTIVATION_SL = mtmanapiJNI.ACTIVATION_SL_get();
  public final static int ACTIVATION_TP = mtmanapiJNI.ACTIVATION_TP_get();
  public final static int ACTIVATION_PENDING = mtmanapiJNI.ACTIVATION_PENDING_get();
  public final static int ACTIVATION_STOPOUT = mtmanapiJNI.ACTIVATION_STOPOUT_get();
  public final static int ACTIVATION_SL_ROLLBACK = mtmanapiJNI.ACTIVATION_SL_ROLLBACK_get();
  public final static int ACTIVATION_TP_ROLLBACK = mtmanapiJNI.ACTIVATION_TP_ROLLBACK_get();
  public final static int ACTIVATION_PENDING_ROLLBACK = mtmanapiJNI.ACTIVATION_PENDING_ROLLBACK_get();
  public final static int ACTIVATION_STOPOUT_ROLLBACK = mtmanapiJNI.ACTIVATION_STOPOUT_ROLLBACK_get();

  public final static int TT_PRICES_GET = mtmanapiJNI.TT_PRICES_GET_get();
  public final static int TT_PRICES_REQUOTE = mtmanapiJNI.TT_PRICES_REQUOTE_get();
  public final static int TT_ORDER_IE_OPEN = mtmanapiJNI.TT_ORDER_IE_OPEN_get();
  public final static int TT_ORDER_REQ_OPEN = mtmanapiJNI.TT_ORDER_REQ_OPEN_get();
  public final static int TT_ORDER_MK_OPEN = mtmanapiJNI.TT_ORDER_MK_OPEN_get();
  public final static int TT_ORDER_PENDING_OPEN = mtmanapiJNI.TT_ORDER_PENDING_OPEN_get();
  public final static int TT_ORDER_IE_CLOSE = mtmanapiJNI.TT_ORDER_IE_CLOSE_get();
  public final static int TT_ORDER_REQ_CLOSE = mtmanapiJNI.TT_ORDER_REQ_CLOSE_get();
  public final static int TT_ORDER_MK_CLOSE = mtmanapiJNI.TT_ORDER_MK_CLOSE_get();
  public final static int TT_ORDER_MODIFY = mtmanapiJNI.TT_ORDER_MODIFY_get();
  public final static int TT_ORDER_DELETE = mtmanapiJNI.TT_ORDER_DELETE_get();
  public final static int TT_ORDER_CLOSE_BY = mtmanapiJNI.TT_ORDER_CLOSE_BY_get();
  public final static int TT_ORDER_CLOSE_ALL = mtmanapiJNI.TT_ORDER_CLOSE_ALL_get();
  public final static int TT_BR_ORDER_OPEN = mtmanapiJNI.TT_BR_ORDER_OPEN_get();
  public final static int TT_BR_ORDER_CLOSE = mtmanapiJNI.TT_BR_ORDER_CLOSE_get();
  public final static int TT_BR_ORDER_DELETE = mtmanapiJNI.TT_BR_ORDER_DELETE_get();
  public final static int TT_BR_ORDER_CLOSE_BY = mtmanapiJNI.TT_BR_ORDER_CLOSE_BY_get();
  public final static int TT_BR_ORDER_CLOSE_ALL = mtmanapiJNI.TT_BR_ORDER_CLOSE_ALL_get();
  public final static int TT_BR_ORDER_MODIFY = mtmanapiJNI.TT_BR_ORDER_MODIFY_get();
  public final static int TT_BR_ORDER_ACTIVATE = mtmanapiJNI.TT_BR_ORDER_ACTIVATE_get();
  public final static int TT_BR_ORDER_COMMENT = mtmanapiJNI.TT_BR_ORDER_COMMENT_get();
  public final static int TT_BR_BALANCE = mtmanapiJNI.TT_BR_BALANCE_get();

  public final static int MARGINLEVEL_OK = mtmanapiJNI.MARGINLEVEL_OK_get();
  public final static int MARGINLEVEL_MARGINCALL = mtmanapiJNI.MARGINLEVEL_MARGINCALL_get();
  public final static int MARGINLEVEL_STOPOUT = mtmanapiJNI.MARGINLEVEL_STOPOUT_get();

  public final static int DC_EMPTY = mtmanapiJNI.DC_EMPTY_get();
  public final static int DC_REQUEST = mtmanapiJNI.DC_REQUEST_get();
  public final static int DC_LOCKED = mtmanapiJNI.DC_LOCKED_get();
  public final static int DC_ANSWERED = mtmanapiJNI.DC_ANSWERED_get();
  public final static int DC_RESETED = mtmanapiJNI.DC_RESETED_get();
  public final static int DC_CANCELED = mtmanapiJNI.DC_CANCELED_get();

  public final static int SDIR_UP = mtmanapiJNI.SDIR_UP_get();
  public final static int SDIR_DOWN = mtmanapiJNI.SDIR_DOWN_get();
  public final static int SDIR_NONE = mtmanapiJNI.SDIR_NONE_get();

  public final static int PUMP_START_PUMPING = mtmanapiJNI.PUMP_START_PUMPING_get();
  public final static int PUMP_UPDATE_SYMBOLS = mtmanapiJNI.PUMP_UPDATE_SYMBOLS_get();
  public final static int PUMP_UPDATE_GROUPS = mtmanapiJNI.PUMP_UPDATE_GROUPS_get();
  public final static int PUMP_UPDATE_USERS = mtmanapiJNI.PUMP_UPDATE_USERS_get();
  public final static int PUMP_UPDATE_ONLINE = mtmanapiJNI.PUMP_UPDATE_ONLINE_get();
  public final static int PUMP_UPDATE_BIDASK = mtmanapiJNI.PUMP_UPDATE_BIDASK_get();
  public final static int PUMP_UPDATE_NEWS = mtmanapiJNI.PUMP_UPDATE_NEWS_get();
  public final static int PUMP_UPDATE_NEWS_BODY = mtmanapiJNI.PUMP_UPDATE_NEWS_BODY_get();
  public final static int PUMP_UPDATE_MAIL = mtmanapiJNI.PUMP_UPDATE_MAIL_get();
  public final static int PUMP_UPDATE_TRADES = mtmanapiJNI.PUMP_UPDATE_TRADES_get();
  public final static int PUMP_UPDATE_REQUESTS = mtmanapiJNI.PUMP_UPDATE_REQUESTS_get();
  public final static int PUMP_UPDATE_PLUGINS = mtmanapiJNI.PUMP_UPDATE_PLUGINS_get();
  public final static int PUMP_UPDATE_ACTIVATION = mtmanapiJNI.PUMP_UPDATE_ACTIVATION_get();
  public final static int PUMP_UPDATE_MARGINCALL = mtmanapiJNI.PUMP_UPDATE_MARGINCALL_get();
  public final static int PUMP_STOP_PUMPING = mtmanapiJNI.PUMP_STOP_PUMPING_get();
  public final static int PUMP_PING = mtmanapiJNI.PUMP_PING_get();
  public final static int PUMP_UPDATE_NEWS_NEW = mtmanapiJNI.PUMP_UPDATE_NEWS_NEW_get();

  public final static int DEAL_START_DEALING = mtmanapiJNI.DEAL_START_DEALING_get();
  public final static int DEAL_REQUEST_NEW = mtmanapiJNI.DEAL_REQUEST_NEW_get();
  public final static int DEAL_STOP_DEALING = mtmanapiJNI.DEAL_STOP_DEALING_get();

}
