/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class PerformanceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PerformanceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PerformanceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_PerformanceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCtm(int value) {
    mtmanapiJNI.PerformanceInfo_ctm_set(swigCPtr, this, value);
  }

  public int getCtm() {
    return mtmanapiJNI.PerformanceInfo_ctm_get(swigCPtr, this);
  }

  public void setUsers(short value) {
    mtmanapiJNI.PerformanceInfo_users_set(swigCPtr, this, value);
  }

  public short getUsers() {
    return mtmanapiJNI.PerformanceInfo_users_get(swigCPtr, this);
  }

  public void setCpu(short value) {
    mtmanapiJNI.PerformanceInfo_cpu_set(swigCPtr, this, value);
  }

  public short getCpu() {
    return mtmanapiJNI.PerformanceInfo_cpu_get(swigCPtr, this);
  }

  public void setFreemem(int value) {
    mtmanapiJNI.PerformanceInfo_freemem_set(swigCPtr, this, value);
  }

  public int getFreemem() {
    return mtmanapiJNI.PerformanceInfo_freemem_get(swigCPtr, this);
  }

  public void setNetwork(int value) {
    mtmanapiJNI.PerformanceInfo_network_set(swigCPtr, this, value);
  }

  public int getNetwork() {
    return mtmanapiJNI.PerformanceInfo_network_get(swigCPtr, this);
  }

  public void setSockets(int value) {
    mtmanapiJNI.PerformanceInfo_sockets_set(swigCPtr, this, value);
  }

  public int getSockets() {
    return mtmanapiJNI.PerformanceInfo_sockets_get(swigCPtr, this);
  }

  public PerformanceInfo() {
    this(mtmanapiJNI.new_PerformanceInfo(), true);
  }

}
