/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class RequestInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RequestInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequestInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_RequestInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(int value) {
    mtmanapiJNI.RequestInfo_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return mtmanapiJNI.RequestInfo_id_get(swigCPtr, this);
  }

  public void setStatus(char value) {
    mtmanapiJNI.RequestInfo_status_set(swigCPtr, this, value);
  }

  public char getStatus() {
    return mtmanapiJNI.RequestInfo_status_get(swigCPtr, this);
  }

  public void setTime(long value) {
    mtmanapiJNI.RequestInfo_time_set(swigCPtr, this, value);
  }

  public long getTime() {
    return mtmanapiJNI.RequestInfo_time_get(swigCPtr, this);
  }

  public void setManager(int value) {
    mtmanapiJNI.RequestInfo_manager_set(swigCPtr, this, value);
  }

  public int getManager() {
    return mtmanapiJNI.RequestInfo_manager_get(swigCPtr, this);
  }

  public void setLogin(int value) {
    mtmanapiJNI.RequestInfo_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.RequestInfo_login_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    mtmanapiJNI.RequestInfo_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mtmanapiJNI.RequestInfo_group_get(swigCPtr, this);
  }

  public void setBalance(double value) {
    mtmanapiJNI.RequestInfo_balance_set(swigCPtr, this, value);
  }

  public double getBalance() {
    return mtmanapiJNI.RequestInfo_balance_get(swigCPtr, this);
  }

  public void setCredit(double value) {
    mtmanapiJNI.RequestInfo_credit_set(swigCPtr, this, value);
  }

  public double getCredit() {
    return mtmanapiJNI.RequestInfo_credit_get(swigCPtr, this);
  }

  public void setPrices(SWIGTYPE_p_double value) {
    mtmanapiJNI.RequestInfo_prices_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getPrices() {
    long cPtr = mtmanapiJNI.RequestInfo_prices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setTrade(TradeTransInfo value) {
    mtmanapiJNI.RequestInfo_trade_set(swigCPtr, this, TradeTransInfo.getCPtr(value), value);
  }

  public TradeTransInfo getTrade() {
    long cPtr = mtmanapiJNI.RequestInfo_trade_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TradeTransInfo(cPtr, false);
  }

  public void setGw_volume(int value) {
    mtmanapiJNI.RequestInfo_gw_volume_set(swigCPtr, this, value);
  }

  public int getGw_volume() {
    return mtmanapiJNI.RequestInfo_gw_volume_get(swigCPtr, this);
  }

  public void setGw_order(int value) {
    mtmanapiJNI.RequestInfo_gw_order_set(swigCPtr, this, value);
  }

  public int getGw_order() {
    return mtmanapiJNI.RequestInfo_gw_order_get(swigCPtr, this);
  }

  public void setGw_price(short value) {
    mtmanapiJNI.RequestInfo_gw_price_set(swigCPtr, this, value);
  }

  public short getGw_price() {
    return mtmanapiJNI.RequestInfo_gw_price_get(swigCPtr, this);
  }

  public void setPrev(RequestInfo value) {
    mtmanapiJNI.RequestInfo_prev_set(swigCPtr, this, RequestInfo.getCPtr(value), value);
  }

  public RequestInfo getPrev() {
    long cPtr = mtmanapiJNI.RequestInfo_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RequestInfo(cPtr, false);
  }

  public void setNext(RequestInfo value) {
    mtmanapiJNI.RequestInfo_next_set(swigCPtr, this, RequestInfo.getCPtr(value), value);
  }

  public RequestInfo getNext() {
    long cPtr = mtmanapiJNI.RequestInfo_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RequestInfo(cPtr, false);
  }

  public RequestInfo() {
    this(mtmanapiJNI.new_RequestInfo(), true);
  }

}
