/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class SymbolSummary {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SymbolSummary(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymbolSummary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_SymbolSummary(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.SymbolSummary_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.SymbolSummary_symbol_get(swigCPtr, this);
  }

  public void setCount(int value) {
    mtmanapiJNI.SymbolSummary_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return mtmanapiJNI.SymbolSummary_count_get(swigCPtr, this);
  }

  public void setDigits(int value) {
    mtmanapiJNI.SymbolSummary_digits_set(swigCPtr, this, value);
  }

  public int getDigits() {
    return mtmanapiJNI.SymbolSummary_digits_get(swigCPtr, this);
  }

  public void setType(int value) {
    mtmanapiJNI.SymbolSummary_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mtmanapiJNI.SymbolSummary_type_get(swigCPtr, this);
  }

  public void setOrders(int value) {
    mtmanapiJNI.SymbolSummary_orders_set(swigCPtr, this, value);
  }

  public int getOrders() {
    return mtmanapiJNI.SymbolSummary_orders_get(swigCPtr, this);
  }

  public void setBuylots(long value) {
    mtmanapiJNI.SymbolSummary_buylots_set(swigCPtr, this, value);
  }

  public long getBuylots() {
    return mtmanapiJNI.SymbolSummary_buylots_get(swigCPtr, this);
  }

  public void setSelllots(long value) {
    mtmanapiJNI.SymbolSummary_selllots_set(swigCPtr, this, value);
  }

  public long getSelllots() {
    return mtmanapiJNI.SymbolSummary_selllots_get(swigCPtr, this);
  }

  public void setBuyprice(double value) {
    mtmanapiJNI.SymbolSummary_buyprice_set(swigCPtr, this, value);
  }

  public double getBuyprice() {
    return mtmanapiJNI.SymbolSummary_buyprice_get(swigCPtr, this);
  }

  public void setSellprice(double value) {
    mtmanapiJNI.SymbolSummary_sellprice_set(swigCPtr, this, value);
  }

  public double getSellprice() {
    return mtmanapiJNI.SymbolSummary_sellprice_get(swigCPtr, this);
  }

  public void setProfit(double value) {
    mtmanapiJNI.SymbolSummary_profit_set(swigCPtr, this, value);
  }

  public double getProfit() {
    return mtmanapiJNI.SymbolSummary_profit_get(swigCPtr, this);
  }

  public void setCovorders(int value) {
    mtmanapiJNI.SymbolSummary_covorders_set(swigCPtr, this, value);
  }

  public int getCovorders() {
    return mtmanapiJNI.SymbolSummary_covorders_get(swigCPtr, this);
  }

  public void setCovbuylots(long value) {
    mtmanapiJNI.SymbolSummary_covbuylots_set(swigCPtr, this, value);
  }

  public long getCovbuylots() {
    return mtmanapiJNI.SymbolSummary_covbuylots_get(swigCPtr, this);
  }

  public void setCovselllots(long value) {
    mtmanapiJNI.SymbolSummary_covselllots_set(swigCPtr, this, value);
  }

  public long getCovselllots() {
    return mtmanapiJNI.SymbolSummary_covselllots_get(swigCPtr, this);
  }

  public void setCovbuyprice(double value) {
    mtmanapiJNI.SymbolSummary_covbuyprice_set(swigCPtr, this, value);
  }

  public double getCovbuyprice() {
    return mtmanapiJNI.SymbolSummary_covbuyprice_get(swigCPtr, this);
  }

  public void setCovsellprice(double value) {
    mtmanapiJNI.SymbolSummary_covsellprice_set(swigCPtr, this, value);
  }

  public double getCovsellprice() {
    return mtmanapiJNI.SymbolSummary_covsellprice_get(swigCPtr, this);
  }

  public void setCovprofit(double value) {
    mtmanapiJNI.SymbolSummary_covprofit_set(swigCPtr, this, value);
  }

  public double getCovprofit() {
    return mtmanapiJNI.SymbolSummary_covprofit_get(swigCPtr, this);
  }

  public SymbolSummary() {
    this(mtmanapiJNI.new_SymbolSummary(), true);
  }

}
