/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.fxcms.mt4.api;

public class TickInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TickInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TickInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_TickInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.TickInfo_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.TickInfo_symbol_get(swigCPtr, this);
  }

  public void setCtm(int value) {
    mtmanapiJNI.TickInfo_ctm_set(swigCPtr, this, value);
  }

  public int getCtm() {
    return mtmanapiJNI.TickInfo_ctm_get(swigCPtr, this);
  }

  public void setBid(double value) {
    mtmanapiJNI.TickInfo_bid_set(swigCPtr, this, value);
  }

  public double getBid() {
    return mtmanapiJNI.TickInfo_bid_get(swigCPtr, this);
  }

  public void setAsk(double value) {
    mtmanapiJNI.TickInfo_ask_set(swigCPtr, this, value);
  }

  public double getAsk() {
    return mtmanapiJNI.TickInfo_ask_get(swigCPtr, this);
  }

  public TickInfo() {
    this(mtmanapiJNI.new_TickInfo(), true);
  }

}
