/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ChartInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChartInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChartInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ChartInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.ChartInfo_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.ChartInfo_symbol_get(swigCPtr, this);
  }

  public void setPeriod(int value) {
    mtmanapiJNI.ChartInfo_period_set(swigCPtr, this, value);
  }

  public int getPeriod() {
    return mtmanapiJNI.ChartInfo_period_get(swigCPtr, this);
  }

  public void setStart(int value) {
    mtmanapiJNI.ChartInfo_start_set(swigCPtr, this, value);
  }

  public int getStart() {
    return mtmanapiJNI.ChartInfo_start_get(swigCPtr, this);
  }

  public void setEnd(int value) {
    mtmanapiJNI.ChartInfo_end_set(swigCPtr, this, value);
  }

  public int getEnd() {
    return mtmanapiJNI.ChartInfo_end_get(swigCPtr, this);
  }

  public void setTimesign(int value) {
    mtmanapiJNI.ChartInfo_timesign_set(swigCPtr, this, value);
  }

  public int getTimesign() {
    return mtmanapiJNI.ChartInfo_timesign_get(swigCPtr, this);
  }

  public void setMode(int value) {
    mtmanapiJNI.ChartInfo_mode_set(swigCPtr, this, value);
  }

  public int getMode() {
    return mtmanapiJNI.ChartInfo_mode_get(swigCPtr, this);
  }

  public ChartInfo() {
    this(mtmanapiJNI.new_ChartInfo(), true);
  }

}
