/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConAccess(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConAccess obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConAccess(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAction(int value) {
    mtmanapiJNI.ConAccess_action_set(swigCPtr, this, value);
  }

  public int getAction() {
    return mtmanapiJNI.ConAccess_action_get(swigCPtr, this);
  }

  public void setFrom(long value) {
    mtmanapiJNI.ConAccess_from_set(swigCPtr, this, value);
  }

  public long getFrom() {
    return mtmanapiJNI.ConAccess_from_get(swigCPtr, this);
  }

  public void setTo(long value) {
    mtmanapiJNI.ConAccess_to_set(swigCPtr, this, value);
  }

  public long getTo() {
    return mtmanapiJNI.ConAccess_to_get(swigCPtr, this);
  }

  public void setComment(String value) {
    mtmanapiJNI.ConAccess_comment_set(swigCPtr, this, value);
  }

  public String getComment() {
    return mtmanapiJNI.ConAccess_comment_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConAccess_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConAccess_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConAccess() {
    this(mtmanapiJNI.new_ConAccess(), true);
  }

}
