/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConBackup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConBackup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConBackup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConBackup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFullbackup_path(String value) {
    mtmanapiJNI.ConBackup_fullbackup_path_set(swigCPtr, this, value);
  }

  public String getFullbackup_path() {
    return mtmanapiJNI.ConBackup_fullbackup_path_get(swigCPtr, this);
  }

  public void setFullbackup_period(int value) {
    mtmanapiJNI.ConBackup_fullbackup_period_set(swigCPtr, this, value);
  }

  public int getFullbackup_period() {
    return mtmanapiJNI.ConBackup_fullbackup_period_get(swigCPtr, this);
  }

  public void setFullbackup_store(int value) {
    mtmanapiJNI.ConBackup_fullbackup_store_set(swigCPtr, this, value);
  }

  public int getFullbackup_store() {
    return mtmanapiJNI.ConBackup_fullbackup_store_get(swigCPtr, this);
  }

  public void setFullbackup_lasttime(int value) {
    mtmanapiJNI.ConBackup_fullbackup_lasttime_set(swigCPtr, this, value);
  }

  public int getFullbackup_lasttime() {
    return mtmanapiJNI.ConBackup_fullbackup_lasttime_get(swigCPtr, this);
  }

  public void setFullbackup_shift(short value) {
    mtmanapiJNI.ConBackup_fullbackup_shift_set(swigCPtr, this, value);
  }

  public short getFullbackup_shift() {
    return mtmanapiJNI.ConBackup_fullbackup_shift_get(swigCPtr, this);
  }

  public void setExternal_path(String value) {
    mtmanapiJNI.ConBackup_external_path_set(swigCPtr, this, value);
  }

  public String getExternal_path() {
    return mtmanapiJNI.ConBackup_external_path_get(swigCPtr, this);
  }

  public void setArchive_period(int value) {
    mtmanapiJNI.ConBackup_archive_period_set(swigCPtr, this, value);
  }

  public int getArchive_period() {
    return mtmanapiJNI.ConBackup_archive_period_get(swigCPtr, this);
  }

  public void setArchive_store(int value) {
    mtmanapiJNI.ConBackup_archive_store_set(swigCPtr, this, value);
  }

  public int getArchive_store() {
    return mtmanapiJNI.ConBackup_archive_store_get(swigCPtr, this);
  }

  public void setArchive_lasttime(int value) {
    mtmanapiJNI.ConBackup_archive_lasttime_set(swigCPtr, this, value);
  }

  public int getArchive_lasttime() {
    return mtmanapiJNI.ConBackup_archive_lasttime_get(swigCPtr, this);
  }

  public void setExport_securities(String value) {
    mtmanapiJNI.ConBackup_export_securities_set(swigCPtr, this, value);
  }

  public String getExport_securities() {
    return mtmanapiJNI.ConBackup_export_securities_get(swigCPtr, this);
  }

  public void setExport_path(String value) {
    mtmanapiJNI.ConBackup_export_path_set(swigCPtr, this, value);
  }

  public String getExport_path() {
    return mtmanapiJNI.ConBackup_export_path_get(swigCPtr, this);
  }

  public void setExport_period(int value) {
    mtmanapiJNI.ConBackup_export_period_set(swigCPtr, this, value);
  }

  public int getExport_period() {
    return mtmanapiJNI.ConBackup_export_period_get(swigCPtr, this);
  }

  public void setExport_lasttime(int value) {
    mtmanapiJNI.ConBackup_export_lasttime_set(swigCPtr, this, value);
  }

  public int getExport_lasttime() {
    return mtmanapiJNI.ConBackup_export_lasttime_get(swigCPtr, this);
  }

  public void setWatch_role(int value) {
    mtmanapiJNI.ConBackup_watch_role_set(swigCPtr, this, value);
  }

  public int getWatch_role() {
    return mtmanapiJNI.ConBackup_watch_role_get(swigCPtr, this);
  }

  public void setWatch_password(String value) {
    mtmanapiJNI.ConBackup_watch_password_set(swigCPtr, this, value);
  }

  public String getWatch_password() {
    return mtmanapiJNI.ConBackup_watch_password_get(swigCPtr, this);
  }

  public void setWatch_opposite(String value) {
    mtmanapiJNI.ConBackup_watch_opposite_set(swigCPtr, this, value);
  }

  public String getWatch_opposite() {
    return mtmanapiJNI.ConBackup_watch_opposite_get(swigCPtr, this);
  }

  public void setWatch_ip(int value) {
    mtmanapiJNI.ConBackup_watch_ip_set(swigCPtr, this, value);
  }

  public int getWatch_ip() {
    return mtmanapiJNI.ConBackup_watch_ip_get(swigCPtr, this);
  }

  public void setArchive_shift(char value) {
    mtmanapiJNI.ConBackup_archive_shift_set(swigCPtr, this, value);
  }

  public char getArchive_shift() {
    return mtmanapiJNI.ConBackup_archive_shift_get(swigCPtr, this);
  }

  public void setWatch_state(char value) {
    mtmanapiJNI.ConBackup_watch_state_set(swigCPtr, this, value);
  }

  public char getWatch_state() {
    return mtmanapiJNI.ConBackup_watch_state_get(swigCPtr, this);
  }

  public void setWatch_failover(char value) {
    mtmanapiJNI.ConBackup_watch_failover_set(swigCPtr, this, value);
  }

  public char getWatch_failover() {
    return mtmanapiJNI.ConBackup_watch_failover_get(swigCPtr, this);
  }

  public void setWatch_timeout(short value) {
    mtmanapiJNI.ConBackup_watch_timeout_set(swigCPtr, this, value);
  }

  public short getWatch_timeout() {
    return mtmanapiJNI.ConBackup_watch_timeout_get(swigCPtr, this);
  }

  public void setWatch_login(int value) {
    mtmanapiJNI.ConBackup_watch_login_set(swigCPtr, this, value);
  }

  public int getWatch_login() {
    return mtmanapiJNI.ConBackup_watch_login_get(swigCPtr, this);
  }

  public void setWatch_timestamp(int value) {
    mtmanapiJNI.ConBackup_watch_timestamp_set(swigCPtr, this, value);
  }

  public int getWatch_timestamp() {
    return mtmanapiJNI.ConBackup_watch_timestamp_get(swigCPtr, this);
  }

  public ConBackup() {
    this(mtmanapiJNI.new_ConBackup(), true);
  }

}
