/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConCommon {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConCommon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConCommon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConCommon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOwner(String value) {
    mtmanapiJNI.ConCommon_owner_set(swigCPtr, this, value);
  }

  public String getOwner() {
    return mtmanapiJNI.ConCommon_owner_get(swigCPtr, this);
  }

  public void setName(String value) {
    mtmanapiJNI.ConCommon_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.ConCommon_name_get(swigCPtr, this);
  }

  public void setAddress(long value) {
    mtmanapiJNI.ConCommon_address_set(swigCPtr, this, value);
  }

  public long getAddress() {
    return mtmanapiJNI.ConCommon_address_get(swigCPtr, this);
  }

  public void setPort(int value) {
    mtmanapiJNI.ConCommon_port_set(swigCPtr, this, value);
  }

  public int getPort() {
    return mtmanapiJNI.ConCommon_port_get(swigCPtr, this);
  }

  public void setTimeout(long value) {
    mtmanapiJNI.ConCommon_timeout_set(swigCPtr, this, value);
  }

  public long getTimeout() {
    return mtmanapiJNI.ConCommon_timeout_get(swigCPtr, this);
  }

  public void setTypeofdemo(int value) {
    mtmanapiJNI.ConCommon_typeofdemo_set(swigCPtr, this, value);
  }

  public int getTypeofdemo() {
    return mtmanapiJNI.ConCommon_typeofdemo_get(swigCPtr, this);
  }

  public void setTimeofdemo(int value) {
    mtmanapiJNI.ConCommon_timeofdemo_set(swigCPtr, this, value);
  }

  public int getTimeofdemo() {
    return mtmanapiJNI.ConCommon_timeofdemo_get(swigCPtr, this);
  }

  public void setDaylightcorrection(int value) {
    mtmanapiJNI.ConCommon_daylightcorrection_set(swigCPtr, this, value);
  }

  public int getDaylightcorrection() {
    return mtmanapiJNI.ConCommon_daylightcorrection_get(swigCPtr, this);
  }

  public void setInternal(String value) {
    mtmanapiJNI.ConCommon_internal_set(swigCPtr, this, value);
  }

  public String getInternal() {
    return mtmanapiJNI.ConCommon_internal_get(swigCPtr, this);
  }

  public void setTimezone_real(int value) {
    mtmanapiJNI.ConCommon_timezone_real_set(swigCPtr, this, value);
  }

  public int getTimezone_real() {
    return mtmanapiJNI.ConCommon_timezone_real_get(swigCPtr, this);
  }

  public void setTimezone(int value) {
    mtmanapiJNI.ConCommon_timezone_set(swigCPtr, this, value);
  }

  public int getTimezone() {
    return mtmanapiJNI.ConCommon_timezone_get(swigCPtr, this);
  }

  public void setTimesync(String value) {
    mtmanapiJNI.ConCommon_timesync_set(swigCPtr, this, value);
  }

  public String getTimesync() {
    return mtmanapiJNI.ConCommon_timesync_get(swigCPtr, this);
  }

  public void setMinclient(int value) {
    mtmanapiJNI.ConCommon_minclient_set(swigCPtr, this, value);
  }

  public int getMinclient() {
    return mtmanapiJNI.ConCommon_minclient_get(swigCPtr, this);
  }

  public void setMinapi(int value) {
    mtmanapiJNI.ConCommon_minapi_set(swigCPtr, this, value);
  }

  public int getMinapi() {
    return mtmanapiJNI.ConCommon_minapi_get(swigCPtr, this);
  }

  public void setFeeder_timeout(long value) {
    mtmanapiJNI.ConCommon_feeder_timeout_set(swigCPtr, this, value);
  }

  public long getFeeder_timeout() {
    return mtmanapiJNI.ConCommon_feeder_timeout_get(swigCPtr, this);
  }

  public void setKeepemails(int value) {
    mtmanapiJNI.ConCommon_keepemails_set(swigCPtr, this, value);
  }

  public int getKeepemails() {
    return mtmanapiJNI.ConCommon_keepemails_get(swigCPtr, this);
  }

  public void setEndhour(int value) {
    mtmanapiJNI.ConCommon_endhour_set(swigCPtr, this, value);
  }

  public int getEndhour() {
    return mtmanapiJNI.ConCommon_endhour_get(swigCPtr, this);
  }

  public void setEndminute(int value) {
    mtmanapiJNI.ConCommon_endminute_set(swigCPtr, this, value);
  }

  public int getEndminute() {
    return mtmanapiJNI.ConCommon_endminute_get(swigCPtr, this);
  }

  public void setOptimization_time(int value) {
    mtmanapiJNI.ConCommon_optimization_time_set(swigCPtr, this, value);
  }

  public int getOptimization_time() {
    return mtmanapiJNI.ConCommon_optimization_time_get(swigCPtr, this);
  }

  public void setOptimization_lasttime(int value) {
    mtmanapiJNI.ConCommon_optimization_lasttime_set(swigCPtr, this, value);
  }

  public int getOptimization_lasttime() {
    return mtmanapiJNI.ConCommon_optimization_lasttime_get(swigCPtr, this);
  }

  public void setOptimization_counter(int value) {
    mtmanapiJNI.ConCommon_optimization_counter_set(swigCPtr, this, value);
  }

  public int getOptimization_counter() {
    return mtmanapiJNI.ConCommon_optimization_counter_get(swigCPtr, this);
  }

  public void setOptimization_unused(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConCommon_optimization_unused_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getOptimization_unused() {
    long cPtr = mtmanapiJNI.ConCommon_optimization_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setAntiflood(int value) {
    mtmanapiJNI.ConCommon_antiflood_set(swigCPtr, this, value);
  }

  public int getAntiflood() {
    return mtmanapiJNI.ConCommon_antiflood_get(swigCPtr, this);
  }

  public void setFloodcontrol(int value) {
    mtmanapiJNI.ConCommon_floodcontrol_set(swigCPtr, this, value);
  }

  public int getFloodcontrol() {
    return mtmanapiJNI.ConCommon_floodcontrol_get(swigCPtr, this);
  }

  public void setLiveupdate_mode(int value) {
    mtmanapiJNI.ConCommon_liveupdate_mode_set(swigCPtr, this, value);
  }

  public int getLiveupdate_mode() {
    return mtmanapiJNI.ConCommon_liveupdate_mode_get(swigCPtr, this);
  }

  public void setLastorder(int value) {
    mtmanapiJNI.ConCommon_lastorder_set(swigCPtr, this, value);
  }

  public int getLastorder() {
    return mtmanapiJNI.ConCommon_lastorder_get(swigCPtr, this);
  }

  public void setLastlogin(int value) {
    mtmanapiJNI.ConCommon_lastlogin_set(swigCPtr, this, value);
  }

  public int getLastlogin() {
    return mtmanapiJNI.ConCommon_lastlogin_get(swigCPtr, this);
  }

  public void setLostlogin(int value) {
    mtmanapiJNI.ConCommon_lostlogin_set(swigCPtr, this, value);
  }

  public int getLostlogin() {
    return mtmanapiJNI.ConCommon_lostlogin_get(swigCPtr, this);
  }

  public void setRollovers_mode(int value) {
    mtmanapiJNI.ConCommon_rollovers_mode_set(swigCPtr, this, value);
  }

  public int getRollovers_mode() {
    return mtmanapiJNI.ConCommon_rollovers_mode_get(swigCPtr, this);
  }

  public void setPath_database(String value) {
    mtmanapiJNI.ConCommon_path_database_set(swigCPtr, this, value);
  }

  public String getPath_database() {
    return mtmanapiJNI.ConCommon_path_database_get(swigCPtr, this);
  }

  public void setPath_history(String value) {
    mtmanapiJNI.ConCommon_path_history_set(swigCPtr, this, value);
  }

  public String getPath_history() {
    return mtmanapiJNI.ConCommon_path_history_get(swigCPtr, this);
  }

  public void setPath_log(String value) {
    mtmanapiJNI.ConCommon_path_log_set(swigCPtr, this, value);
  }

  public String getPath_log() {
    return mtmanapiJNI.ConCommon_path_log_get(swigCPtr, this);
  }

  public void setOvernight_last_day(int value) {
    mtmanapiJNI.ConCommon_overnight_last_day_set(swigCPtr, this, value);
  }

  public int getOvernight_last_day() {
    return mtmanapiJNI.ConCommon_overnight_last_day_get(swigCPtr, this);
  }

  public void setOvernight_last_time(int value) {
    mtmanapiJNI.ConCommon_overnight_last_time_set(swigCPtr, this, value);
  }

  public int getOvernight_last_time() {
    return mtmanapiJNI.ConCommon_overnight_last_time_get(swigCPtr, this);
  }

  public void setOvernight_prev_time(int value) {
    mtmanapiJNI.ConCommon_overnight_prev_time_set(swigCPtr, this, value);
  }

  public int getOvernight_prev_time() {
    return mtmanapiJNI.ConCommon_overnight_prev_time_get(swigCPtr, this);
  }

  public void setOvermonth_last_month(int value) {
    mtmanapiJNI.ConCommon_overmonth_last_month_set(swigCPtr, this, value);
  }

  public int getOvermonth_last_month() {
    return mtmanapiJNI.ConCommon_overmonth_last_month_get(swigCPtr, this);
  }

  public void setAdapters(String value) {
    mtmanapiJNI.ConCommon_adapters_set(swigCPtr, this, value);
  }

  public String getAdapters() {
    return mtmanapiJNI.ConCommon_adapters_get(swigCPtr, this);
  }

  public void setBind_adresses(SWIGTYPE_p_unsigned_long value) {
    mtmanapiJNI.ConCommon_bind_adresses_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getBind_adresses() {
    long cPtr = mtmanapiJNI.ConCommon_bind_adresses_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setServer_version(short value) {
    mtmanapiJNI.ConCommon_server_version_set(swigCPtr, this, value);
  }

  public short getServer_version() {
    return mtmanapiJNI.ConCommon_server_version_get(swigCPtr, this);
  }

  public void setServer_build(short value) {
    mtmanapiJNI.ConCommon_server_build_set(swigCPtr, this, value);
  }

  public short getServer_build() {
    return mtmanapiJNI.ConCommon_server_build_get(swigCPtr, this);
  }

  public void setWeb_adresses(SWIGTYPE_p_unsigned_long value) {
    mtmanapiJNI.ConCommon_web_adresses_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getWeb_adresses() {
    long cPtr = mtmanapiJNI.ConCommon_web_adresses_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setStatement_mode(int value) {
    mtmanapiJNI.ConCommon_statement_mode_set(swigCPtr, this, value);
  }

  public int getStatement_mode() {
    return mtmanapiJNI.ConCommon_statement_mode_get(swigCPtr, this);
  }

  public void setMonthly_state_mode(int value) {
    mtmanapiJNI.ConCommon_monthly_state_mode_set(swigCPtr, this, value);
  }

  public int getMonthly_state_mode() {
    return mtmanapiJNI.ConCommon_monthly_state_mode_get(swigCPtr, this);
  }

  public void setKeepticks(int value) {
    mtmanapiJNI.ConCommon_keepticks_set(swigCPtr, this, value);
  }

  public int getKeepticks() {
    return mtmanapiJNI.ConCommon_keepticks_get(swigCPtr, this);
  }

  public void setStatement_weekend(int value) {
    mtmanapiJNI.ConCommon_statement_weekend_set(swigCPtr, this, value);
  }

  public int getStatement_weekend() {
    return mtmanapiJNI.ConCommon_statement_weekend_get(swigCPtr, this);
  }

  public void setLast_activate(int value) {
    mtmanapiJNI.ConCommon_last_activate_set(swigCPtr, this, value);
  }

  public int getLast_activate() {
    return mtmanapiJNI.ConCommon_last_activate_get(swigCPtr, this);
  }

  public void setStop_last(int value) {
    mtmanapiJNI.ConCommon_stop_last_set(swigCPtr, this, value);
  }

  public int getStop_last() {
    return mtmanapiJNI.ConCommon_stop_last_get(swigCPtr, this);
  }

  public void setStop_delay(int value) {
    mtmanapiJNI.ConCommon_stop_delay_set(swigCPtr, this, value);
  }

  public int getStop_delay() {
    return mtmanapiJNI.ConCommon_stop_delay_get(swigCPtr, this);
  }

  public void setStop_reason(int value) {
    mtmanapiJNI.ConCommon_stop_reason_set(swigCPtr, this, value);
  }

  public int getStop_reason() {
    return mtmanapiJNI.ConCommon_stop_reason_get(swigCPtr, this);
  }

  public void setAccount_url(String value) {
    mtmanapiJNI.ConCommon_account_url_set(swigCPtr, this, value);
  }

  public String getAccount_url() {
    return mtmanapiJNI.ConCommon_account_url_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConCommon_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConCommon_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConCommon() {
    this(mtmanapiJNI.new_ConCommon(), true);
  }

}
