/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConDataServer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConDataServer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConDataServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConDataServer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setServer(String value) {
    mtmanapiJNI.ConDataServer_server_set(swigCPtr, this, value);
  }

  public String getServer() {
    return mtmanapiJNI.ConDataServer_server_get(swigCPtr, this);
  }

  public void setIp(long value) {
    mtmanapiJNI.ConDataServer_ip_set(swigCPtr, this, value);
  }

  public long getIp() {
    return mtmanapiJNI.ConDataServer_ip_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    mtmanapiJNI.ConDataServer_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return mtmanapiJNI.ConDataServer_description_get(swigCPtr, this);
  }

  public void setIsproxy(int value) {
    mtmanapiJNI.ConDataServer_isproxy_set(swigCPtr, this, value);
  }

  public int getIsproxy() {
    return mtmanapiJNI.ConDataServer_isproxy_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    mtmanapiJNI.ConDataServer_priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return mtmanapiJNI.ConDataServer_priority_get(swigCPtr, this);
  }

  public void setLoading(long value) {
    mtmanapiJNI.ConDataServer_loading_set(swigCPtr, this, value);
  }

  public long getLoading() {
    return mtmanapiJNI.ConDataServer_loading_get(swigCPtr, this);
  }

  public void setIp_internal(long value) {
    mtmanapiJNI.ConDataServer_ip_internal_set(swigCPtr, this, value);
  }

  public long getIp_internal() {
    return mtmanapiJNI.ConDataServer_ip_internal_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConDataServer_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConDataServer_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNext(ConDataServer value) {
    mtmanapiJNI.ConDataServer_next_set(swigCPtr, this, ConDataServer.getCPtr(value), value);
  }

  public ConDataServer getNext() {
    long cPtr = mtmanapiJNI.ConDataServer_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConDataServer(cPtr, false);
  }

  public ConDataServer() {
    this(mtmanapiJNI.new_ConDataServer(), true);
  }

}
