/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConGroupMargin {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConGroupMargin(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConGroupMargin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConGroupMargin(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.ConGroupMargin_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.ConGroupMargin_symbol_get(swigCPtr, this);
  }

  public void setSwap_long(double value) {
    mtmanapiJNI.ConGroupMargin_swap_long_set(swigCPtr, this, value);
  }

  public double getSwap_long() {
    return mtmanapiJNI.ConGroupMargin_swap_long_get(swigCPtr, this);
  }

  public void setSwap_short(double value) {
    mtmanapiJNI.ConGroupMargin_swap_short_set(swigCPtr, this, value);
  }

  public double getSwap_short() {
    return mtmanapiJNI.ConGroupMargin_swap_short_get(swigCPtr, this);
  }

  public void setMargin_divider(double value) {
    mtmanapiJNI.ConGroupMargin_margin_divider_set(swigCPtr, this, value);
  }

  public double getMargin_divider() {
    return mtmanapiJNI.ConGroupMargin_margin_divider_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConGroupMargin_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConGroupMargin_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConGroupMargin() {
    this(mtmanapiJNI.new_ConGroupMargin(), true);
  }

}
