/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConSessions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConSessions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConSessions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConSessions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuote(ConSession value) {
    mtmanapiJNI.ConSessions_quote_set(swigCPtr, this, ConSession.getCPtr(value), value);
  }

  public ConSession getQuote() {
    long cPtr = mtmanapiJNI.ConSessions_quote_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConSession(cPtr, false);
  }

  public void setTrade(ConSession value) {
    mtmanapiJNI.ConSessions_trade_set(swigCPtr, this, ConSession.getCPtr(value), value);
  }

  public ConSession getTrade() {
    long cPtr = mtmanapiJNI.ConSessions_trade_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConSession(cPtr, false);
  }

  public void setQuote_overnight(int value) {
    mtmanapiJNI.ConSessions_quote_overnight_set(swigCPtr, this, value);
  }

  public int getQuote_overnight() {
    return mtmanapiJNI.ConSessions_quote_overnight_get(swigCPtr, this);
  }

  public void setTrade_overnight(int value) {
    mtmanapiJNI.ConSessions_trade_overnight_set(swigCPtr, this, value);
  }

  public int getTrade_overnight() {
    return mtmanapiJNI.ConSessions_trade_overnight_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConSessions_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.ConSessions_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConSessions() {
    this(mtmanapiJNI.new_ConSessions(), true);
  }

}
