/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ConSymbol {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConSymbol(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConSymbol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ConSymbol(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.ConSymbol_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.ConSymbol_symbol_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    mtmanapiJNI.ConSymbol_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return mtmanapiJNI.ConSymbol_description_get(swigCPtr, this);
  }

  public void setSource(String value) {
    mtmanapiJNI.ConSymbol_source_set(swigCPtr, this, value);
  }

  public String getSource() {
    return mtmanapiJNI.ConSymbol_source_get(swigCPtr, this);
  }

  public void setCurrency(String value) {
    mtmanapiJNI.ConSymbol_currency_set(swigCPtr, this, value);
  }

  public String getCurrency() {
    return mtmanapiJNI.ConSymbol_currency_get(swigCPtr, this);
  }

  public void setType(int value) {
    mtmanapiJNI.ConSymbol_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mtmanapiJNI.ConSymbol_type_get(swigCPtr, this);
  }

  public void setDigits(int value) {
    mtmanapiJNI.ConSymbol_digits_set(swigCPtr, this, value);
  }

  public int getDigits() {
    return mtmanapiJNI.ConSymbol_digits_get(swigCPtr, this);
  }

  public void setTrade(int value) {
    mtmanapiJNI.ConSymbol_trade_set(swigCPtr, this, value);
  }

  public int getTrade() {
    return mtmanapiJNI.ConSymbol_trade_get(swigCPtr, this);
  }

  public void setBackground_color(SWIGTYPE_p_COLORREF value) {
    mtmanapiJNI.ConSymbol_background_color_set(swigCPtr, this, SWIGTYPE_p_COLORREF.getCPtr(value));
  }

  public SWIGTYPE_p_COLORREF getBackground_color() {
    return new SWIGTYPE_p_COLORREF(mtmanapiJNI.ConSymbol_background_color_get(swigCPtr, this), true);
  }

  public void setCount(int value) {
    mtmanapiJNI.ConSymbol_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return mtmanapiJNI.ConSymbol_count_get(swigCPtr, this);
  }

  public void setCount_original(int value) {
    mtmanapiJNI.ConSymbol_count_original_set(swigCPtr, this, value);
  }

  public int getCount_original() {
    return mtmanapiJNI.ConSymbol_count_original_get(swigCPtr, this);
  }

  public void setExternal_unused(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConSymbol_external_unused_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getExternal_unused() {
    long cPtr = mtmanapiJNI.ConSymbol_external_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setRealtime(int value) {
    mtmanapiJNI.ConSymbol_realtime_set(swigCPtr, this, value);
  }

  public int getRealtime() {
    return mtmanapiJNI.ConSymbol_realtime_get(swigCPtr, this);
  }

  public void setStarting(int value) {
    mtmanapiJNI.ConSymbol_starting_set(swigCPtr, this, value);
  }

  public int getStarting() {
    return mtmanapiJNI.ConSymbol_starting_get(swigCPtr, this);
  }

  public void setExpiration(int value) {
    mtmanapiJNI.ConSymbol_expiration_set(swigCPtr, this, value);
  }

  public int getExpiration() {
    return mtmanapiJNI.ConSymbol_expiration_get(swigCPtr, this);
  }

  public void setSessions(ConSessions value) {
    mtmanapiJNI.ConSymbol_sessions_set(swigCPtr, this, ConSessions.getCPtr(value), value);
  }

  public ConSessions getSessions() {
    long cPtr = mtmanapiJNI.ConSymbol_sessions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConSessions(cPtr, false);
  }

  public void setProfit_mode(int value) {
    mtmanapiJNI.ConSymbol_profit_mode_set(swigCPtr, this, value);
  }

  public int getProfit_mode() {
    return mtmanapiJNI.ConSymbol_profit_mode_get(swigCPtr, this);
  }

  public void setProfit_reserved(int value) {
    mtmanapiJNI.ConSymbol_profit_reserved_set(swigCPtr, this, value);
  }

  public int getProfit_reserved() {
    return mtmanapiJNI.ConSymbol_profit_reserved_get(swigCPtr, this);
  }

  public void setFilter(int value) {
    mtmanapiJNI.ConSymbol_filter_set(swigCPtr, this, value);
  }

  public int getFilter() {
    return mtmanapiJNI.ConSymbol_filter_get(swigCPtr, this);
  }

  public void setFilter_counter(int value) {
    mtmanapiJNI.ConSymbol_filter_counter_set(swigCPtr, this, value);
  }

  public int getFilter_counter() {
    return mtmanapiJNI.ConSymbol_filter_counter_get(swigCPtr, this);
  }

  public void setFilter_limit(double value) {
    mtmanapiJNI.ConSymbol_filter_limit_set(swigCPtr, this, value);
  }

  public double getFilter_limit() {
    return mtmanapiJNI.ConSymbol_filter_limit_get(swigCPtr, this);
  }

  public void setFilter_smoothing(int value) {
    mtmanapiJNI.ConSymbol_filter_smoothing_set(swigCPtr, this, value);
  }

  public int getFilter_smoothing() {
    return mtmanapiJNI.ConSymbol_filter_smoothing_get(swigCPtr, this);
  }

  public void setFilter_reserved(float value) {
    mtmanapiJNI.ConSymbol_filter_reserved_set(swigCPtr, this, value);
  }

  public float getFilter_reserved() {
    return mtmanapiJNI.ConSymbol_filter_reserved_get(swigCPtr, this);
  }

  public void setLogging(int value) {
    mtmanapiJNI.ConSymbol_logging_set(swigCPtr, this, value);
  }

  public int getLogging() {
    return mtmanapiJNI.ConSymbol_logging_get(swigCPtr, this);
  }

  public void setSpread(int value) {
    mtmanapiJNI.ConSymbol_spread_set(swigCPtr, this, value);
  }

  public int getSpread() {
    return mtmanapiJNI.ConSymbol_spread_get(swigCPtr, this);
  }

  public void setSpread_balance(int value) {
    mtmanapiJNI.ConSymbol_spread_balance_set(swigCPtr, this, value);
  }

  public int getSpread_balance() {
    return mtmanapiJNI.ConSymbol_spread_balance_get(swigCPtr, this);
  }

  public void setExemode(int value) {
    mtmanapiJNI.ConSymbol_exemode_set(swigCPtr, this, value);
  }

  public int getExemode() {
    return mtmanapiJNI.ConSymbol_exemode_get(swigCPtr, this);
  }

  public void setSwap_enable(int value) {
    mtmanapiJNI.ConSymbol_swap_enable_set(swigCPtr, this, value);
  }

  public int getSwap_enable() {
    return mtmanapiJNI.ConSymbol_swap_enable_get(swigCPtr, this);
  }

  public void setSwap_type(int value) {
    mtmanapiJNI.ConSymbol_swap_type_set(swigCPtr, this, value);
  }

  public int getSwap_type() {
    return mtmanapiJNI.ConSymbol_swap_type_get(swigCPtr, this);
  }

  public void setSwap_long(double value) {
    mtmanapiJNI.ConSymbol_swap_long_set(swigCPtr, this, value);
  }

  public double getSwap_long() {
    return mtmanapiJNI.ConSymbol_swap_long_get(swigCPtr, this);
  }

  public void setSwap_short(double value) {
    mtmanapiJNI.ConSymbol_swap_short_set(swigCPtr, this, value);
  }

  public double getSwap_short() {
    return mtmanapiJNI.ConSymbol_swap_short_get(swigCPtr, this);
  }

  public void setSwap_rollover3days(int value) {
    mtmanapiJNI.ConSymbol_swap_rollover3days_set(swigCPtr, this, value);
  }

  public int getSwap_rollover3days() {
    return mtmanapiJNI.ConSymbol_swap_rollover3days_get(swigCPtr, this);
  }

  public void setContract_size(double value) {
    mtmanapiJNI.ConSymbol_contract_size_set(swigCPtr, this, value);
  }

  public double getContract_size() {
    return mtmanapiJNI.ConSymbol_contract_size_get(swigCPtr, this);
  }

  public void setTick_value(double value) {
    mtmanapiJNI.ConSymbol_tick_value_set(swigCPtr, this, value);
  }

  public double getTick_value() {
    return mtmanapiJNI.ConSymbol_tick_value_get(swigCPtr, this);
  }

  public void setTick_size(double value) {
    mtmanapiJNI.ConSymbol_tick_size_set(swigCPtr, this, value);
  }

  public double getTick_size() {
    return mtmanapiJNI.ConSymbol_tick_size_get(swigCPtr, this);
  }

  public void setStops_level(int value) {
    mtmanapiJNI.ConSymbol_stops_level_set(swigCPtr, this, value);
  }

  public int getStops_level() {
    return mtmanapiJNI.ConSymbol_stops_level_get(swigCPtr, this);
  }

  public void setGtc_pendings(int value) {
    mtmanapiJNI.ConSymbol_gtc_pendings_set(swigCPtr, this, value);
  }

  public int getGtc_pendings() {
    return mtmanapiJNI.ConSymbol_gtc_pendings_get(swigCPtr, this);
  }

  public void setMargin_mode(int value) {
    mtmanapiJNI.ConSymbol_margin_mode_set(swigCPtr, this, value);
  }

  public int getMargin_mode() {
    return mtmanapiJNI.ConSymbol_margin_mode_get(swigCPtr, this);
  }

  public void setMargin_initial(double value) {
    mtmanapiJNI.ConSymbol_margin_initial_set(swigCPtr, this, value);
  }

  public double getMargin_initial() {
    return mtmanapiJNI.ConSymbol_margin_initial_get(swigCPtr, this);
  }

  public void setMargin_maintenance(double value) {
    mtmanapiJNI.ConSymbol_margin_maintenance_set(swigCPtr, this, value);
  }

  public double getMargin_maintenance() {
    return mtmanapiJNI.ConSymbol_margin_maintenance_get(swigCPtr, this);
  }

  public void setMargin_hedged(double value) {
    mtmanapiJNI.ConSymbol_margin_hedged_set(swigCPtr, this, value);
  }

  public double getMargin_hedged() {
    return mtmanapiJNI.ConSymbol_margin_hedged_get(swigCPtr, this);
  }

  public void setMargin_divider(double value) {
    mtmanapiJNI.ConSymbol_margin_divider_set(swigCPtr, this, value);
  }

  public double getMargin_divider() {
    return mtmanapiJNI.ConSymbol_margin_divider_get(swigCPtr, this);
  }

  public void setPoint(double value) {
    mtmanapiJNI.ConSymbol_point_set(swigCPtr, this, value);
  }

  public double getPoint() {
    return mtmanapiJNI.ConSymbol_point_get(swigCPtr, this);
  }

  public void setMultiply(double value) {
    mtmanapiJNI.ConSymbol_multiply_set(swigCPtr, this, value);
  }

  public double getMultiply() {
    return mtmanapiJNI.ConSymbol_multiply_get(swigCPtr, this);
  }

  public void setBid_tickvalue(double value) {
    mtmanapiJNI.ConSymbol_bid_tickvalue_set(swigCPtr, this, value);
  }

  public double getBid_tickvalue() {
    return mtmanapiJNI.ConSymbol_bid_tickvalue_get(swigCPtr, this);
  }

  public void setAsk_tickvalue(double value) {
    mtmanapiJNI.ConSymbol_ask_tickvalue_set(swigCPtr, this, value);
  }

  public double getAsk_tickvalue() {
    return mtmanapiJNI.ConSymbol_ask_tickvalue_get(swigCPtr, this);
  }

  public void setLong_only(int value) {
    mtmanapiJNI.ConSymbol_long_only_set(swigCPtr, this, value);
  }

  public int getLong_only() {
    return mtmanapiJNI.ConSymbol_long_only_get(swigCPtr, this);
  }

  public void setInstant_max_volume(int value) {
    mtmanapiJNI.ConSymbol_instant_max_volume_set(swigCPtr, this, value);
  }

  public int getInstant_max_volume() {
    return mtmanapiJNI.ConSymbol_instant_max_volume_get(swigCPtr, this);
  }

  public void setMargin_currency(String value) {
    mtmanapiJNI.ConSymbol_margin_currency_set(swigCPtr, this, value);
  }

  public String getMargin_currency() {
    return mtmanapiJNI.ConSymbol_margin_currency_get(swigCPtr, this);
  }

  public void setFreeze_level(int value) {
    mtmanapiJNI.ConSymbol_freeze_level_set(swigCPtr, this, value);
  }

  public int getFreeze_level() {
    return mtmanapiJNI.ConSymbol_freeze_level_get(swigCPtr, this);
  }

  public void setMargin_hedged_strong(int value) {
    mtmanapiJNI.ConSymbol_margin_hedged_strong_set(swigCPtr, this, value);
  }

  public int getMargin_hedged_strong() {
    return mtmanapiJNI.ConSymbol_margin_hedged_strong_get(swigCPtr, this);
  }

  public void setValue_date(int value) {
    mtmanapiJNI.ConSymbol_value_date_set(swigCPtr, this, value);
  }

  public int getValue_date() {
    return mtmanapiJNI.ConSymbol_value_date_get(swigCPtr, this);
  }

  public void setQuotes_delay(int value) {
    mtmanapiJNI.ConSymbol_quotes_delay_set(swigCPtr, this, value);
  }

  public int getQuotes_delay() {
    return mtmanapiJNI.ConSymbol_quotes_delay_get(swigCPtr, this);
  }

  public void setSwap_openprice(int value) {
    mtmanapiJNI.ConSymbol_swap_openprice_set(swigCPtr, this, value);
  }

  public int getSwap_openprice() {
    return mtmanapiJNI.ConSymbol_swap_openprice_get(swigCPtr, this);
  }

  public void setSwap_variation_margin(int value) {
    mtmanapiJNI.ConSymbol_swap_variation_margin_set(swigCPtr, this, value);
  }

  public int getSwap_variation_margin() {
    return mtmanapiJNI.ConSymbol_swap_variation_margin_get(swigCPtr, this);
  }

  public void setUnused(SWIGTYPE_p_int value) {
    mtmanapiJNI.ConSymbol_unused_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getUnused() {
    long cPtr = mtmanapiJNI.ConSymbol_unused_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public ConSymbol() {
    this(mtmanapiJNI.new_ConSymbol(), true);
  }

}
