/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public final class EnErrLogTypes {
  public final static EnErrLogTypes CmdOK = new EnErrLogTypes("CmdOK");
  public final static EnErrLogTypes CmdTrade = new EnErrLogTypes("CmdTrade");
  public final static EnErrLogTypes CmdLogin = new EnErrLogTypes("CmdLogin");
  public final static EnErrLogTypes CmdWarn = new EnErrLogTypes("CmdWarn");
  public final static EnErrLogTypes CmdErr = new EnErrLogTypes("CmdErr");
  public final static EnErrLogTypes CmdAtt = new EnErrLogTypes("CmdAtt");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EnErrLogTypes swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EnErrLogTypes.class + " with value " + swigValue);
  }

  private EnErrLogTypes(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EnErrLogTypes(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EnErrLogTypes(String swigName, EnErrLogTypes swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EnErrLogTypes[] swigValues = { CmdOK, CmdTrade, CmdLogin, CmdWarn, CmdErr, CmdAtt };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

