/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public final class EnLogType {
  public final static EnLogType LOG_TYPE_STANDARD = new EnLogType("LOG_TYPE_STANDARD", mtmanapiJNI.LOG_TYPE_STANDARD_get());
  public final static EnLogType LOG_TYPE_LOGINS = new EnLogType("LOG_TYPE_LOGINS", mtmanapiJNI.LOG_TYPE_LOGINS_get());
  public final static EnLogType LOG_TYPE_TRADES = new EnLogType("LOG_TYPE_TRADES", mtmanapiJNI.LOG_TYPE_TRADES_get());
  public final static EnLogType LOG_TYPE_ERRORS = new EnLogType("LOG_TYPE_ERRORS", mtmanapiJNI.LOG_TYPE_ERRORS_get());
  public final static EnLogType LOG_TYPE_FULL = new EnLogType("LOG_TYPE_FULL", mtmanapiJNI.LOG_TYPE_FULL_get());
  public final static EnLogType LOG_TYPE_UPDATER = new EnLogType("LOG_TYPE_UPDATER", mtmanapiJNI.LOG_TYPE_UPDATER_get());
  public final static EnLogType LOG_TYPE_SENDMAIL = new EnLogType("LOG_TYPE_SENDMAIL", mtmanapiJNI.LOG_TYPE_SENDMAIL_get());
  public final static EnLogType LOG_TYPE_FAILOVER = new EnLogType("LOG_TYPE_FAILOVER", mtmanapiJNI.LOG_TYPE_FAILOVER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EnLogType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EnLogType.class + " with value " + swigValue);
  }

  private EnLogType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EnLogType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EnLogType(String swigName, EnLogType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EnLogType[] swigValues = { LOG_TYPE_STANDARD, LOG_TYPE_LOGINS, LOG_TYPE_TRADES, LOG_TYPE_ERRORS, LOG_TYPE_FULL, LOG_TYPE_UPDATER, LOG_TYPE_SENDMAIL, LOG_TYPE_FAILOVER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

