/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class MarginLevel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MarginLevel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MarginLevel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_MarginLevel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLogin(int value) {
    mtmanapiJNI.MarginLevel_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.MarginLevel_login_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    mtmanapiJNI.MarginLevel_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mtmanapiJNI.MarginLevel_group_get(swigCPtr, this);
  }

  public void setLeverage(int value) {
    mtmanapiJNI.MarginLevel_leverage_set(swigCPtr, this, value);
  }

  public int getLeverage() {
    return mtmanapiJNI.MarginLevel_leverage_get(swigCPtr, this);
  }

  public void setUpdated(int value) {
    mtmanapiJNI.MarginLevel_updated_set(swigCPtr, this, value);
  }

  public int getUpdated() {
    return mtmanapiJNI.MarginLevel_updated_get(swigCPtr, this);
  }

  public void setBalance(double value) {
    mtmanapiJNI.MarginLevel_balance_set(swigCPtr, this, value);
  }

  public double getBalance() {
    return mtmanapiJNI.MarginLevel_balance_get(swigCPtr, this);
  }

  public void setEquity(double value) {
    mtmanapiJNI.MarginLevel_equity_set(swigCPtr, this, value);
  }

  public double getEquity() {
    return mtmanapiJNI.MarginLevel_equity_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    mtmanapiJNI.MarginLevel_volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return mtmanapiJNI.MarginLevel_volume_get(swigCPtr, this);
  }

  public void setMargin(double value) {
    mtmanapiJNI.MarginLevel_margin_set(swigCPtr, this, value);
  }

  public double getMargin() {
    return mtmanapiJNI.MarginLevel_margin_get(swigCPtr, this);
  }

  public void setMargin_free(double value) {
    mtmanapiJNI.MarginLevel_margin_free_set(swigCPtr, this, value);
  }

  public double getMargin_free() {
    return mtmanapiJNI.MarginLevel_margin_free_get(swigCPtr, this);
  }

  public void setMargin_level(double value) {
    mtmanapiJNI.MarginLevel_margin_level_set(swigCPtr, this, value);
  }

  public double getMargin_level() {
    return mtmanapiJNI.MarginLevel_margin_level_get(swigCPtr, this);
  }

  public void setMargin_type(int value) {
    mtmanapiJNI.MarginLevel_margin_type_set(swigCPtr, this, value);
  }

  public int getMargin_type() {
    return mtmanapiJNI.MarginLevel_margin_type_get(swigCPtr, this);
  }

  public void setLevel_type(int value) {
    mtmanapiJNI.MarginLevel_level_type_set(swigCPtr, this, value);
  }

  public int getLevel_type() {
    return mtmanapiJNI.MarginLevel_level_type_get(swigCPtr, this);
  }

  public MarginLevel() {
    this(mtmanapiJNI.new_MarginLevel(), true);
  }

}
