/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class mtmanapi implements mtmanapiConstants {
  public static SWIGTYPE_p_ConGroup new_ConGroupArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConGroupArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ConGroup(cPtr, false);
  }

  public static void delete_ConGroupArray(SWIGTYPE_p_ConGroup ary) {
    mtmanapiJNI.delete_ConGroupArray(SWIGTYPE_p_ConGroup.getCPtr(ary));
  }

  public static SWIGTYPE_p_ConGroup ConGroupArray_getitem(SWIGTYPE_p_ConGroup ary, int index) {
    return new SWIGTYPE_p_ConGroup(mtmanapiJNI.ConGroupArray_getitem(SWIGTYPE_p_ConGroup.getCPtr(ary), index), true);
  }

  public static void ConGroupArray_setitem(SWIGTYPE_p_ConGroup ary, int index, SWIGTYPE_p_ConGroup value) {
    mtmanapiJNI.ConGroupArray_setitem(SWIGTYPE_p_ConGroup.getCPtr(ary), index, SWIGTYPE_p_ConGroup.getCPtr(value));
  }

  public static SWIGTYPE_p_ConGroupSec new_ConGroupSecArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConGroupSecArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ConGroupSec(cPtr, false);
  }

  public static void delete_ConGroupSecArray(SWIGTYPE_p_ConGroupSec ary) {
    mtmanapiJNI.delete_ConGroupSecArray(SWIGTYPE_p_ConGroupSec.getCPtr(ary));
  }

  public static SWIGTYPE_p_ConGroupSec ConGroupSecArray_getitem(SWIGTYPE_p_ConGroupSec ary, int index) {
    return new SWIGTYPE_p_ConGroupSec(mtmanapiJNI.ConGroupSecArray_getitem(SWIGTYPE_p_ConGroupSec.getCPtr(ary), index), true);
  }

  public static void ConGroupSecArray_setitem(SWIGTYPE_p_ConGroupSec ary, int index, SWIGTYPE_p_ConGroupSec value) {
    mtmanapiJNI.ConGroupSecArray_setitem(SWIGTYPE_p_ConGroupSec.getCPtr(ary), index, SWIGTYPE_p_ConGroupSec.getCPtr(value));
  }

  public static SWIGTYPE_p_UserRecord new_UserRecordArray(int nelements) {
    long cPtr = mtmanapiJNI.new_UserRecordArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_UserRecord(cPtr, false);
  }

  public static void delete_UserRecordArray(SWIGTYPE_p_UserRecord ary) {
    mtmanapiJNI.delete_UserRecordArray(SWIGTYPE_p_UserRecord.getCPtr(ary));
  }

  public static SWIGTYPE_p_UserRecord UserRecordArray_getitem(SWIGTYPE_p_UserRecord ary, int index) {
    return new SWIGTYPE_p_UserRecord(mtmanapiJNI.UserRecordArray_getitem(SWIGTYPE_p_UserRecord.getCPtr(ary), index), true);
  }

  public static void UserRecordArray_setitem(SWIGTYPE_p_UserRecord ary, int index, SWIGTYPE_p_UserRecord value) {
    mtmanapiJNI.UserRecordArray_setitem(SWIGTYPE_p_UserRecord.getCPtr(ary), index, SWIGTYPE_p_UserRecord.getCPtr(value));
  }

  public static SWIGTYPE_p_TradeRecord new_TradeRecordArray(int nelements) {
    long cPtr = mtmanapiJNI.new_TradeRecordArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TradeRecord(cPtr, false);
  }

  public static void delete_TradeRecordArray(SWIGTYPE_p_TradeRecord ary) {
    mtmanapiJNI.delete_TradeRecordArray(SWIGTYPE_p_TradeRecord.getCPtr(ary));
  }

  public static SWIGTYPE_p_TradeRecord TradeRecordArray_getitem(SWIGTYPE_p_TradeRecord ary, int index) {
    return new SWIGTYPE_p_TradeRecord(mtmanapiJNI.TradeRecordArray_getitem(SWIGTYPE_p_TradeRecord.getCPtr(ary), index), true);
  }

  public static void TradeRecordArray_setitem(SWIGTYPE_p_TradeRecord ary, int index, SWIGTYPE_p_TradeRecord value) {
    mtmanapiJNI.TradeRecordArray_setitem(SWIGTYPE_p_TradeRecord.getCPtr(ary), index, SWIGTYPE_p_TradeRecord.getCPtr(value));
  }

  public static SWIGTYPE_p_ConSymbol new_ConSymbolArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConSymbolArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ConSymbol(cPtr, false);
  }

  public static void delete_ConSymbolArray(SWIGTYPE_p_ConSymbol ary) {
    mtmanapiJNI.delete_ConSymbolArray(SWIGTYPE_p_ConSymbol.getCPtr(ary));
  }

  public static SWIGTYPE_p_ConSymbol ConSymbolArray_getitem(SWIGTYPE_p_ConSymbol ary, int index) {
    return new SWIGTYPE_p_ConSymbol(mtmanapiJNI.ConSymbolArray_getitem(SWIGTYPE_p_ConSymbol.getCPtr(ary), index), true);
  }

  public static void ConSymbolArray_setitem(SWIGTYPE_p_ConSymbol ary, int index, SWIGTYPE_p_ConSymbol value) {
    mtmanapiJNI.ConSymbolArray_setitem(SWIGTYPE_p_ConSymbol.getCPtr(ary), index, SWIGTYPE_p_ConSymbol.getCPtr(value));
  }

  public static SWIGTYPE_p_SymbolInfo new_SymbolInfoArray(int nelements) {
    long cPtr = mtmanapiJNI.new_SymbolInfoArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SymbolInfo(cPtr, false);
  }

  public static void delete_SymbolInfoArray(SWIGTYPE_p_SymbolInfo ary) {
    mtmanapiJNI.delete_SymbolInfoArray(SWIGTYPE_p_SymbolInfo.getCPtr(ary));
  }

  public static SWIGTYPE_p_SymbolInfo SymbolInfoArray_getitem(SWIGTYPE_p_SymbolInfo ary, int index) {
    return new SWIGTYPE_p_SymbolInfo(mtmanapiJNI.SymbolInfoArray_getitem(SWIGTYPE_p_SymbolInfo.getCPtr(ary), index), true);
  }

  public static void SymbolInfoArray_setitem(SWIGTYPE_p_SymbolInfo ary, int index, SWIGTYPE_p_SymbolInfo value) {
    mtmanapiJNI.SymbolInfoArray_setitem(SWIGTYPE_p_SymbolInfo.getCPtr(ary), index, SWIGTYPE_p_SymbolInfo.getCPtr(value));
  }

  public static SWIGTYPE_p_RateInfo new_RateInfoArray(int nelements) {
    long cPtr = mtmanapiJNI.new_RateInfoArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_RateInfo(cPtr, false);
  }

  public static void delete_RateInfoArray(SWIGTYPE_p_RateInfo ary) {
    mtmanapiJNI.delete_RateInfoArray(SWIGTYPE_p_RateInfo.getCPtr(ary));
  }

  public static SWIGTYPE_p_RateInfo RateInfoArray_getitem(SWIGTYPE_p_RateInfo ary, int index) {
    return new SWIGTYPE_p_RateInfo(mtmanapiJNI.RateInfoArray_getitem(SWIGTYPE_p_RateInfo.getCPtr(ary), index), true);
  }

  public static void RateInfoArray_setitem(SWIGTYPE_p_RateInfo ary, int index, SWIGTYPE_p_RateInfo value) {
    mtmanapiJNI.RateInfoArray_setitem(SWIGTYPE_p_RateInfo.getCPtr(ary), index, SWIGTYPE_p_RateInfo.getCPtr(value));
  }

  public static SWIGTYPE_p_TickInfo new_TickInfoArray(int nelements) {
    long cPtr = mtmanapiJNI.new_TickInfoArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TickInfo(cPtr, false);
  }

  public static void delete_TickInfoArray(SWIGTYPE_p_TickInfo ary) {
    mtmanapiJNI.delete_TickInfoArray(SWIGTYPE_p_TickInfo.getCPtr(ary));
  }

  public static SWIGTYPE_p_TickInfo TickInfoArray_getitem(SWIGTYPE_p_TickInfo ary, int index) {
    return new SWIGTYPE_p_TickInfo(mtmanapiJNI.TickInfoArray_getitem(SWIGTYPE_p_TickInfo.getCPtr(ary), index), true);
  }

  public static void TickInfoArray_setitem(SWIGTYPE_p_TickInfo ary, int index, SWIGTYPE_p_TickInfo value) {
    mtmanapiJNI.TickInfoArray_setitem(SWIGTYPE_p_TickInfo.getCPtr(ary), index, SWIGTYPE_p_TickInfo.getCPtr(value));
  }

  public static SWIGTYPE_p_ConSessions new_ConSessionsArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConSessionsArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ConSessions(cPtr, false);
  }

  public static void delete_ConSessionsArray(SWIGTYPE_p_ConSessions ary) {
    mtmanapiJNI.delete_ConSessionsArray(SWIGTYPE_p_ConSessions.getCPtr(ary));
  }

  public static SWIGTYPE_p_ConSessions ConSessionsArray_getitem(SWIGTYPE_p_ConSessions ary, int index) {
    return new SWIGTYPE_p_ConSessions(mtmanapiJNI.ConSessionsArray_getitem(SWIGTYPE_p_ConSessions.getCPtr(ary), index), true);
  }

  public static void ConSessionsArray_setitem(SWIGTYPE_p_ConSessions ary, int index, SWIGTYPE_p_ConSessions value) {
    mtmanapiJNI.ConSessionsArray_setitem(SWIGTYPE_p_ConSessions.getCPtr(ary), index, SWIGTYPE_p_ConSessions.getCPtr(value));
  }

  public static SWIGTYPE_p_ConSession new_ConSessionArray(int nelements) {
    long cPtr = mtmanapiJNI.new_ConSessionArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ConSession(cPtr, false);
  }

  public static void delete_ConSessionArray(SWIGTYPE_p_ConSession ary) {
    mtmanapiJNI.delete_ConSessionArray(SWIGTYPE_p_ConSession.getCPtr(ary));
  }

  public static SWIGTYPE_p_ConSession ConSessionArray_getitem(SWIGTYPE_p_ConSession ary, int index) {
    return new SWIGTYPE_p_ConSession(mtmanapiJNI.ConSessionArray_getitem(SWIGTYPE_p_ConSession.getCPtr(ary), index), true);
  }

  public static void ConSessionArray_setitem(SWIGTYPE_p_ConSession ary, int index, SWIGTYPE_p_ConSession value) {
    mtmanapiJNI.ConSessionArray_setitem(SWIGTYPE_p_ConSession.getCPtr(ary), index, SWIGTYPE_p_ConSession.getCPtr(value));
  }

  public static String getS_MTManagerVersion() {
    return mtmanapiJNI.s_MTManagerVersion_get();
  }

  public static String getS_MTManagerCreate() {
    return mtmanapiJNI.s_MTManagerCreate_get();
  }

  public static String getS_MTManagerCreateExt() {
    return mtmanapiJNI.s_MTManagerCreateExt_get();
  }

  public static String getS_MTAdminCreate() {
    return mtmanapiJNI.s_MTAdminCreate_get();
  }

  public static String getS_MTAdminCreateExt() {
    return mtmanapiJNI.s_MTAdminCreateExt_get();
  }

}
