/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class MTProxyInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MTProxyInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MTProxyInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_MTProxyInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnable(int value) {
    mtmanapiJNI.MTProxyInfo_enable_set(swigCPtr, this, value);
  }

  public int getEnable() {
    return mtmanapiJNI.MTProxyInfo_enable_get(swigCPtr, this);
  }

  public void setType(int value) {
    mtmanapiJNI.MTProxyInfo_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mtmanapiJNI.MTProxyInfo_type_get(swigCPtr, this);
  }

  public void setAddress(SWIGTYPE_p_wchar_t value) {
    mtmanapiJNI.MTProxyInfo_address_set(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(value));
  }

  public SWIGTYPE_p_wchar_t getAddress() {
    long cPtr = mtmanapiJNI.MTProxyInfo_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
  }

  public void setAuth(SWIGTYPE_p_wchar_t value) {
    mtmanapiJNI.MTProxyInfo_auth_set(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(value));
  }

  public SWIGTYPE_p_wchar_t getAuth() {
    long cPtr = mtmanapiJNI.MTProxyInfo_auth_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
  }

  public MTProxyInfo() {
    this(mtmanapiJNI.new_MTProxyInfo(), true);
  }

  public final static int PROXY_SOCKS4 = mtmanapiJNI.MTProxyInfo_PROXY_SOCKS4_get();
  public final static int PROXY_SOCKS5 = mtmanapiJNI.MTProxyInfo_PROXY_SOCKS5_get();
  public final static int PROXY_HTTP = mtmanapiJNI.MTProxyInfo_PROXY_HTTP_get();
  public final static int PROXY_FIRST = mtmanapiJNI.MTProxyInfo_PROXY_FIRST_get();
  public final static int PROXY_LAST = mtmanapiJNI.MTProxyInfo_PROXY_LAST_get();

}
