/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class OnlineRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OnlineRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OnlineRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_OnlineRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCounter(int value) {
    mtmanapiJNI.OnlineRecord_counter_set(swigCPtr, this, value);
  }

  public int getCounter() {
    return mtmanapiJNI.OnlineRecord_counter_get(swigCPtr, this);
  }

  public void setReserved(int value) {
    mtmanapiJNI.OnlineRecord_reserved_set(swigCPtr, this, value);
  }

  public int getReserved() {
    return mtmanapiJNI.OnlineRecord_reserved_get(swigCPtr, this);
  }

  public void setLogin(int value) {
    mtmanapiJNI.OnlineRecord_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.OnlineRecord_login_get(swigCPtr, this);
  }

  public void setIp(long value) {
    mtmanapiJNI.OnlineRecord_ip_set(swigCPtr, this, value);
  }

  public long getIp() {
    return mtmanapiJNI.OnlineRecord_ip_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    mtmanapiJNI.OnlineRecord_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return mtmanapiJNI.OnlineRecord_group_get(swigCPtr, this);
  }

  public OnlineRecord() {
    this(mtmanapiJNI.new_OnlineRecord(), true);
  }

}
