/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class PluginInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PluginInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PluginInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_PluginInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    mtmanapiJNI.PluginInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return mtmanapiJNI.PluginInfo_name_get(swigCPtr, this);
  }

  public void setVersion(long value) {
    mtmanapiJNI.PluginInfo_version_set(swigCPtr, this, value);
  }

  public long getVersion() {
    return mtmanapiJNI.PluginInfo_version_get(swigCPtr, this);
  }

  public void setCopyright(String value) {
    mtmanapiJNI.PluginInfo_copyright_set(swigCPtr, this, value);
  }

  public String getCopyright() {
    return mtmanapiJNI.PluginInfo_copyright_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.PluginInfo_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.PluginInfo_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public PluginInfo() {
    this(mtmanapiJNI.new_PluginInfo(), true);
  }

}
