/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class RateInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RateInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RateInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_RateInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCtm(int value) {
    mtmanapiJNI.RateInfo_ctm_set(swigCPtr, this, value);
  }

  public int getCtm() {
    return mtmanapiJNI.RateInfo_ctm_get(swigCPtr, this);
  }

  public void setOpen(int value) {
    mtmanapiJNI.RateInfo_open_set(swigCPtr, this, value);
  }

  public int getOpen() {
    return mtmanapiJNI.RateInfo_open_get(swigCPtr, this);
  }

  public void setHigh(int value) {
    mtmanapiJNI.RateInfo_high_set(swigCPtr, this, value);
  }

  public int getHigh() {
    return mtmanapiJNI.RateInfo_high_get(swigCPtr, this);
  }

  public void setLow(int value) {
    mtmanapiJNI.RateInfo_low_set(swigCPtr, this, value);
  }

  public int getLow() {
    return mtmanapiJNI.RateInfo_low_get(swigCPtr, this);
  }

  public void setClose(int value) {
    mtmanapiJNI.RateInfo_close_set(swigCPtr, this, value);
  }

  public int getClose() {
    return mtmanapiJNI.RateInfo_close_get(swigCPtr, this);
  }

  public void setVol(double value) {
    mtmanapiJNI.RateInfo_vol_set(swigCPtr, this, value);
  }

  public double getVol() {
    return mtmanapiJNI.RateInfo_vol_get(swigCPtr, this);
  }

  public RateInfo() {
    this(mtmanapiJNI.new_RateInfo(), true);
  }

}
