/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class ServerLog {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ServerLog(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServerLog obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_ServerLog(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCode(int value) {
    mtmanapiJNI.ServerLog_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return mtmanapiJNI.ServerLog_code_get(swigCPtr, this);
  }

  public void setTime(String value) {
    mtmanapiJNI.ServerLog_time_set(swigCPtr, this, value);
  }

  public String getTime() {
    return mtmanapiJNI.ServerLog_time_get(swigCPtr, this);
  }

  public void setIp(String value) {
    mtmanapiJNI.ServerLog_ip_set(swigCPtr, this, value);
  }

  public String getIp() {
    return mtmanapiJNI.ServerLog_ip_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    mtmanapiJNI.ServerLog_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return mtmanapiJNI.ServerLog_message_get(swigCPtr, this);
  }

  public ServerLog() {
    this(mtmanapiJNI.new_ServerLog(), true);
  }

}
