/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class SymbolProperties {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SymbolProperties(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymbolProperties obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_SymbolProperties(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.SymbolProperties_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.SymbolProperties_symbol_get(swigCPtr, this);
  }

  public void setColor(SWIGTYPE_p_COLORREF value) {
    mtmanapiJNI.SymbolProperties_color_set(swigCPtr, this, SWIGTYPE_p_COLORREF.getCPtr(value));
  }

  public SWIGTYPE_p_COLORREF getColor() {
    return new SWIGTYPE_p_COLORREF(mtmanapiJNI.SymbolProperties_color_get(swigCPtr, this), true);
  }

  public void setSpread(int value) {
    mtmanapiJNI.SymbolProperties_spread_set(swigCPtr, this, value);
  }

  public int getSpread() {
    return mtmanapiJNI.SymbolProperties_spread_get(swigCPtr, this);
  }

  public void setSpread_balance(int value) {
    mtmanapiJNI.SymbolProperties_spread_balance_set(swigCPtr, this, value);
  }

  public int getSpread_balance() {
    return mtmanapiJNI.SymbolProperties_spread_balance_get(swigCPtr, this);
  }

  public void setStops_level(int value) {
    mtmanapiJNI.SymbolProperties_stops_level_set(swigCPtr, this, value);
  }

  public int getStops_level() {
    return mtmanapiJNI.SymbolProperties_stops_level_get(swigCPtr, this);
  }

  public void setSmoothing(int value) {
    mtmanapiJNI.SymbolProperties_smoothing_set(swigCPtr, this, value);
  }

  public int getSmoothing() {
    return mtmanapiJNI.SymbolProperties_smoothing_get(swigCPtr, this);
  }

  public void setExemode(int value) {
    mtmanapiJNI.SymbolProperties_exemode_set(swigCPtr, this, value);
  }

  public int getExemode() {
    return mtmanapiJNI.SymbolProperties_exemode_get(swigCPtr, this);
  }

  public void setReserved(SWIGTYPE_p_int value) {
    mtmanapiJNI.SymbolProperties_reserved_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getReserved() {
    long cPtr = mtmanapiJNI.SymbolProperties_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public SymbolProperties() {
    this(mtmanapiJNI.new_SymbolProperties(), true);
  }

}
