/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class SymbolInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SymbolInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymbolInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_SymbolInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    mtmanapiJNI.SymbolInfo_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.SymbolInfo_symbol_get(swigCPtr, this);
  }

  public void setDigits(int value) {
    mtmanapiJNI.SymbolInfo_digits_set(swigCPtr, this, value);
  }

  public int getDigits() {
    return mtmanapiJNI.SymbolInfo_digits_get(swigCPtr, this);
  }

  public void setCount(int value) {
    mtmanapiJNI.SymbolInfo_count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return mtmanapiJNI.SymbolInfo_count_get(swigCPtr, this);
  }

  public void setVisible(int value) {
    mtmanapiJNI.SymbolInfo_visible_set(swigCPtr, this, value);
  }

  public int getVisible() {
    return mtmanapiJNI.SymbolInfo_visible_get(swigCPtr, this);
  }

  public void setType(int value) {
    mtmanapiJNI.SymbolInfo_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mtmanapiJNI.SymbolInfo_type_get(swigCPtr, this);
  }

  public void setPoint(double value) {
    mtmanapiJNI.SymbolInfo_point_set(swigCPtr, this, value);
  }

  public double getPoint() {
    return mtmanapiJNI.SymbolInfo_point_get(swigCPtr, this);
  }

  public void setSpread(int value) {
    mtmanapiJNI.SymbolInfo_spread_set(swigCPtr, this, value);
  }

  public int getSpread() {
    return mtmanapiJNI.SymbolInfo_spread_get(swigCPtr, this);
  }

  public void setSpread_balance(int value) {
    mtmanapiJNI.SymbolInfo_spread_balance_set(swigCPtr, this, value);
  }

  public int getSpread_balance() {
    return mtmanapiJNI.SymbolInfo_spread_balance_get(swigCPtr, this);
  }

  public void setDirection(int value) {
    mtmanapiJNI.SymbolInfo_direction_set(swigCPtr, this, value);
  }

  public int getDirection() {
    return mtmanapiJNI.SymbolInfo_direction_get(swigCPtr, this);
  }

  public void setUpdateflag(int value) {
    mtmanapiJNI.SymbolInfo_updateflag_set(swigCPtr, this, value);
  }

  public int getUpdateflag() {
    return mtmanapiJNI.SymbolInfo_updateflag_get(swigCPtr, this);
  }

  public void setLasttime(int value) {
    mtmanapiJNI.SymbolInfo_lasttime_set(swigCPtr, this, value);
  }

  public int getLasttime() {
    return mtmanapiJNI.SymbolInfo_lasttime_get(swigCPtr, this);
  }

  public void setBid(double value) {
    mtmanapiJNI.SymbolInfo_bid_set(swigCPtr, this, value);
  }

  public double getBid() {
    return mtmanapiJNI.SymbolInfo_bid_get(swigCPtr, this);
  }

  public void setAsk(double value) {
    mtmanapiJNI.SymbolInfo_ask_set(swigCPtr, this, value);
  }

  public double getAsk() {
    return mtmanapiJNI.SymbolInfo_ask_get(swigCPtr, this);
  }

  public void setHigh(double value) {
    mtmanapiJNI.SymbolInfo_high_set(swigCPtr, this, value);
  }

  public double getHigh() {
    return mtmanapiJNI.SymbolInfo_high_get(swigCPtr, this);
  }

  public void setLow(double value) {
    mtmanapiJNI.SymbolInfo_low_set(swigCPtr, this, value);
  }

  public double getLow() {
    return mtmanapiJNI.SymbolInfo_low_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    mtmanapiJNI.SymbolInfo_commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return mtmanapiJNI.SymbolInfo_commission_get(swigCPtr, this);
  }

  public void setComm_type(int value) {
    mtmanapiJNI.SymbolInfo_comm_type_set(swigCPtr, this, value);
  }

  public int getComm_type() {
    return mtmanapiJNI.SymbolInfo_comm_type_get(swigCPtr, this);
  }

  public SymbolInfo() {
    this(mtmanapiJNI.new_SymbolInfo(), true);
  }

}
