/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt4.api;

public class TradeRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TradeRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TradeRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_TradeRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrder(int value) {
    mtmanapiJNI.TradeRecord_order_set(swigCPtr, this, value);
  }

  public int getOrder() {
    return mtmanapiJNI.TradeRecord_order_get(swigCPtr, this);
  }

  public void setLogin(int value) {
    mtmanapiJNI.TradeRecord_login_set(swigCPtr, this, value);
  }

  public int getLogin() {
    return mtmanapiJNI.TradeRecord_login_get(swigCPtr, this);
  }

  public void setSymbol(String value) {
    mtmanapiJNI.TradeRecord_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return mtmanapiJNI.TradeRecord_symbol_get(swigCPtr, this);
  }

  public void setDigits(int value) {
    mtmanapiJNI.TradeRecord_digits_set(swigCPtr, this, value);
  }

  public int getDigits() {
    return mtmanapiJNI.TradeRecord_digits_get(swigCPtr, this);
  }

  public void setCmd(int value) {
    mtmanapiJNI.TradeRecord_cmd_set(swigCPtr, this, value);
  }

  public int getCmd() {
    return mtmanapiJNI.TradeRecord_cmd_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    mtmanapiJNI.TradeRecord_volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return mtmanapiJNI.TradeRecord_volume_get(swigCPtr, this);
  }

  public void setOpen_time(int value) {
    mtmanapiJNI.TradeRecord_open_time_set(swigCPtr, this, value);
  }

  public int getOpen_time() {
    return mtmanapiJNI.TradeRecord_open_time_get(swigCPtr, this);
  }

  public void setState(int value) {
    mtmanapiJNI.TradeRecord_state_set(swigCPtr, this, value);
  }

  public int getState() {
    return mtmanapiJNI.TradeRecord_state_get(swigCPtr, this);
  }

  public void setOpen_price(double value) {
    mtmanapiJNI.TradeRecord_open_price_set(swigCPtr, this, value);
  }

  public double getOpen_price() {
    return mtmanapiJNI.TradeRecord_open_price_get(swigCPtr, this);
  }

  public void setSl(double value) {
    mtmanapiJNI.TradeRecord_sl_set(swigCPtr, this, value);
  }

  public double getSl() {
    return mtmanapiJNI.TradeRecord_sl_get(swigCPtr, this);
  }

  public void setTp(double value) {
    mtmanapiJNI.TradeRecord_tp_set(swigCPtr, this, value);
  }

  public double getTp() {
    return mtmanapiJNI.TradeRecord_tp_get(swigCPtr, this);
  }

  public void setClose_time(int value) {
    mtmanapiJNI.TradeRecord_close_time_set(swigCPtr, this, value);
  }

  public int getClose_time() {
    return mtmanapiJNI.TradeRecord_close_time_get(swigCPtr, this);
  }

  public void setGw_volume(int value) {
    mtmanapiJNI.TradeRecord_gw_volume_set(swigCPtr, this, value);
  }

  public int getGw_volume() {
    return mtmanapiJNI.TradeRecord_gw_volume_get(swigCPtr, this);
  }

  public void setExpiration(int value) {
    mtmanapiJNI.TradeRecord_expiration_set(swigCPtr, this, value);
  }

  public int getExpiration() {
    return mtmanapiJNI.TradeRecord_expiration_get(swigCPtr, this);
  }

  public void setReason(char value) {
    mtmanapiJNI.TradeRecord_reason_set(swigCPtr, this, value);
  }

  public char getReason() {
    return mtmanapiJNI.TradeRecord_reason_get(swigCPtr, this);
  }

  public void setConv_reserv(String value) {
    mtmanapiJNI.TradeRecord_conv_reserv_set(swigCPtr, this, value);
  }

  public String getConv_reserv() {
    return mtmanapiJNI.TradeRecord_conv_reserv_get(swigCPtr, this);
  }

  public void setConv_rates(SWIGTYPE_p_double value) {
    mtmanapiJNI.TradeRecord_conv_rates_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getConv_rates() {
    long cPtr = mtmanapiJNI.TradeRecord_conv_rates_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setCommission(double value) {
    mtmanapiJNI.TradeRecord_commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return mtmanapiJNI.TradeRecord_commission_get(swigCPtr, this);
  }

  public void setCommission_agent(double value) {
    mtmanapiJNI.TradeRecord_commission_agent_set(swigCPtr, this, value);
  }

  public double getCommission_agent() {
    return mtmanapiJNI.TradeRecord_commission_agent_get(swigCPtr, this);
  }

  public void setStorage(double value) {
    mtmanapiJNI.TradeRecord_storage_set(swigCPtr, this, value);
  }

  public double getStorage() {
    return mtmanapiJNI.TradeRecord_storage_get(swigCPtr, this);
  }

  public void setClose_price(double value) {
    mtmanapiJNI.TradeRecord_close_price_set(swigCPtr, this, value);
  }

  public double getClose_price() {
    return mtmanapiJNI.TradeRecord_close_price_get(swigCPtr, this);
  }

  public void setProfit(double value) {
    mtmanapiJNI.TradeRecord_profit_set(swigCPtr, this, value);
  }

  public double getProfit() {
    return mtmanapiJNI.TradeRecord_profit_get(swigCPtr, this);
  }

  public void setTaxes(double value) {
    mtmanapiJNI.TradeRecord_taxes_set(swigCPtr, this, value);
  }

  public double getTaxes() {
    return mtmanapiJNI.TradeRecord_taxes_get(swigCPtr, this);
  }

  public void setMagic(int value) {
    mtmanapiJNI.TradeRecord_magic_set(swigCPtr, this, value);
  }

  public int getMagic() {
    return mtmanapiJNI.TradeRecord_magic_get(swigCPtr, this);
  }

  public void setComment(String value) {
    mtmanapiJNI.TradeRecord_comment_set(swigCPtr, this, value);
  }

  public String getComment() {
    return mtmanapiJNI.TradeRecord_comment_get(swigCPtr, this);
  }

  public void setGw_order(int value) {
    mtmanapiJNI.TradeRecord_gw_order_set(swigCPtr, this, value);
  }

  public int getGw_order() {
    return mtmanapiJNI.TradeRecord_gw_order_get(swigCPtr, this);
  }

  public void setActivation(int value) {
    mtmanapiJNI.TradeRecord_activation_set(swigCPtr, this, value);
  }

  public int getActivation() {
    return mtmanapiJNI.TradeRecord_activation_get(swigCPtr, this);
  }

  public void setGw_open_price(short value) {
    mtmanapiJNI.TradeRecord_gw_open_price_set(swigCPtr, this, value);
  }

  public short getGw_open_price() {
    return mtmanapiJNI.TradeRecord_gw_open_price_get(swigCPtr, this);
  }

  public void setGw_close_price(short value) {
    mtmanapiJNI.TradeRecord_gw_close_price_set(swigCPtr, this, value);
  }

  public short getGw_close_price() {
    return mtmanapiJNI.TradeRecord_gw_close_price_get(swigCPtr, this);
  }

  public void setMargin_rate(double value) {
    mtmanapiJNI.TradeRecord_margin_rate_set(swigCPtr, this, value);
  }

  public double getMargin_rate() {
    return mtmanapiJNI.TradeRecord_margin_rate_get(swigCPtr, this);
  }

  public void setTimestamp(int value) {
    mtmanapiJNI.TradeRecord_timestamp_set(swigCPtr, this, value);
  }

  public int getTimestamp() {
    return mtmanapiJNI.TradeRecord_timestamp_get(swigCPtr, this);
  }

  public void setApi_data(SWIGTYPE_p_int value) {
    mtmanapiJNI.TradeRecord_api_data_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getApi_data() {
    long cPtr = mtmanapiJNI.TradeRecord_api_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setNext(TradeRecord value) {
    mtmanapiJNI.TradeRecord_next_set(swigCPtr, this, TradeRecord.getCPtr(value), value);
  }

  public TradeRecord getNext() {
    long cPtr = mtmanapiJNI.TradeRecord_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TradeRecord(cPtr, false);
  }

  public TradeRecord() {
    this(mtmanapiJNI.new_TradeRecord(), true);
  }

}
