/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt5.api;

public class CMTManagerAPIFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CMTManagerAPIFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CMTManagerAPIFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_CMTManagerAPIFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CMTManagerAPIFactory() {
    this(mtmanapiJNI.new_CMTManagerAPIFactory(), true);
  }

  public SWIGTYPE_p_MTAPIRES Initialize(SWIGTYPE_p_LPCWSTR dll_path) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_Initialize__SWIG_0(swigCPtr, this, SWIGTYPE_p_LPCWSTR.getCPtr(dll_path)), true);
  }

  public SWIGTYPE_p_MTAPIRES Initialize() {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_Initialize__SWIG_1(swigCPtr, this), true);
  }

  public SWIGTYPE_p_MTAPIRES Shutdown() {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_Shutdown(swigCPtr, this), true);
  }

  public SWIGTYPE_p_MTAPIRES CreateManager(long version, SWIGTYPE_p_p_IMTManagerAPI manager) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_CreateManager__SWIG_0(swigCPtr, this, version, SWIGTYPE_p_p_IMTManagerAPI.getCPtr(manager)), true);
  }

  public SWIGTYPE_p_MTAPIRES CreateAdmin(long version, SWIGTYPE_p_p_IMTAdminAPI admin) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_CreateAdmin__SWIG_0(swigCPtr, this, version, SWIGTYPE_p_p_IMTAdminAPI.getCPtr(admin)), true);
  }

  public SWIGTYPE_p_MTAPIRES CreateManager(long version, SWIGTYPE_p_LPCWSTR datapath, SWIGTYPE_p_p_IMTManagerAPI manager) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_CreateManager__SWIG_1(swigCPtr, this, version, SWIGTYPE_p_LPCWSTR.getCPtr(datapath), SWIGTYPE_p_p_IMTManagerAPI.getCPtr(manager)), true);
  }

  public SWIGTYPE_p_MTAPIRES CreateAdmin(long version, SWIGTYPE_p_LPCWSTR datapath, SWIGTYPE_p_p_IMTAdminAPI admin) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_CreateAdmin__SWIG_1(swigCPtr, this, version, SWIGTYPE_p_LPCWSTR.getCPtr(datapath), SWIGTYPE_p_p_IMTAdminAPI.getCPtr(admin)), true);
  }

  public static SWIGTYPE_p_MTAPIRES LicenseCheckManager(IMTManagerAPI manager, SWIGTYPE_p_LPCWSTR name) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_LicenseCheckManager(IMTManagerAPI.getCPtr(manager), manager, SWIGTYPE_p_LPCWSTR.getCPtr(name)), true);
  }

  public static SWIGTYPE_p_MTAPIRES LicenseCheckAdmin(IMTAdminAPI admin, SWIGTYPE_p_LPCWSTR name) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_LicenseCheckAdmin(IMTAdminAPI.getCPtr(admin), admin, SWIGTYPE_p_LPCWSTR.getCPtr(name)), true);
  }

  public SWIGTYPE_p_MTAPIRES Version(SWIGTYPE_p_unsigned_int version) {
    return new SWIGTYPE_p_MTAPIRES(mtmanapiJNI.CMTManagerAPIFactory_Version(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(version)), true);
  }

}
