/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt5.api;

public class IMTDealerSink {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IMTDealerSink(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMTDealerSink obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_IMTDealerSink(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void OnDealerResult(SWIGTYPE_p_IMTConfirm arg0) {
    mtmanapiJNI.IMTDealerSink_OnDealerResult(swigCPtr, this, SWIGTYPE_p_IMTConfirm.getCPtr(arg0));
  }

  public void OnDealerAnswer(SWIGTYPE_p_IMTRequest arg0) {
    mtmanapiJNI.IMTDealerSink_OnDealerAnswer(swigCPtr, this, SWIGTYPE_p_IMTRequest.getCPtr(arg0));
  }

  public IMTDealerSink() {
    this(mtmanapiJNI.new_IMTDealerSink(), true);
  }

}
