/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt5.api;

public class IMTManagerSink {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IMTManagerSink(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMTManagerSink obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mtmanapiJNI.delete_IMTManagerSink(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void OnDisconnect() {
    mtmanapiJNI.IMTManagerSink_OnDisconnect(swigCPtr, this);
  }

  public void OnTradeAccountSet(SWIGTYPE_p_MTAPIRES arg0, SWIGTYPE_p_signed___int64 arg1, SWIGTYPE_p_IMTUser arg2, SWIGTYPE_p_IMTAccount arg3, SWIGTYPE_p_IMTOrderArray arg4, SWIGTYPE_p_IMTPositionArray arg5) {
    mtmanapiJNI.IMTManagerSink_OnTradeAccountSet(swigCPtr, this, SWIGTYPE_p_MTAPIRES.getCPtr(arg0), SWIGTYPE_p_signed___int64.getCPtr(arg1), SWIGTYPE_p_IMTUser.getCPtr(arg2), SWIGTYPE_p_IMTAccount.getCPtr(arg3), SWIGTYPE_p_IMTOrderArray.getCPtr(arg4), SWIGTYPE_p_IMTPositionArray.getCPtr(arg5));
  }

  public void OnConnect() {
    mtmanapiJNI.IMTManagerSink_OnConnect(swigCPtr, this);
  }

  public IMTManagerSink() {
    this(mtmanapiJNI.new_IMTManagerSink(), true);
  }

}
