/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.moola.fx.mt5.api;

public interface mtmanapiConstants {
  public final static int MTManagerAPIVersion = mtmanapiJNI.MTManagerAPIVersion_get();
  public final static SWIGTYPE_p_wchar_t MTManagerAPIDate = new SWIGTYPE_p_wchar_t(mtmanapiJNI.MTManagerAPIDate_get(), false);
}
